### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'as_ast'

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#1046]
## Description

Analyzing the bytecode of [proxy.sol](https://github.com/SmartContractSecurity/SWC-registry/blob/master/test_cases/solidity/delegate_call_to_untrusted_callee/proxy/proxy.sol) crashes with an `AttributeError` that originates from the integer module.

## How to Reproduce

Using Mythril-develop:

```
$ $MYTH -xc 608060405234801561001057600080fd5b50336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555061018f806100606000396000f300608060405260043610610041576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680636fadcf7214610046575b600080fd5b34801561005257600080fd5b506100cd600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803590602001908201803590602001908080601f01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505091929192905050506100cf565b005b8173ffffffffffffffffffffffffffffffffffffffff168160405180828051906020019080838360005b838110156101145780820151818401526020810190506100f9565b50505050905090810190601f1680156101415780820380516001836020036101000a031916815260200191505b50915050600060405180830381855af4915050151561015f57600080fd5b50505600a165627a7a723058207a77fadde213fe27534b66fa1f883cdd0808e8fc3af1bbaf6ab1170c352b0b490029 
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/Users/bernhardmueller/Projects/mythril/mythril/mythril/mythril_analyzer.py", line 147, in fire_lasers
    enable_iprof=self.enable_iprof,
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/symbolic.py", line 108, in __init__
    creation_code=contract.creation_code, contract_name=contract.name
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/svm.py", line 144, in sym_exec
    self, creation_code, contract_name
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/transaction/symbolic.py", line 113, in execute_contract_creation
    laser_evm.exec(True)
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/svm.py", line 221, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/svm.py", line 270, in execute_state
    self._execute_pre_hook(op_code, global_state)
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/svm.py", line 520, in _execute_pre_hook
    hook(global_state)
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/modules/integer.py", line 110, in execute
    func(state)
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/modules/integer.py", line 177, in _handle_exp
    model = self._try_constraints(state.mstate.constraints, [constraint])
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/modules/integer.py", line 333, in _try_constraints
    return solver.get_model(constraints + new_constraints)
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/solver.py", line 39, in get_model
    s.add(constraint)
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/smt/solver/solver.py", line 37, in add
    self.raw.add(z3_constraints)
  File "/Users/bernhardmueller/.pyenv/versions/3.5.2/lib/python3.5/site-packages/z3/z3.py", line 6827, in add
    self.assert_exprs(*args)
  File "/Users/bernhardmueller/.pyenv/versions/3.5.2/lib/python3.5/site-packages/z3/z3.py", line 6823, in assert_exprs
    Z3_optimize_assert(self.ctx.ref(), self.optimize, arg.as_ast())
AttributeError: 'bool' object has no attribute 'as_ast'

The analysis was completed successfully. No issues were detected.
```

## Expected behavior

Shouldn't crash.

**Comment by norhh** [comment]
It didn't fail for me in for 10min, what was it's time limit?

**Comment by norhh** [comment]
It also didn't fail for me when timed for 20min

**Comment by b-mueller** [comment]
Fails immediately for me...

**Comment by b-mueller** [comment]
Hmm. I just run it again, now I can't reproduce the crash anymore :)

Maybe I just messed up my environment.
