### ISSUE TITLE
LevelDB support - Review by Topcoder community

### ISSUE THREAD

**Issue by birdofpreyru** [ConsenSys/mythril#105]
### Review:

-	Iterate through all existing contract accounts;
	Iterate through a subset of contract accounts, such as those with non-zero balance.
	you should use filter function as param so it can filter accounts with any filter function
	mythril\mythril\leveldb\client.py# search
	will use get_active_contracts and it will filter for non-zero balance contracts only
	although exist contact storage mythril\mythril\ether\contractstorage.py
	it will filter non balance by default

-	mythril\setup.py
	plyvel should add in requirements.txt too 

- It is not friendly to manually input path you can write function to populate default path 
	according to kinds of OS
	myth --leveldb ./geth/chaindata

- I use geth chain data from another submission and make sure your codes will use same logic to filter with accounts without consider balance
	but your search codes will return different result
	mythril\mythril\leveldb\client.py# search
	myth --leveldb ../data/geth/chaindata -s "code#PUSH#"
	use your codes directly with 
	if a.balance > 0 -> if a.balance == 0
	it will find contracts with balance=0 with different result
	Matched contract with code hash 601895bdb98d2e33c14e852b8317a6f8
	Address: 0xdeedd109f0a164952705c86b876e386728e40057efd4a3b99054c70018a867ce, balance: 0
	Matched contract with code hash 78e1ed3ce28affb391db7e33cd1432f7
	Address: 0xb310f09a10fc1e473f309bc9ccaf1e33221a050a38b8502068aa72ac1de4bf18, balance: 0
	I finally found out your account address is actually 
	Transaction address 
	(use https://github.com/etherparty/explorer)
	actually your http://take.ms/tAYXo
	is showing same error result
	your search command will show different result with or without leveldb option
	you should find way to get account address from transaction if need to 

### Appeal

RE: Response 1: Iterating through contracts via the trie doesn't have a capability to add a filter on top. So I have trie => all_accounts and active_accounts (active means non-zero balance). 
The mythril\mythril\ether\contractstorage.py is initializing a local database by iterating through all the blocks and it filters out non-zero balance when initializing.
Obviously the latter will have a smaller set, but it has to be manually synced.
The requirement was to access the leveldb directly and use it to iterate through accounts, not sync it back like the existing method does. There's no extra parameter included in geth trie keys which would allow that - it has to be done manually per account, which is exactly what's done.
For a good reference here's diagram of connections in ethereum protocol: https://i.stack.imgur.com/0UwnR.jpg
The actual implementation is a bit different per client, we are targeting geth and I did research it and concluded same: https://stackoverflow.com/questions/36291117/how-to-get-ethereum-transaction-list-by-address there're no links atm.

RE: Response 4: A couple things here: 
> I finally found out your account address is actually Transaction address 
< That's not correct, my displayed search address is sha3(address), the go-ethereum implementation is using secure version of Trie, it has hashed keys.
Here's example: a contract: http://take.ms/cIqsm and corresponding transaction http://take.ms/qyxIp
Add "print(_encode_hex(utils.sha3(accountAddress)))" in _get_account method in leveldb/client.py and run some address-based operation - you will see the corresponding tree address: http://take.ms/OePqC - it's completely different. 

Note that you CAN still use this address in my implementation when using other commands (-d/-g/-x). This is what this screenshot was about http://take.ms/tAYXo. Here's me using the obtained SHA3 for the example above: http://take.ms/a2mFf. I believe this fulfills the requirement as you need search to obtain contract addresses so you can analyze the contracts, well you can use the addresses obtained by my search for it as well.

And finally note, that you must compare the un-synced search requests. If the other submission is using sync to achieve the transaction address, then it's doing exactly same as existing functionality does. If it has found a way to retrieve the address efficiently from the contract hash, then yeah it would definitely be better, but I sincerely doubt it and you should double check this attentively before making conclusions.

### Appeal Response

I have trie => all_accounts and active_accounts (active means non-zero balance). 
you may change like this 
mythril/mythril/leveldb/client.py
def search(self, expression, callback_func, search_all=False):
so by default it will search active account but if pass search_all=True
it will filter for all account directly
we are using custom search command for leveldb storage
and you can use such way to implement requirement
or at least you should consider this requirement listed in wiki
4
OK it may be changes of geth /mythril or something 

---

### Review

- when I test under Ubuntu 16.04 it will show such error when I try to init 
	with command geth --syncmode fast --rpc
	python3 myth  --leveldb ~/.ethereum/geth/chaindata -s "code#PUSH#"
	Traceback (most recent call last):
  File "myth", line 246, in <module>
    ethDB.search(args.search, searchCallback)
  File "/home/test/Documents/LevelDB/rw/252303/mythril/mythril/leveldb/client.py", line 86, in search
    contracts = self.get_active_contracts()
  File "/home/test/Documents/LevelDB/rw/252303/mythril/mythril/leveldb/client.py", line 79, in get_active_contracts
    self.get_all_contracts() # optimized
  File "/home/test/Documents/LevelDB/rw/252303/mythril/mythril/leveldb/client.py", line 54, in get_all_contracts
    state = self._get_head_state()
  File "/home/test/Documents/LevelDB/rw/252303/mythril/mythril/leveldb/client.py", line 138, in _get_head_state
    self.headState = State(self.db, root)
  File "/home/test/Documents/LevelDB/rw/252303/mythril/mythril/leveldb/state.py", line 98, in __init__
    self.trie = Trie(self.db, root)
  File "/home/test/.local/lib/python3.5/site-packages/ethereum/trie.py", line 150, in __init__
    self.set_root_hash(root_hash)
  File "/home/test/.local/lib/python3.5/site-packages/ethereum/trie.py", line 192, in set_root_hash
    self.root_node = self._decode_to_node(root_hash)
  File "/home/test/.local/lib/python3.5/site-packages/ethereum/trie.py", line 229, in _decode_to_node
    o = rlp.decode(self.db.get(encoded))
  File "/home/test/.local/lib/python3.5/site-packages/rlp/codec.py", line 217, in decode
    rlp = str_to_bytes(rlp)
  File "/home/test/.local/lib/python3.5/site-packages/rlp/utils_py3.py", line 20, in str_to_bytes
    return bytes(value, 'utf-8')
	TypeError: encoding without a string argument

- even I try to init db with geth --syncmode fast --rpc
	./myth --init-db 
	it will always sync with 0 block even I found new blocks downloaded successfully in chaindata folder
	Starting synchronization from latest block: 0

- actually we may test with private network with smaller data and faster speed

- I actually test finally with my own way/data
	use geth block chain data from another submission
	geth  --datadir data  --rpc --rpccorsdomain http://localhost:8000
	You can use https://github.com/etherparty/explorer to view blocks
	mkdir test
	export MYTHRIL_DIR=test
	mythril\mythril\ether\contractstorage.py
	comment or remove  if not contract_balance block so will store all contacts
	./myth --init-db --rpc localhost:8545
	./myth --search "code#PUSH#"
	compare with leveldb support result(not work actually)

### Appeal

You are having trouble with initializing database over rpc, which is not in scope of the challenge, quite the contrary - the base requirement is to avoid init-db sync which is iterating over all blocks:
"To enable this feature, Mythril builds its own smart contract database. The contract data is received from an Ethereum node over IPC or RPC (--sync-db command). This is however slow and inefficient. A much better way would be to directly access the LevelDB database of a locally installed go-ethereum node." - in the specification there's a mistake --sync-db should be --init-db but otherwise it's correct with assessment. If you use a real geth chain this sync will take very long time.

The command
'python3 myth  --leveldb ~/.ethereum/geth/chaindata -s "code#PUSH#"'
will work without syncing, if the path ~/.ethereum/geth/chaindata is accessible and is indeed correct leveldb path AND as noted in DG the geth instance should not be running - since it retains a lock on database and it won't be accessible.

So all that actions weren't necessary. You just needed a closed geth instance which has some blocks with contracts in it.
The first error just shows that there wasn't any state information at the moment or the fast sync is skipping this

Also better way to launch geth with rpc on and accessible is 
geth --datadir=chaindata console --rpc --rpccorsdomain '*'
This will launch it with RPC address localhost:8545 and will be accessible even through a VM and also allow console connections like 
geth attach <path/to>/chaindata/geth.ipc
Where you can use web3 js API directly.

Also answering Q.1.3.3 I provided a whole video with examples and there's a bit more in the README.md of the reop

### Appeal Response

When I test with geth (1.8.2-stable-b8b9f7f4 under Ubuntu) with custom network deploy contract with web3 and solc
and can view  by https://github.com/etherparty/explorer
mythril.rpc.exceptions.BadResponseError: {'jsonrpc': '2.0', 'id': 1, 'error': {'message': 'invalid argument 0: hex string without 0x prefix', 'code': -32602}}
mkdir test
export MYTHRIL_DIR=test
python3 myth --init-db --rpc localhost:8545
will throw error
mythril.rpc.exceptions.BadResponseError: {'jsonrpc': '2.0', 'id': 1, 'error': {'message': 'invalid argument 0: hex string without 0x prefix', 'code': -32602}}
but I could sync with another submission successfully with same test network created by myself(work on with commit a603772956bca7059635627f87966fa8879e900b)
I know it may exist version updates with geth or mythril or something
but at least you should provide workable test data to verify
the sync all command take too long time for me to download all blocks
and I have to test with custom network
and your current deployment steps are not easy to deploy and test for leveldb support

**Comment by birdofpreyru** [comment]
@b-mueller I see you assigned it to me, but I'm not sure yet, what you want me to do about it :) At least, briefly point me the issues you see as issues, so that I take care about fixing them, and consider other points as not relevant.

**Comment by b-mueller** [comment]
@birdofpreyru no specific tasks, I only assigned as you're basically in charge of this.

I'm currently testing the submission myself and updating the [PR](https://github.com/ConsenSys/mythril/pull/106) with the results.

**Comment by N1k1tung** [comment]
> but at least you should provide workable test data to verify

Here's the datadir for private network used for making the video overview: https://drive.google.com/open?id=1boF9jysNaScHUhlQ7E3Dm7QhCRjY9aQK
