### ISSUE TITLE
parse error?

### ISSUE THREAD

**Issue by SunBeomSo** [ConsenSys/mythril#1055]
## Description

Hi,
While I am testing the code below using Mythril:
https://etherscan.io/address/0xc1ca4e6fa2d888168a34a3429bf186bcd9b475a0#contracts

I encountered an error message below. Can you please explain the error?
```
^[[34mmythril.interfaces.cli^[[0m ^[[1;30m[ERROR]:^[[0m ^[[31mTraceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.4-py3.6.egg/mythril/interfaces/cli.py", line 528, in parse_args
    disassembler=disassembler, address=address, parser=parser, args=args
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.4-py3.6.egg/mythril/interfaces/cli.py", line 452, in execute_command
    transaction_count=args.transaction_count,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.4-py3.6.egg/mythril/mythril/mythril_analyzer.py", line 161, in fire_lasers
    issue.add_code_info(contract)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.4-py3.6.egg/mythril/analysis/report.py", line 115, in add_code_info
    self.address, constructor=(self.function == "constructor")
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.4-py3.6.egg/mythril/solidity/soliditycontract.py", line 131, in get_source_info
    solidity_file = self.solidity_files[mappings[index].solidity_file_idx]
TypeError: list indices must be integers or slices, not NoneType
 ^[[0m^M
```

## How to Reproduce
My command was:
```
docker exec -it DOCKERID myth --execution-timeout 1800 -x /home/test.sol:HumanStandardToken -m integer,exceptions
```

## Environment
- Mythril version: output from 0.20.4
- Solidity compiler and version: 0.4.25
- Python version: Python 3.6.7
- OS and Version: Ubuntu 18.04.2

**Comment by norhh** [comment]
Hi @SunBeomSo, Thanks for the report, we will try to fix it soon.
