### ISSUE TITLE
Docker: Permission denied: /home/mythril/.mythril/config.ini

### ISSUE THREAD

**Issue by villesundell** [ConsenSys/mythril#1070]
## Description
When using the most recent docker images referred to by the manual (https://github.com/ConsenSys/mythril/wiki/With-Docker) I get:

```console
PermissionError: [Errno 13] Permission denied: '/home/mythril/.mythril/config.ini'
```

## How to Reproduce
Use the most recent docker image:

```console
$ docker run mythril/myth -dc "0x6060"
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.8-py3.6.egg/mythril/interfaces/cli.py", line 507, in parse_args
    config = set_config(args)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.8-py3.6.egg/mythril/interfaces/cli.py", line 321, in set_config
    config = MythrilConfig()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.8-py3.6.egg/mythril/mythril/mythril_config.py", line 29, in __init__
    self._init_config()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.8-py3.6.egg/mythril/mythril/mythril_config.py", line 71, in _init_config
    open(self.config_path, "a").close()
PermissionError: [Errno 13] Permission denied: '/home/mythril/.mythril/config.ini'
```

## Expected behavior
Expected behavior happens with 0.20.6 and below:

```console
$ docker run mythril/myth:0.20.6 -dc "0x6060"
Disassembly: 
0 PUSH1 0x60
```

## Additional Environment or Context
Versions from 0.20.6 and below work, 0.20.8 and above do not.
Maybe related to #1017 ?

**Comment by norhh** [comment]
Hey @villesundell , we will release a new version soon, till then try using mythril/myth-dev container. `docker pull mythril/myth-dev`

**Comment by villesundell** [comment]
@norhh Thanks, mythril/myth-dev seems to work for me! :slightly_smiling_face:
