### ISSUE TITLE
IndexError when bytecode does not reach a stopping instruction

### ISSUE THREAD

**Issue by nbanmp** [ConsenSys/mythril#1091]
When the end of the bytecode is reached without a stopping instruction being hit, an IndexError occurs.

```
━━┫ ./myth analyze -c 0x6000 # PUSH 0x0
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/home/nat/Dev/mythril/mythril/mythril/mythril_analyzer.py", line 157, in fire_lasers
    disable_dependency_pruning=self.disable_dependency_pruning,
  File "/home/nat/Dev/mythril/mythril/analysis/symbolic.py", line 153, in __init__
    world_state=world_state,
  File "/home/nat/Dev/mythril/mythril/laser/ethereum/svm.py", line 150, in sym_exec
    self, creation_code, contract_name, world_state=world_state
  File "/home/nat/Dev/mythril/mythril/laser/ethereum/transaction/symbolic.py", line 108, in execute_contract_creation
    laser_evm.exec(True)
  File "/home/nat/Dev/mythril/mythril/laser/ethereum/svm.py", line 228, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/home/nat/Dev/mythril/mythril/laser/ethereum/svm.py", line 267, in execute_state
    hook(global_state)
  File "/home/nat/Dev/mythril/mythril/laser/ethereum/plugins/implementations/coverage/coverage_plugin.py", line 66, in execute_state_hook
    self.coverage[code][1][global_state.mstate.pc] = True
IndexError: list assignment index out of range
```

**Comment by norhh** [comment]
Hey, thats same as this https://github.com/ConsenSys/mythril/issues/1075
