### ISSUE TITLE
Crash caused by dynamic loader

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#1168]
## Description

The recent change to activate loading of contract code by default exposed a bug that causes Mythril to crash when when the loader is initialized with an `eth` instance.

## How to Reproduce

Run Mythril against the [send loop sample contract](https://github.com/SmartContractSecurity/SWC-registry/blob/master/test_cases/solidity/call_best_practices/send_loop/send_loop.sol):

```
$ myth a -c 608060405234801561001057600080fd5b5060007379b483371e87d664cd39491b5f06250165e4b18490806001815401808255809150509060018203906000526020600020016000909192909190916101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505060007379b483371e87d664cd39491b5f06250165e4b18590806001815401808255809150509060018203906000526020600020016000909192909190916101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050610213806101146000396000f30060806040526004361061004c576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806338e771ab14610051578063bc3da53514610068575b600080fd5b34801561005d57600080fd5b506100666100bf565b005b34801561007457600080fd5b506100a9600480360381019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291905050506101cf565b6040518082815260200191505060405180910390f35b60005b6000805490508110156101cc576000818154811015156100de57fe5b9060005260206000200160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166108fc60016000808581548110151561013457fe5b9060005260206000200160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020549081150290604051600060405180830381858888f1935050505015156101bf57600080fd5b80806001019150506100c2565b50565b600160205280600052604060002060009150905054815600a165627a7a723058204f612e911a1a01486cc43dc19e9ebc244fd8c0cdc4075b829a610912a2d273bc0029
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/Users/bernhardmueller/Projects/mythril/mythril/mythril/mythril_analyzer.py", line 160, in fire_lasers
    disable_dependency_pruning=self.disable_dependency_pruning,
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/symbolic.py", line 150, in __init__
    world_state=world_state,
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/svm.py", line 164, in sym_exec
    self._execute_transactions(created_account.address)
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/svm.py", line 198, in _execute_transactions
    execute_message_call(self, address)
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/transaction/symbolic.py", line 67, in execute_message_call
    laser_evm.exec()
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/svm.py", line 228, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/svm.py", line 286, in execute_state
    ).evaluate(global_state)
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/instructions.py", line 195, in evaluate
    result = instruction_mutator(global_state)
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/instructions.py", line 143, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/instructions.py", line 85, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/instructions.py", line 1687, in call_
    global_state, self.dynamic_loader, True
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/call.py", line 54, in get_call_parameters
    global_state, callee_address, dynamic_loader
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/call.py", line 138, in get_callee_account
    code = dynamic_loader.dynld(callee_address)
  File "/Users/bernhardmueller/Projects/mythril/mythril/support/loader.py", line 86, in dynld
    code = self.eth.eth_getCode(dependency_address)
AttributeError: 'NoneType' object has no attribute 'eth_getCode'

The analysis was completed successfully. No issues were detected.
```

## Environment

Please modify for your setup

- Mythril version: develop
- Python version: 3.6.3

**Comment by palkeo** [comment]
If anybody wants to take it... Otherwise feel free to revert my PR, and I can take a look, fix that and re-submit it. I probably won't have much time before end of week to look into it.

**Comment by palkeo** [comment]
Actually I'm quickly doing it, it's an easy fix in the loader.

**Comment by b-mueller** [comment]
Awesome, thanks!
