### ISSUE TITLE
Getting critical exception in mythril.mythril.mythril_analyzer

### ISSUE THREAD

**Issue by dwaipayabasu** [ConsenSys/mythril#1201]
I was trying to analyze one solidity code written in SOLC version 4.25 with two library files. I got the below error after some time. Though mythrill has already generated few issue in the code, but not sure why after that it got the error. 
Any help in this?

mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril/mythril/mythril_analyzer.py", line 170, in fire_lasers
    custom_modules_directory=self.custom_modules_directory,
  File "/usr/local/lib/python3.6/dist-packages/mythril/analysis/symbolic.py", line 159, in __init__
    world_state=world_state,
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/svm.py", line 174, in sym_exec
    self._execute_transactions(created_account.address)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/svm.py", line 208, in _execute_transactions
    execute_message_call(self, address)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/transaction/symbolic.py", line 67, in execute_message_call
    laser_evm.exec()
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/svm.py", line 240, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/svm.py", line 290, in execute_state
    self._execute_pre_hook(op_code, global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/svm.py", line 554, in _execute_pre_hook
    hook(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/plugins/implementations/dependency_pruner.py", line 287, in sload_hook
    self.update_sloads(annotation.path, location)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/plugins/implementations/dependency_pruner.py", line 153, in update_sloads
    if target_location not in self.sloads_on_path[address]:
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/smt/bitvecfunc.py", line 261, in __eq__
    self, other, operator.eq, default_value=False, inputs_equal=True
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/smt/bitvecfunc.py", line 114, in _comparison_helper
    a.input_ == b.input_ if inputs_equal else a.input_ != b.input_,
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/smt/bitvecfunc.py", line 261, in __eq__
    self, other, operator.eq, default_value=False, inputs_equal=True
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/smt/bitvecfunc.py", line 112, in _comparison_helper
    Bool(cast(z3.BoolRef, operation(a.raw, b.raw)), annotations=union),
  File "/usr/local/lib/python3.6/dist-packages/z3/z3.py", line 917, in __eq__
    return BoolRef(Z3_mk_eq(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
  File "/usr/local/lib/python3.6/dist-packages/z3/z3core.py", line 1656, in Z3_mk_eq
    _elems.Check(a0)
  File "/usr/local/lib/python3.6/dist-packages/z3/z3core.py", line 1373, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: b'Sorts (_ BitVec 256) and (_ BitVec 512) are incompatible'

**Comment by norhh** [comment]
Hi @dwaipayabasu what version of mythril are you using? Can you provide the contract code if possible?

**Comment by nbanmp** [comment]
Closing, as there is not enough information to reproduce this, and no response has been received in a month.

Please open a new issue with mythril version information, and source/bytecode (if publicly available) if this is still an issue.
