### ISSUE TITLE
__init__() got an unexpected keyword argument

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ConsenSys/mythril#1210]
## Description
Hey guys, thanks for your awesome work!
I've tried to analyze my newest contracts but I got an error.

## How to Reproduce
Unfortunately I can not provide any source code to reproduce. 

```console
$ myth analyze contracts/contract.sol
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/mythril/mythril_analyzer.py", line 170, in fire_lasers
    custom_modules_directory=self.custom_modules_directory,
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/analysis/symbolic.py", line 99, in __init__
    or len(get_detection_modules("post", modules, custom_modules_directory)) > 0
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/analysis/security.py", line 73, in get_detection_modules
    module = importlib.import_module("mythril.analysis.modules." + module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/analysis/modules/transaction_order_dependence.py", line 161, in <module>
    detector = TxOrderDependenceModule()
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/analysis/modules/transaction_order_dependence.py", line 23, in __init__
    "This module finds the existance of transaction order dependence "
TypeError: __init__() got an unexpected keyword argument 'hooks'

mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/mythril/mythril_analyzer.py", line 170, in fire_lasers
    custom_modules_directory=self.custom_modules_directory,
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/analysis/symbolic.py", line 99, in __init__
    or len(get_detection_modules("post", modules, custom_modules_directory)) > 0
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/analysis/security.py", line 73, in get_detection_modules
    module = importlib.import_module("mythril.analysis.modules." + module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/analysis/modules/transaction_order_dependence.py", line 161, in <module>
    detector = TxOrderDependenceModule()
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/analysis/modules/transaction_order_dependence.py", line 23, in __init__
    "This module finds the existance of transaction order dependence "
TypeError: __init__() got an unexpected keyword argument 'hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 717, in parse_args_and_execute
    disassembler=disassembler, address=address, parser=parser, args=args
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 633, in execute_command
    transaction_count=args.transaction_count,
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/mythril/mythril_analyzer.py", line 184, in fire_lasers
    modules, self.custom_modules_directory
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/analysis/security.py", line 123, in retrieve_callback_issues
    custom_modules_directory=custom_modules_directory,
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/analysis/security.py", line 73, in get_detection_modules
    module = importlib.import_module("mythril.analysis.modules." + module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/analysis/modules/transaction_order_dependence.py", line 161, in <module>
    detector = TxOrderDependenceModule()
  File "/home/asdf/.local/lib/python3.6/site-packages/mythril/analysis/modules/transaction_order_dependence.py", line 23, in __init__
    "This module finds the existance of transaction order dependence "
TypeError: __init__() got an unexpected keyword argument 'hooks'
```

## Environment
```console 
$ myth --version 
Mythril version v0.21.16
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.5.11+commit.22be8592.Linux.g++
```

**Comment by MariusVanDerWijden** [comment]
@norhh I did reinstall it `pip3 uninstall mythril; pip3 install mythril --no-cache-dir` but the problem persists. I'll try to downgrade now and see if that works.

**Comment by MariusVanDerWijden** [comment]
I got it working now, the problem was, my pip3 was not on the latest version. 
So I had to update pip3

` pip3 install --upgrade pip` and then upgrade py-ecc since it clashed 
`pip3 uninstall py-ecc; pip3 install py-ecc --user`  and at the end reinstall mythril 
`pip3 install mythril --no-cache-dir --user`

An mythril found no issues in my contract ;) Thanks!
