### ISSUE TITLE
Experiencing critical exception in mythril.mythril.mythril_analyzer

### ISSUE THREAD

**Issue by cstrangedk** [ConsenSys/mythril#1214]
Experiencing same error as reported previously #1201 

Tested on different contracts (not publicly available)...

Using docker container `docker pull mythril/myth`
Mythril version v0.21.16

```
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.16-py3.6.egg/mythril/mythril/mythril_analyzer.py", line 170, in fire_lasers
    custom_modules_directory=self.custom_modules_directory,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.16-py3.6.egg/mythril/analysis/symbolic.py", line 160, in __init__
    world_state=world_state,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.16-py3.6.egg/mythril/laser/ethereum/svm.py", line 174, in sym_exec
    self._execute_transactions(created_account.address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.16-py3.6.egg/mythril/laser/ethereum/svm.py", line 208, in _execute_transactions
    execute_message_call(self, address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.16-py3.6.egg/mythril/laser/ethereum/transaction/symbolic.py", line 67, in execute_message_call
    laser_evm.exec()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.16-py3.6.egg/mythril/laser/ethereum/svm.py", line 240, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.16-py3.6.egg/mythril/laser/ethereum/svm.py", line 290, in execute_state
    self._execute_pre_hook(op_code, global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.16-py3.6.egg/mythril/laser/ethereum/svm.py", line 556, in _execute_pre_hook
    hook(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.16-py3.6.egg/mythril/laser/ethereum/plugins/implementations/dependency_pruner.py", line 273, in sstore_hook
    self.update_sstores(annotation.path, location)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.16-py3.6.egg/mythril/laser/ethereum/plugins/implementations/dependency_pruner.py", line 167, in update_sstores
    if target_location not in self.sstores_on_path[address]:
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.16-py3.6.egg/mythril/laser/smt/bitvecfunc.py", line 261, in __eq__
    self, other, operator.eq, default_value=False, inputs_equal=True
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.16-py3.6.egg/mythril/laser/smt/bitvecfunc.py", line 114, in _comparison_helper
    a.input_ == b.input_ if inputs_equal else a.input_ != b.input_,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.16-py3.6.egg/mythril/laser/smt/bitvecfunc.py", line 261, in __eq__
    self, other, operator.eq, default_value=False, inputs_equal=True
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.16-py3.6.egg/mythril/laser/smt/bitvecfunc.py", line 112, in _comparison_helper
    Bool(cast(z3.BoolRef, operation(a.raw, b.raw)), annotations=union),
  File "/usr/local/lib/python3.6/dist-packages/z3/z3.py", line 917, in __eq__
    return BoolRef(Z3_mk_eq(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
  File "/usr/local/lib/python3.6/dist-packages/z3/z3core.py", line 1656, in Z3_mk_eq
    _elems.Check(a0)
  File "/usr/local/lib/python3.6/dist-packages/z3/z3core.py", line 1373, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: b'Sorts (_ BitVec 256) and (_ BitVec 512) are incompatible'

The analysis was completed successfully. No issues were detected.
```

**Comment by norhh** [comment]
Hi @cstrangedk, thanks for the report, can you put the contract in here by any chance?

**Comment by cstrangedk** [comment]
@norhh sorry, contract is not public yet

**Comment by norhh** [comment]
In that case can you provide a modified and much smaller version of contract(so that it wouldn't be a problem) in which this error occurs? As that would be helpful.
