### ISSUE TITLE
`CRITICAL` in loader.py/machine_state.py

### ISSUE THREAD

**Issue by Danc2050** [ConsenSys/mythril#1232]
## Description

A `CRITICAL` error is given with the address mentioned below using the command below:

## How to Reproduce

**Input** `docker run mythril/myth -v4 analyze -1 -a 0x04c4b45aacc60dcbb8e5d09695b95935319f5c76` ~`myth -v4 analyze -1 -a 0x04c4b45aacc60dcbb8e5d09695b95935319f5c76`~
**Output**
```mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/support/loader.py", line 38, in read_storage
    contract_ref = self.storage_cache[contract_address]
KeyError: '0x4c4b45aacc60dcbb8e5d09695b95935319f5c76'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/ethereum/interface/rpc/client.py", line 74, in _call
    return response["result"]
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/mythril/mythril_analyzer.py", line 155, in fire_lasers
    disable_dependency_pruning=self.disable_dependency_pruning,
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/analysis/symbolic.py", line 163, in __init__
    self.laser.sym_exec(world_state=world_state, target_address=address.value)
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 144, in sym_exec
    self._execute_transactions(symbol_factory.BitVecVal(target_address, 256))
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 198, in _execute_transactions
    execute_message_call(self, address)
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/transaction/symbolic.py", line 67, in execute_message_call
    laser_evm.exec()
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 228, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 286, in execute_state
    ).evaluate(global_state)
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 195, in evaluate
    result = instruction_mutator(global_state)
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 143, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 85, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 1394, in sload_
    state.stack.append(global_state.environment.active_account.storage[index])
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/state/account.py", line 68, in __getitem__
    index=int(item.value),
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/support/loader.py", line 46, in read_storage
    contract_address, position=index, block="latest"
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/ethereum/interface/rpc/base_client.py", line 71, in eth_getStorageAt
    return self._call("eth_getStorageAt", [address, hex(position), block])
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/ethereum/interface/rpc/client.py", line 76, in _call
    raise BadResponseError(response)
mythril.ethereum.interface.rpc.exceptions.BadResponseError: {'jsonrpc': '2.0', 'id': 1, 'error': {'code': -32602, 'message': 'invalid argument 0: json: cannot unmarshal hex string of odd length into Go value of type common.Address'}}```

## Expected behavior

Symbolic Execution should run without error(s).

**Comment by norhh** [comment]
@Danc2050 thanks for the bug report, I am thinking this might be a one time response, can you rerun it and check because I can't reproduce this but am getting a different bug when I ran it.

**Comment by Danc2050** [comment]
@norhh Of course.

My apologies, the `machine_state.py` error occurs in Docker, whereas I still get the `loader.py` error using the pip3 CLI version:

```mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/support/loader.py", line 38, in read_storage
    contract_ref = self.storage_cache[contract_address]
KeyError: '0x4c4b45aacc60dcbb8e5d09695b95935319f5c76'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/ethereum/interface/rpc/client.py", line 74, in _call
    return response["result"]
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/mythril/mythril_analyzer.py", line 155, in fire_lasers
    disable_dependency_pruning=self.disable_dependency_pruning,
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/analysis/symbolic.py", line 163, in __init__
    self.laser.sym_exec(world_state=world_state, target_address=address.value)
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 144, in sym_exec
    self._execute_transactions(symbol_factory.BitVecVal(target_address, 256))
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 198, in _execute_transactions
    execute_message_call(self, address)
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/transaction/symbolic.py", line 67, in execute_message_call
    laser_evm.exec()
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 228, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 286, in execute_state
    ).evaluate(global_state)
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 195, in evaluate
    result = instruction_mutator(global_state)
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 143, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 85, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 1394, in sload_
    state.stack.append(global_state.environment.active_account.storage[index])
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/laser/ethereum/state/account.py", line 68, in __getitem__
    index=int(item.value),
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/support/loader.py", line 46, in read_storage
    contract_address, position=index, block="latest"
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/ethereum/interface/rpc/base_client.py", line 71, in eth_getStorageAt
    return self._call("eth_getStorageAt", [address, hex(position), block])
  File "/home/danc2/.local/lib/python3.6/site-packages/mythril/ethereum/interface/rpc/client.py", line 76, in _call
    raise BadResponseError(response)
mythril.ethereum.interface.rpc.exceptions.BadResponseError: {'jsonrpc': '2.0', 'id': 1, 'error': {'code': -32602, 'message': 'invalid argument 0: json: cannot unmarshal hex string of odd length into Go value of type common.Address'}}
```

Docker, using the command docker run mythril/myth -v4 analyze -1 -a 0x04c4b45aacc60dcbb8e5d09695b95935319f5c76, I get the machine_state.py error:

```mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.17-py3.6.egg/mythril/laser/ethereum/state/machine_state.py", line 63, in __getitem__
    return super(MachineStack, self).__getitem__(item)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.17-py3.6.egg/mythril/mythril/mythril_analyzer.py", line 170, in fire_lasers
    custom_modules_directory=self.custom_modules_directory,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.17-py3.6.egg/mythril/analysis/symbolic.py", line 179, in __init__
    self.laser.sym_exec(world_state=world_state, target_address=address.value)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.17-py3.6.egg/mythril/laser/ethereum/svm.py", line 158, in sym_exec
    self._execute_transactions(symbol_factory.BitVecVal(target_address, 256))
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.17-py3.6.egg/mythril/laser/ethereum/svm.py", line 212, in _execute_transactions
    execute_message_call(self, address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.17-py3.6.egg/mythril/laser/ethereum/transaction/symbolic.py", line 67, in execute_message_call
    laser_evm.exec()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.17-py3.6.egg/mythril/laser/ethereum/svm.py", line 244, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.17-py3.6.egg/mythril/laser/ethereum/svm.py", line 294, in execute_state
    self._execute_pre_hook(op_code, global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.17-py3.6.egg/mythril/laser/ethereum/svm.py", line 584, in _execute_pre_hook
    hook(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.17-py3.6.egg/mythril/analysis/modules/base.py", line 56, in execute
    self._execute(statespace)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.17-py3.6.egg/mythril/analysis/modules/dos.py", line 58, in _execute
    issues = self._analyze_state(state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.17-py3.6.egg/mythril/analysis/modules/dos.py", line 85, in _analyze_state
    target = util.get_concrete_int(state.mstate.stack[-1])
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.21.17-py3.6.egg/mythril/laser/ethereum/state/machine_state.py", line 66, in __getitem__
    "Trying to access a stack element which doesn't exist"
mythril.laser.ethereum.evm_exceptions.StackUnderflowException: Trying to access a stack element which doesn't exist
```

**Comment by norhh** [comment]
Yes I got the second error, am currently working on it. 
For the first one can you post the output of `pip freeze`? As the cause for that is a dependency issue.

**Comment by Danc2050** [comment]
Here it is...sorry it is a long list.

https://pastebin.com/3CD9SdDX
