### ISSUE TITLE
Analysis crashes, with `TypeError: 'BitVec' object cannot be interpreted as an integer`

### ISSUE THREAD

**Issue by fiddlemath** [ConsenSys/mythril#1243]
## Description

When analyzing [this solidity file](https://github.com/reserve-protocol/rsv-v2/blob/236cfbc298c04dad237660b2a8d249ddd22d1b27/contracts/Proposal.sol), mythril crashes with the error `TypeError: 'BitVec' object cannot be interpreted as an integer`

## How to Reproduce

1. Check out https://github.com/reserve-protocol/rsv-v2/tree/236cfbc298c04dad237660b2a8d249ddd22d1b27

2. Run either `make analysis/Proposal.myth.md` or `myth a contracts/Proposal.sol` from that repo's root.

## Screenshots

```console
$ myth a contracts/Proposal.sol > analysis/Proposal.myth.md
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mythril/mythril/mythril_analyzer.py", line 170, in fire_lasers
    custom_modules_directory=self.custom_modules_directory,
  File "/usr/local/lib/python3.7/site-packages/mythril/analysis/symbolic.py", line 160, in __init__
    world_state=world_state,
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/svm.py", line 178, in sym_exec
    self._execute_transactions(created_account.address)
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/svm.py", line 212, in _execute_transactions
    execute_message_call(self, address)
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/transaction/symbolic.py", line 67, in execute_message_call
    laser_evm.exec()
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/svm.py", line 244, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/svm.py", line 302, in execute_state
    ).evaluate(global_state)
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/instructions.py", line 239, in evaluate
    result = instruction_mutator(global_state)
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/instructions.py", line 186, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/instructions.py", line 121, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/instructions.py", line 1729, in create_
    global_state, call_value, mem_offset, mem_size
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/instructions.py", line 1674, in _create_transaction_helper
    for i in range(call_data.size):
TypeError: 'BitVec' object cannot be interpreted as an integer
```

## Environment

solc version 0.5.7, as fetched via [solc-select](https://github.com/crytic/solc-select)

``` console
$ pip3 show mythril
Name: mythril
Version: 0.21.17
Summary: Security analysis tool for Ethereum smart contracts
Home-page: https://github.com/ConsenSys/mythril
Author: ConsenSys Dilligence
Author-email: None
License: MIT
Location: /usr/local/lib/python3.7/site-packages
Requires: pythx, ethereum, eth-tester, persistent, py-solc, z3-solver, coloredlogs, requests, mock, eth-hash, eth-abi, transaction, eth-keyfile, eth-keys, rlp, eth-typing, configparser, jinja2, plyvel, matplotlib, coverage, py-ecc, ethereum-input-decoder, eth-account, py-flags, eth-rlp
Required-by:
```

## Additional Context

The same analysis runs in the same environment (from the same makefile, even) on the _other_ solidity files in that repository. 

This contract is already deployed, and our team is moving on, so this bug is not urgent to us right now. However, given that this is an easily-sharable failure case, and since mythril has been a useful tool, I figured I'd leave a bug report.

Thanks for the good work!

**Comment by norhh** [comment]
Hi @fiddlemath thanks for the bug report.
