### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by lpassos** [ConsenSys/mythril#1286]
## Description

A type error occurs when running mythril against a target contract: `TypeError: 'NoneType' object is not iterable`. Unfortunately, I cannot paste the target contract here as it not public.
Nonetheless, the stack trace is as follows:

```
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril/mythril/mythril_analyzer.py", line 147, in fire_lasers
    enable_iprof=self.enable_iprof,
  File "/usr/local/lib/python3.6/dist-packages/mythril/analysis/symbolic.py", line 107, in __init__
    creation_code=contract.creation_code, contract_name=contract.name
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/svm.py", line 140, in sym_exec
    self, creation_code, contract_name
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/transaction/symbolic.py", line 102, in execute_contract_creation
    laser_evm.exec(True)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/svm.py", line 217, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/svm.py", line 270, in execute_state
    ).evaluate(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/instructions.py", line 199, in evaluate
    result = instruction_mutator(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/instructions.py", line 146, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/instructions.py", line 90, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/instructions.py", line 1785, in suicide_
    global_state.current_transaction.end(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/transaction/transaction_models.py", line 183, in end
    not all([isinstance(element, int) for element in return_data])
TypeError: 'NoneType' object is not iterable
```

### Version
Mythril version v0.20.4

**Comment by norhh** [comment]
Hey @lpassos , can you try it out with the latest version `0.21.20`?

**Comment by norhh** [comment]
This should be fixed now, @lpassos if the issue still persists, feel free to reopen the issue.
