### ISSUE TITLE
CircleCI: Build error related to laser-ethereum

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#131]
After setting up CI and auto-deployment with LASER, Mythril fails to build in CircleCI (tests run successfully on my local machine though).

I created the new tag [v0.16.0](https://github.com/b-mueller/laser-ethereum/releases/tag/v0.16.0), which was [successfully deployed on Pypi](https://pypi.org/project/laser-ethereum/). Perhaps I messed something up in the process. Building Mythril in CircleCI I get:

```
Building wheels for collected packages: MarkupSafe
  Running setup.py bdist_wheel for MarkupSafe ... - \ done
  Stored in directory: /root/.cache/pip/wheels/33/56/20/ebe49a5c612fffe1c5a632146b16596f9e64676768661e4e46
Successfully built MarkupSafe
Installing collected packages: laser-ethereum, MarkupSafe, jinja2
  Found existing installation: laser-ethereum .16.5
    Uninstalling laser-ethereum-.16.5:
      Successfully uninstalled laser-ethereum-.16.5
Successfully installed MarkupSafe-1.0 jinja2-2.10 laser-ethereum-0.16.0
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/__init__.py", line 246, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/basecommand.py", line 264, in main
    timeout=min(5, options.timeout)) as session:
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/basecommand.py", line 81, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/download.py", line 338, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/download.py", line 127, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/misc.py", line 829, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 558, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 614, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1882, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1399, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1756, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1633, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1590, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/laser_ethereum-.16.5-py3.6.egg'
Exited with code 1
```

@birdofpreyru, could you please have a look?

**Comment by b-mueller** [comment]
Interesting, I made an unrelated update and the test is passing. Nevermind then.
