### ISSUE TITLE
Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.

### ISSUE THREAD

**Issue by damarnez** [ConsenSys/mythril#1390]
## Description

Each time I try to analyze my contracts, I recieve this error.

## How to Reproduce

```console
docker run -v $(pwd):/tmp mythril/myth -v4 analyze /tmp/contracts/marketplace/Position_flat.sol:Position --solv 0.5.10
```

```console
mythril.laser.ethereum.svm [INFO]: Starting message call transaction, iteration: 1, 2 initial states
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.22.4-py3.6.egg/mythril/mythril/mythril_analyzer.py", line 162, in fire_lasers
    custom_modules_directory=self.custom_modules_directory,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.22.4-py3.6.egg/mythril/analysis/symbolic.py", line 165, in __init__
    world_state=world_state,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.22.4-py3.6.egg/mythril/laser/ethereum/svm.py", line 180, in sym_exec
    self._execute_transactions(created_account.address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.22.4-py3.6.egg/mythril/laser/ethereum/svm.py", line 224, in _execute_transactions
    execute_message_call(self, address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.22.4-py3.6.egg/mythril/laser/ethereum/transaction/symbolic.py", line 108, in execute_message_call
    laser_evm.exec()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.22.4-py3.6.egg/mythril/laser/ethereum/svm.py", line 256, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.22.4-py3.6.egg/mythril/laser/ethereum/svm.py", line 347, in execute_state
    ).evaluate(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.22.4-py3.6.egg/mythril/laser/ethereum/instructions.py", line 240, in evaluate
    result = instruction_mutator(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.22.4-py3.6.egg/mythril/laser/ethereum/instructions.py", line 187, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.22.4-py3.6.egg/mythril/laser/ethereum/instructions.py", line 122, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.22.4-py3.6.egg/mythril/laser/ethereum/instructions.py", line 905, in balance_
    address.value, self.dynamic_loader
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.22.4-py3.6.egg/mythril/laser/ethereum/state/world_state.py", line 89, in accounts_exist_or_load
    addr_bitvec = symbol_factory.BitVecVal(int(addr, 16), 256)
TypeError: int() can't convert non-string with explicit base

mythril.mythril.mythril_analyzer [INFO]: Solver statistics: 
Query count: 369 
Solver time: 37.42240118980408
The analysis was completed successfully. No issues were detected.
...
$
```

**Comment by norhh** [comment]
Thanks for submitting the error. Is it possible for you to provide a part of the contract with which this issue can be reproduced?

**Comment by damarnez** [comment]
Sure, here you can see the contracts.

https://gitlab.com/damarnez/openshop-contracts

If you want to launch the mythril analysis only needs to run
 ``` npm run local:verify ```, 
this command lauch the script located at  ``` /scripts/myth.sh ``` .

And the problematic contract is this : https://gitlab.com/damarnez/openshop-contracts/-/blob/master/contracts/marketplace/Position.sol

**Comment by norhh** [comment]
#1394 fixes this
