### ISSUE TITLE
Error in file analysis

### ISSUE THREAD

**Issue by mstad** [ConsenSys/mythril#1401]
## Description

Error in file analysis

## How to Reproduce

```console
$ myth analyze  /home/mirkostad/Programmi/smart-contracts/Mutations/Original/0x3.sol  >> ./Results/Original/0x3.sol.txt
==== Exception state ====
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/home/mirkostad/.local/lib/python3.6/site-packages/mythril/mythril/mythril_analyzer.py", line 159, in fire_lasers
    custom_modules_directory=self.custom_modules_directory,
  File "/home/mirkostad/.local/lib/python3.6/site-packages/mythril/analysis/symbolic.py", line 160, in __init__
    world_state=world_state,
  File "/home/mirkostad/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 168, in sym_exec
    self._execute_transactions(created_account.address)
  File "/home/mirkostad/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 212, in _execute_transactions
    execute_message_call(self, address)
  File "/home/mirkostad/.local/lib/python3.6/site-packages/mythril/laser/ethereum/transaction/symbolic.py", line 108, in execute_message_call
    laser_evm.exec()
  File "/home/mirkostad/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 244, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/home/mirkostad/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 335, in execute_state
    ).evaluate(global_state)
  File "/home/mirkostad/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 244, in evaluate
    result = instruction_mutator(global_state)
  File "/home/mirkostad/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 191, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/home/mirkostad/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 126, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/home/mirkostad/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 909, in balance_
    address, self.dynamic_loader
  File "/home/mirkostad/.local/lib/python3.6/site-packages/mythril/laser/ethereum/state/world_state.py", line 125, in accounts_exist_or_load
    code=dynamic_loader.dynld(addr),
  File "/home/mirkostad/.local/lib/python3.6/site-packages/mythril/support/loader.py", line 67, in dynld
    raise ValueError("Cannot load from the storage when eth is None")
ValueError: Cannot load from the storage when eth is None

Killed
[0x3.txt](https://github.com/ConsenSys/mythril/files/4844621/0x3.txt)


or perhaps:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error


If there is a Solidity source code, a truffle project, or bytecode
that is involved, please provide that or links to it.

-->

## Expected behavior

<!-- A clear and concise description of what you expected to happen. -->

## Screenshots

<!-- This section is optional.

If applicable, add screenshots to help explain your problem.

-->

## Environment

<!-- This section sometimes is optional but helpful to us.

Please modify for your setup

- Mythril version: output from  `myth --version` or `pip show mythril`
- Solidity compiler and version: `solc --version`
- Python version: `python -V`
- OS and Version: [e.g. Mac OS High Sierra]

-->

## Additional Environment or Context

<!-- This section is optional.

Add any other context about the problem here or special environment setup.

Thanks for helping!

-->

**Comment by norhh** [comment]
Can you try using `--rpc infura-mainnet` option too. For that you also have to specify `infura-id` through commandline. Because without the infura-id arg being set any call to blockchain might fail.
