### ISSUE TITLE
Build problem with 0.16.23

### ISSUE THREAD

**Issue by paulkeogh** [ConsenSys/mythril#144]
The output of docker build mythril gives;

...
Installed /usr/local/lib/python3.6/dist-packages/mythril-0.16.23-py3.6.egg
Processing dependencies for mythril==0.16.23
error: rlp 1.0.0 is installed but rlp<1.0.0,>=0.6.0 is required by {'eth-tester'}
...

Running myth -xo json -c 6060604........ gives;

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/myth", line 15, in <module>
    from ethereum import utils
  File "/home/ubuntu/.local/lib/python3.5/site-packages/ethereum/__init__.py", line 11, in <module>
    from . import slogging  # noqa
  File "/home/ubuntu/.local/lib/python3.5/site-packages/ethereum/slogging.py", line 6, in <module>
    from ethereum.utils import bcolors, is_numeric
  File "/home/ubuntu/.local/lib/python3.5/site-packages/ethereum/utils.py", line 13, in <module>
    from rlp.utils import decode_hex, encode_hex, ascii_chr, str_to_bytes
ImportError: cannot import name 'decode_hex'

How can I work around this ?

**Comment by lazzarello** [comment]
I'm hacking on this rn. might have a PR ready today...

**Comment by b-mueller** [comment]
Fixed with #147.
