### ISSUE TITLE
Does not work with ABIEncoderV2 on 0.7.4? 

### ISSUE THREAD

**Issue by minton1** [ConsenSys/mythril#1442]
## How to Reproduce

Analyze a file that uses compiler version 0.7.4 and declares *and makes use of* 
```
pragma experimental ABIEncoderV2;
```
Input: 
```myth analyze Accounting.sol --max-depth 20  -o markdown > ../myth/accounting20.md```

Output: 
```mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 851, in parse_args_and_execute
    address = load_code(disassembler, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 642, in load_code
    args.solidity_files
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mythril/mythril/mythril_disassembler.py", line 178, in load_from_solidity
    solc_settings_json=self.solc_settings_json,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mythril/support/signatures.py", line 245, in import_solidity_file
    solc_json = get_solc_json(file_path, solc_binary, solc_settings_json)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mythril/ethereum/util.py", line 79, in get_solc_json
    result = json.loads(out)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## Expected behavior

The analysis runs

## Actual behavior

The analysis does not complete

## Environment

pip show mythril
Name: mythril
Version: 0.22.13
Summary: Security analysis tool for Ethereum smart contracts
Home-page: https://github.com/ConsenSys/mythril
Author: ConsenSys Dilligence
Author-email: UNKNOWN
License: MIT
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: eth-account, persistent, py-solc, mock, ethereum, configparser, transaction, eth-keyfile, z3-solver, certifi, eth-hash, plyvel, rlp, py-solc-x, eth-typing, semantic-version, eth-keys, matplotlib, py-flags, eth-rlp, py-ecc, coloredlogs, eth-abi, jinja2, coverage, pythx, py-evm, ethereum-input-decoder, eth-tester, requests
Required-by:

solc 0.7.4
Python 2.7.16
Mac os 10.15.7

**Comment by norhh** [comment]
Hi @minton1 does it work with mythril v0.22.14?

**Comment by minton1** [comment]
It doesn't seem to, no: 

`myth analyze Accounting.sol --max-depth 20 -o markdown > ../myth/accouting20_2.md`
```mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 851, in parse_args_and_execute
    address = load_code(disassembler, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 642, in load_code
    args.solidity_files
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mythril/mythril/mythril_disassembler.py", line 178, in load_from_solidity
    solc_settings_json=self.solc_settings_json,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mythril/support/signatures.py", line 245, in import_solidity_file
    solc_json = get_solc_json(file_path, solc_binary, solc_settings_json)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mythril/ethereum/util.py", line 79, in get_solc_json
    result = json.loads(out)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

`>>> myth version`
`Mythril version v0.22.14`

**Comment by minton1** [comment]
Although now I seem to be getting the same error in files that don't use ABIEncoderV2 (tbh even the files that it does work with, it seems to be flaky and inconsistent). 

Is there something wrong with my installation of cli.py, or something else that might be going on?

**Comment by norhh** [comment]
@minton1 does it happen with all the examples? Can I get a sample program where it throws that error?

**Comment by norhh** [comment]
It should be working with the v0.22.15
