### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by jpgong** [ConsenSys/mythril#1448]
## Description

When using mythril_analyzer to analyze smart contracts, an error TypeError:'<' not supported between instances of'int' and'NoneType' occurs

For example（error questions）:

CRITICAL:mythril.mythril.mythril_analyzer:Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/home/jpgong/mythril/contract＿detection/venv/lib/python3.6/site-packages/mythril/mythril/mythril_analyzer.py", line 160, in fire_lasers
    custom_modules_directory=self.custom_modules_directory,
  File "/home/jpgong/mythril/contract＿detection/venv/lib/python3.6/site-packages/mythril/analysis/symbolic.py", line 215, in __init__
    self.laser.sym_exec(world_state=world_state, target_address=address.value)
  File "/home/jpgong/mythril/contract＿detection/venv/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 155, in sym_exec
    self._execute_transactions(symbol_factory.BitVecVal(target_address, 256))
  File "/home/jpgong/mythril/contract＿detection/venv/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 202, in _execute_transactions
    state for state in self.open_states if state.constraints.is_possible
  File "/home/jpgong/mythril/contract＿detection/venv/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 202, in <listcomp>
    state for state in self.open_states if state.constraints.is_possible
  File "/home/jpgong/mythril/contract＿detection/venv/lib/python3.6/site-packages/mythril/laser/ethereum/state/constraints.py", line 32, in is_possible
    get_model(tuple(self[:]))
  File "/home/jpgong/mythril/contract＿detection/venv/lib/python3.6/site-packages/mythril/support/model.py", line 28, in get_model
    timeout = min(timeout, time_handler.time_remaining() - 500)
TypeError: '<' not supported between instances of 'int' and 'NoneType'

**Comment by norhh** [comment]
@jpgong, You should set the `execution_timeout` when using MythrilAnalyze independently.

**Comment by jpgong** [comment]
> @jpgong, You should set the `execution_timeout` when using MythrilAnalyze independently.

I have set execution_timeout=600 before, but the error still appears. Is it because the time setting is too big?

analyzer = MythrilAnalyzer(
            disassembler=disassembler,
            use_onchain_data=self.onchain_storage,
            strategy="bfs",
            address=contract_address,
            max_depth=64,
            execution_timeout=self.timeout,   # 600
            loop_bound=self.loop_bound,  # 3
            create_timeout=10,
        )

**Comment by norhh** [comment]
did you set `solver_timeout`?
