### ISSUE TITLE
Cirtical Error using mythril Docker

### ISSUE THREAD

**Issue by KurtMerbeth** [ConsenSys/mythril#1449]
## Description

After pulling latest mythril Docker from docker hub, i tried to analyze a smart contract.
myth analyze throws Critical Error and aborts. 

## How to Reproduce

```
sudo docker run -v /home/zotac/BA:/tmp mythril/myth analyze /tmp/Contract.sol
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/mythril/mythril_analyzer.py", line 149, in fire_lasers
    sym = SymExecWrapper(
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/analysis/symbolic.py", line 163, in __init__
    self.laser.sym_exec(
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/ethereum/svm.py", line 175, in sym_exec
    self._execute_transactions(created_account.address)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/ethereum/svm.py", line 216, in _execute_transactions
    execute_message_call(self, address)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/ethereum/transaction/symbolic.py", line 108, in execute_message_call
    laser_evm.exec()
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/ethereum/svm.py", line 253, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/ethereum/svm.py", line 335, in execute_state
    self._execute_pre_hook(op_code, global_state)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/ethereum/svm.py", line 654, in _execute_pre_hook
    hook(global_state)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/analysis/module/base.py", line 69, in execute
    result = self._execute(target)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/analysis/module/modules/state_change_external_calls.py", line 116, in _execute
    issues = self._analyze_state(state)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/analysis/module/modules/state_change_external_calls.py", line 180, in _analyze_state
    issue = annotation.get_issue(global_state, self)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/analysis/module/modules/state_change_external_calls.py", line 61, in get_issue
    solver.get_transaction_sequence(
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/analysis/solver.py", line 65, in get_transaction_sequence
    model = get_model(tx_constraints, minimize=minimize)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/support/model.py", line 57, in get_model
    result = s.check()
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/smt/solver/solver_statistics.py", line 19, in function_wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/smt/solver/solver.py", line 55, in check
    evaluate = self.raw.check(args)
  File "/usr/local/lib/python3.8/dist-packages/z3/z3.py", line 7534, in check
    return CheckSatResult(Z3_optimize_check(self.ctx.ref(), self.optimize, num, _assumptions))
  File "/usr/local/lib/python3.8/dist-packages/z3/z3core.py", line 4468, in Z3_optimize_check
    _elems.Check(a0)
  File "/usr/local/lib/python3.8/dist-packages/z3/z3core.py", line 1420, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: b'push canceled'
```

## Expected behavior

analysis of the given smart contract

## Environment

Docker Image: mythril/myth:latest
created (local)  2020-11-14 09:48:07

**Comment by norhh** [comment]
It's an issue with unit propogation timeout in current version of z3 library which mythril uses. It may be fixed in a new version or z3py .

**Comment by SunBeomSo** [comment]
I encountered the same issue, which are not always reproducible. When this issue occurs, final results (with ``-o json`` option) are not properly generated, i.e., threre are not records such as ``"success": false``.

**Comment by KurtMerbeth** [comment]
This problem appeared only once.
Another run worked without problems.

**But this error appears permanently with the -t option.**

```docker run -v /home/zotac/BA:/tmp mythril/myth analyze -t 4 /tmp/BadBet.sol
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/mythril/mythril_analyzer.py", line 149, in fire_lasers
    sym = SymExecWrapper(
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/analysis/symbolic.py", line 163, in __init__
    self.laser.sym_exec(
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/ethereum/svm.py", line 175, in sym_exec
    self._execute_transactions(created_account.address)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/ethereum/svm.py", line 216, in _execute_transactions
    execute_message_call(self, address)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/ethereum/transaction/symbolic.py", line 108, in execute_message_call
    laser_evm.exec()
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/ethereum/svm.py", line 258, in exec
    new_states = [
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/ethereum/svm.py", line 261, in <listcomp>
    if state.world_state.constraints.is_possible
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/ethereum/state/constraints.py", line 32, in is_possible
    get_model(tuple(self[:]))
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/support/model.py", line 57, in get_model
    result = s.check()
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/smt/solver/solver_statistics.py", line 19, in function_wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.14-py3.8.egg/mythril/laser/smt/solver/solver.py", line 55, in check
    evaluate = self.raw.check(args)
  File "/usr/local/lib/python3.8/dist-packages/z3/z3.py", line 7534, in check
    return CheckSatResult(Z3_optimize_check(self.ctx.ref(), self.optimize, num, _assumptions))
  File "/usr/local/lib/python3.8/dist-packages/z3/z3core.py", line 4468, in Z3_optimize_check
    _elems.Check(a0)
  File "/usr/local/lib/python3.8/dist-packages/z3/z3core.py", line 1420, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: b'push canceled'```

**Comment by norhh** [comment]
@KurtMerbeth , can you provide the BadBet contact in that case, as that might be helpful.

**Comment by KurtMerbeth** [comment]
> @KurtMerbeth , can you provide the BadBet contact in that case, as that might be helpful.

[BadBet.sol](https://kurtme.io/files/BadBet.sol)

**Comment by norhh** [comment]
This should be fixed in the develop branch.
