### ISSUE TITLE
Error  myth analyze file.sol

### ISSUE THREAD

**Issue by Hamza-101** [ConsenSys/mythril#1458]
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril/interfaces/cli.py", line 843, in parse_args_and_execute
    address = load_code(disassembler, args)
  File "/usr/local/lib/python3.6/dist-packages/mythril/interfaces/cli.py", line 634, in load_code
    args.solidity_files
  File "/usr/local/lib/python3.6/dist-packages/mythril/mythril/mythril_disassembler.py", line 178, in load_from_solidity
    solc_settings_json=self.solc_settings_json,
  File "/usr/local/lib/python3.6/dist-packages/mythril/support/signatures.py", line 245, in import_solidity_file
    solc_json = get_solc_json(file_path, solc_binary, solc_settings_json)
  File "/usr/local/lib/python3.6/dist-packages/mythril/ethereum/util.py", line 79, in get_solc_json
    result = json.loads(out)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by norhh** [comment]
@Hamza-101 , can you share what mythril version you are using. As this was a problem in older mythril versions

**Comment by Hamza-101** [comment]
The one from the repo

**Comment by norhh** [comment]
@Hamza-101 , does this happen when you use the mythril/myth docker container?

**Comment by Hamza-101** [comment]
@norhh no when i take the other route.

**Comment by norhh** [comment]
In that case can you check if it happens with `mythril/myth` container. Also, is it possible for you to post the contract which will trigger this error so that I can reproduce it to try understanding the issue?

**Comment by Hamza-101** [comment]
Docker doesnt work and sorry but the contract is private.

**Comment by Haripandey21** [comment]
getting the same issue : 
```
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/home/hari/.local/lib/python3.10/site-packages/mythril/interfaces/cli.py", line 943, in parse_args_and_execute
    address = load_code(disassembler, args)
  File "/home/hari/.local/lib/python3.10/site-packages/mythril/interfaces/cli.py", line 698, in load_code
    address, _ = disassembler.load_from_solidity(
  File "/home/hari/.local/lib/python3.10/site-packages/mythril/mythril/mythril_disassembler.py", line 172, in load_from_solidity
    solc_binary = self.solc_binary or util.extract_binary(file)
  File "/home/hari/.local/lib/python3.10/site-packages/mythril/ethereum/util.py", line 222, in extract_binary
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'LotteryResolved.sol' 
```
@Hamza-101  how you solved that issue bro ?
