### ISSUE TITLE
Does not Work in Macos BigSur

### ISSUE THREAD

**Issue by amanszpapaya** [ConsenSys/mythril#1467]
I have successfully installed mythril v0.22.17 on macOS Bigsur. But when I try to run a simple command like myth -h it gives me the following error:

~ % myth -h
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/myth", line 33, in <module>
    sys.exit(load_entry_point('mythril==0.22.17', 'console_scripts', 'myth')())
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/myth", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mythril/interfaces/cli.py", line 27, in <module>
    from mythril.mythril import (
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mythril/mythril/__init__.py", line 3, in <module>
    from .mythril_config import MythrilConfig
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mythril/mythril/mythril_config.py", line 14, in <module>
    from mythril.ethereum.interface.leveldb.client import EthLevelDB
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mythril/ethereum/interface/leveldb/client.py", line 13, in <module>
    from mythril.ethereum.interface.leveldb.eth_db import ETH_DB
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mythril/ethereum/interface/leveldb/eth_db.py", line 3, in <module>
    import plyvel
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/plyvel/__init__.py", line 6, in <module>
    from ._plyvel import (  # noqa
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/plyvel/_plyvel.cpython-38-darwin.so, 2): Symbol not found: __ZTIN7leveldb10ComparatorE
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/plyvel/_plyvel.cpython-38-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/plyvel/_plyvel.cpython-38-darwin.so

My Environment:
- Mythril version: v0.22.17
- Solidity compiler and version:  0.8.2+commit.661d1103.Darwin.appleclang
- Python version: Python 3.8.8
- OS and Version: Mac OS BigSur

Thanks for helping!

**Comment by norhh** [comment]
Currently mythril doesn't support python 3.8+, can you use python 3.6?

**Comment by amanszpapaya** [comment]
Hi, I've tried it with Python 3.6.6 but it returned the same error
 ~ % myth -h
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/myth", line 11, in <module>
    load_entry_point('mythril==0.22.17', 'console_scripts', 'myth')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 27, in <module>
    from mythril.mythril import (
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mythril/mythril/__init__.py", line 3, in <module>
    from .mythril_config import MythrilConfig
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mythril/mythril/mythril_config.py", line 14, in <module>
    from mythril.ethereum.interface.leveldb.client import EthLevelDB
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mythril/ethereum/interface/leveldb/client.py", line 13, in <module>
    from mythril.ethereum.interface.leveldb.eth_db import ETH_DB
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mythril/ethereum/interface/leveldb/eth_db.py", line 3, in <module>
    import plyvel
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plyvel/__init__.py", line 6, in <module>
    from ._plyvel import (  # noqa
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plyvel/_plyvel.cpython-36m-darwin.so, 2): Symbol not found: __ZTIN7leveldb10ComparatorE
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plyvel/_plyvel.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plyvel/_plyvel.cpython-36m-darwin.so

**Comment by norhh** [comment]
Did you recently upgrade to a different OS?. Usually, upgrades mess up some linking and libraries. You can try reinstalling plyvel, leveldb and retry it, or a better way is to directly use mythril docker container.

**Comment by amanszpapaya** [comment]
I'll start using the container, thanks for the help
