### ISSUE TITLE
(os x) myth from pip3 version conflict

### ISSUE THREAD

**Issue by Elyx0** [ConsenSys/mythril#1482]
I followed the doc:
```bash
brew update
brew upgrade
brew tap ethereum/ethereum
brew install leveldb
brew install solidity
pip3 install mythril
```
So I end up with the following dependencies:
```
pip3 list
Package                Version
---------------------- ---------
asn1crypto             1.4.0
attrdict               2.0.1
attrs                  21.2.0
beautifulsoup4         4.7.1
blake2b-py             0.1.4
cached-property        1.5.2
certifi                2021.5.30
cffi                   1.14.5
chardet                3.0.4
coincurve              15.0.0
coloredlogs            15.0
configparser           5.0.2
coverage               5.5
cycler                 0.10.0
cytoolz                0.11.0
dictionaries           0.0.2
eth-abi                1.3.0
eth-account            0.3.0
eth-bloom              1.0.4
eth-hash               0.2.0
eth-keyfile            0.5.1
eth-keys               0.2.4
eth-rlp                0.2.1
eth-tester             0.1.0b32
eth-typing             2.2.2
eth-utils              1.9.0
ethereum               2.3.2
ethereum-input-decoder 0.2.2
future                 0.18.2
hexbytes               0.2.1
humanfriendly          9.1
idna                   2.8
inflection             0.5.1
Jinja2                 3.0.1
jsonschema             3.2.0
kiwisolver             1.3.1
lru-dict               1.1.7
MarkupSafe             2.0.1
matplotlib             3.4.2
mock                   4.0.3
mypy-extensions        0.4.3
mythril                0.22.19
mythx-models           2.0.1
numpy                  1.19.0
parsimonious           0.8.1
pbkdf2                 1.3
persistent             4.7.0
Pillow                 8.2.0
pip                    21.1.2
plyvel                 1.3.0
py-ecc                 1.6.0
py-evm                 0.3.0a13
py-flags               1.1.4
py-solc                3.2.0
py-solc-x              1.0.0
pyaes                  1.6.1
pyasn1                 0.4.8
pycparser              2.20
pycryptodome           3.10.1
pydantic               1.7.3
pyethash               0.1.27
PyJWT                  1.7.1
pyparsing              2.4.7
pyrsistent             0.17.3
pysha3                 1.0.2
python-dateutil        2.8.1
pythx                  1.7.1
PyYAML                 5.4.1
repoze.lru             0.7
requests               2.25.0
rlp                    1.2.0
rsa                    4.7.2
scrypt                 0.8.18
semantic-version       2.8.5
setuptools             41.2.0
six                    1.16.0
soupsieve              1.9.1
Telethon               1.21.1
toolz                  0.11.1
transaction            3.0.1
trie                   1.4.0
urllib3                1.25.3
z3-solver              4.8.10.0
zope.interface         5.4.0
```

Then running `myth test.sol` instantly crashes.

```py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-hash 0.2.0 (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages), Requirement.parse('eth-hash[pycryptodome]<0.4.0,>=0.3.1'), {'eth-bloom'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/myth", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-hash 0.2.0 (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages), Requirement.parse('eth-hash[pycryptodome]<0.4.0,>=0.3.1'), {'eth-bloom'})
```

```py
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
eth-bloom 1.0.4 requires eth-hash[pycryptodome]<0.4.0,>=0.3.1, but you have eth-hash 0.2.0 which is incompatible.
```

i tried to remove eth-hash 0.2.0  but I get
```
pkg_resources.DistributionNotFound: The 'eth-hash<0.3.0' distribution was not found and is required by mythril
```

Any ideas? osx 18.7.0

**Comment by norhh** [comment]
Hi, I fixed the potential issue, can you retry by downloading the latest mythril version?
