### ISSUE TITLE
I am analyzing my sol file and I have reported the following errors. How can I deal with him?

### ISSUE THREAD

**Issue by Lsw-98** [ConsenSys/mythril#1487]
(py36) lsw@lsw-virtual-machine:~/桌面$ myth a re.sol
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 843, in parse_args_and_execute
    address = load_code(disassembler, args)
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 634, in load_code
    args.solidity_files
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/site-packages/mythril/mythril/mythril_disassembler.py", line 183, in load_from_solidity
    solc_settings_json=self.solc_settings_json,
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/site-packages/mythril/support/signatures.py", line 245, in import_solidity_file
    solc_json = get_solc_json(file_path, solc_binary, solc_settings_json)
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/site-packages/mythril/ethereum/util.py", line 79, in get_solc_json
    result = json.loads(out)
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/lsw/anaconda3/envs/py36/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by norhh** [comment]
Hi @Lsw-98 , what's the mythril version that's being used?

**Comment by Lsw-98** [comment]
Hi @norhh, I use mythril    0.22.21

**Comment by norhh** [comment]
Hi @Lsw-98 , I can't seem to reproduce the bug. Do you have solidity installed? can you try 
`myth a file.sol --solv <solidity_version_of_file>`

**Comment by norhh** [comment]
Also, can you try the develop branch and paste the error you get there? As that might be helpful to find the issue.

**Comment by norhh** [comment]
This should be fixed now
