### ISSUE TITLE
Using Ubuntu 18.04 to install mythril to report an error

### ISSUE THREAD

**Issue by Lsw-98** [ConsenSys/mythril#1495]
This is my wrong message：
Collecting mythril
Requirement already satisfied: eth-keys<0.3.0,>=0.2.0b3 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: coloredlogs>=10.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Collecting py-solc-x==1.0.0 (from mythril)
  Using cached https://files.pythonhosted.org/packages/22/3a/74dbec043820910027c2eeba68f84413b31c563627732bf073360e42ba3c/py_solc_x-1.0.0-py3-none-any.whl
Requirement already satisfied: eth-utils==1.9.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: semantic-version==2.8.5 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: eth-hash>=0.3.1 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: rlp<2.0.0,>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: eth-keyfile>=0.5.1 in /usr/local/lib/python3.6/dist-packages (from mythril)
Collecting matplotlib (from mythril)
  Using cached https://files.pythonhosted.org/packages/09/03/b7b30fa81cb687d1178e085d0f01111ceaea3bf81f9330c937fb6f6c8ca0/matplotlib-3.3.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting py-flags (from mythril)
  Using cached https://files.pythonhosted.org/packages/6e/c1/6a4d763d2f9fb474e3ec99b6e4b8ffa886be398995cfd891c9e6123ec6db/py_flags-1.1.4-py3-none-any.whl
Requirement already satisfied: eth-rlp>=0.1.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Collecting py-solc (from mythril)
  Using cached https://files.pythonhosted.org/packages/47/74/d36abca3f36ccdcd04976c50f83502c870623e5beb4a4ec96c7bad4bb9e8/py_solc-3.2.0-py3-none-any.whl
Requirement already satisfied: certifi>=2020.06.20 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: eth-tester==0.1.0b32 in /usr/local/lib/python3.6/dist-packages (from mythril)
Collecting pythx (from mythril)
  Using cached https://files.pythonhosted.org/packages/1b/dd/31050af71b0d795f12ad0913aa1514803c04340a2904f3a789252dea86e5/pythx-1.7.1-py2.py3-none-any.whl
Collecting transaction>=2.2.1 (from mythril)
  Using cached https://files.pythonhosted.org/packages/9b/35/b5cca132f9b364066bea00cbf4ea466b7a15461a609ab9ba8e832e165452/transaction-3.0.1-py2.py3-none-any.whl
Requirement already satisfied: eth-account<=0.3.0,>=0.1.0a2 in /usr/local/lib/python3.6/dist-packages (from mythril)
Collecting ethereum>=2.3.2 (from mythril)
Requirement already satisfied: configparser>=3.5.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Collecting plyvel (from mythril)
  Using cached https://files.pythonhosted.org/packages/bd/4d/14ed73d3bc0ac1d5f3c1b79ba2fe509d8222053cfc94014804129d52642e/plyvel-1.3.0.tar.gz
Collecting py-ecc==1.6.0 (from mythril)
  Using cached https://files.pythonhosted.org/packages/57/37/052d1f8d13da5cfc3faf249c6e825d47984fc9065c90cde676e72c762ac8/py_ecc-1.6.0-py3-none-any.whl
Collecting numpy==1.19.0 (from mythril)
  Using cached https://files.pythonhosted.org/packages/00/16/476826a84d545424084499763248abbbdc73d065168efed9aa71cdf2a7dc/numpy-1.19.0-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: coverage in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: ethereum-input-decoder>=0.2.2 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: eth-typing>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: eth-abi==1.3.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Collecting persistent>=4.2.0 (from mythril)
  Using cached https://files.pythonhosted.org/packages/99/57/72671bf3071852d1b7641a894b97453f93fb7e0bf4921a84826e8af48a8e/persistent-4.7.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting mock (from mythril)
  Using cached https://files.pythonhosted.org/packages/5c/03/b7e605db4a57c0f6fba744b11ef3ddf4ddebcada35022927a2b5fc623fdf/mock-4.0.3-py3-none-any.whl
Collecting z3-solver>=4.8.8.0 (from mythril)
  Using cached https://files.pythonhosted.org/packages/04/35/f355c26853fe246ae58e6521296445cea0ef128ccbe4c6f39969d4bb6a18/z3_solver-4.8.11.0-py2.py3-none-manylinux1_x86_64.whl
Collecting py-evm==0.3.0a13 (from mythril)
  Using cached https://files.pythonhosted.org/packages/a1/91/465d3d79081f444d8424b3ebfc104b59b52183992271191f93a141d5e43f/py_evm-0.3.0a13-py3-none-any.whl
Requirement already satisfied: requests==2.25.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Collecting jinja2>=2.9 (from mythril)
  Using cached https://files.pythonhosted.org/packages/80/21/ae597efc7ed8caaa43fb35062288baaf99a7d43ff0cf66452ddf47604ee6/Jinja2-3.0.1-py3-none-any.whl
Requirement already satisfied: humanfriendly>=9.1 in /usr/local/lib/python3.6/dist-packages (from coloredlogs>=10.0->mythril)
Requirement already satisfied: cytoolz<1.0.0,>=0.10.1; implementation_name == "cpython" in /usr/local/lib/python3.6/dist-packages (from eth-utils==1.9.0->mythril)
Requirement already satisfied: pycryptodome<4.0.0,>=3.4.7 in /usr/local/lib/python3.6/dist-packages (from eth-keyfile>=0.5.1->mythril)
Collecting kiwisolver>=1.0.1 (from matplotlib->mythril)
  Using cached https://files.pythonhosted.org/packages/a7/1b/cbd8ae738719b5f41592a12057ef5442e2ed5f5cb5451f8fc7e9f8875a1a/kiwisolver-1.3.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting cycler>=0.10 (from matplotlib->mythril)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting pillow>=6.2.0 (from matplotlib->mythril)
  Using cached https://files.pythonhosted.org/packages/df/74/4a981d12fa26b83c9230b67dee44d1361a372e0f22785f093969fd98b964/Pillow-8.3.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
Requirement already satisfied: python-dateutil>=2.1 in /usr/lib/python3/dist-packages (from matplotlib->mythril)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 (from matplotlib->mythril)
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
Collecting dictionaries==0.0.2 (from py-flags->mythril)
  Using cached https://files.pythonhosted.org/packages/0c/66/99daf061d3940bcdcb25101be442c370896df7ab25eeea3653b9751e6848/dictionaries-0.0.2-py2.py3-none-any.whl
Requirement already satisfied: hexbytes<1,>=0.1.0 in /usr/local/lib/python3.6/dist-packages (from eth-rlp>=0.1.0->mythril)
Collecting PyJWT==1.7.1 (from pythx->mythril)
  Using cached https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
Collecting inflection==0.5.1 (from pythx->mythril)
  Using cached https://files.pythonhosted.org/packages/59/91/aa6bde563e0085a02a435aa99b49ef75b0a4b062635e606dab23ce18d720/inflection-0.5.1-py2.py3-none-any.whl
Collecting mythx-models==2.0.1 (from pythx->mythril)
  Using cached https://files.pythonhosted.org/packages/f6/f0/159fd3e146eaccc9fa510bcc3dabb989940c237e8466df89a47cb85dce31/mythx_models-2.0.1-py2.py3-none-any.whl
Requirement already satisfied: zope.interface in /usr/lib/python3/dist-packages (from transaction>=2.2.1->mythril)
Requirement already satisfied: attrdict<3,>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from eth-account<=0.3.0,>=0.1.0a2->mythril)
Collecting future (from ethereum>=2.3.2->mythril)
Collecting scrypt (from ethereum>=2.3.2->mythril)
  Using cached https://files.pythonhosted.org/packages/0a/b4/a4a59f47e14873557aa69301ffc05e01c125726e00da1dc307dc3ccccc10/scrypt-0.8.18-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyethash<1.0.0,>=0.1.27 (from ethereum>=2.3.2->mythril)
Collecting coincurve>=7.0.0 (from ethereum>=2.3.2->mythril)
  Using cached https://files.pythonhosted.org/packages/65/31/9f13921cc7ca27059af4def1a9d1277a6a252dea967b62f9ea05cc2a4115/coincurve-15.0.0.tar.gz
Collecting pysha3>=1.0.1 (from ethereum>=2.3.2->mythril)
  Using cached https://files.pythonhosted.org/packages/32/2a/b93e0c6d90c7c45e2fab35d7ef349e8c5bd7387a048e961b041fd9521556/pysha3-1.0.2-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from ethereum>=2.3.2->mythril)
Collecting pbkdf2 (from ethereum>=2.3.2->mythril)
Collecting repoze.lru (from ethereum>=2.3.2->mythril)
  Using cached https://files.pythonhosted.org/packages/b0/30/6cc0c95f0b59ad4b3b9163bff7cdcf793cc96fac64cf398ff26271f5cf5e/repoze.lru-0.7-py3-none-any.whl
Collecting mypy-extensions>=0.4.1 (from py-ecc==1.6.0->mythril)
  Using cached https://files.pythonhosted.org/packages/5c/eb/975c7c080f3223a5cdaff09612f3a5221e4ba534f7039db34c35d95fa6a5/mypy_extensions-0.4.3-py2.py3-none-any.whl
Requirement already satisfied: parsimonious<0.9.0,>=0.8.0 in /usr/local/lib/python3.6/dist-packages (from eth-abi==1.3.0->mythril)
Requirement already satisfied: cffi; platform_python_implementation == "CPython" in /usr/local/lib/python3.6/dist-packages (from persistent>=4.2.0->mythril)
Collecting cached-property<2,>=1.5.1 (from py-evm==0.3.0a13->mythril)
  Using cached https://files.pythonhosted.org/packages/48/19/f2090f7dad41e225c7f2326e4cfe6fff49e57dedb5b53636c9551f86b069/cached_property-1.5.2-py2.py3-none-any.whl
Collecting lru-dict>=1.1.6 (from py-evm==0.3.0a13->mythril)
Collecting eth-bloom<2.0.0,>=1.0.3 (from py-evm==0.3.0a13->mythril)
  Using cached https://files.pythonhosted.org/packages/92/70/cfd696ebb70c964975bc1a42ba7b811c9a9523d680ada2ba9e04b0a5f8d0/eth_bloom-1.0.4-py3-none-any.whl
Collecting trie<2.0.0,>=1.4.0 (from py-evm==0.3.0a13->mythril)
  Using cached https://files.pythonhosted.org/packages/53/b2/937df7c676aeb921a57092c3ce8ee6b9b81e45008960f81e1da6c66d17c0/trie-1.4.0-py3-none-any.whl
Collecting blake2b-py<0.2,>=0.1.2 (from py-evm==0.3.0a13->mythril)
  Using cached https://files.pythonhosted.org/packages/32/36/b34e949be9bdf763bdd5a9dc9709999c980bd0ef426602bf2d25872e75e7/blake2b_py-0.1.3-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.25.0->mythril)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.25.0->mythril)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests==2.25.0->mythril)
Collecting MarkupSafe>=2.0 (from jinja2>=2.9->mythril)
  Using cached https://files.pythonhosted.org/packages/fc/d6/57f9a97e56447a1e340f8574836d3b636e2c14de304943836bd645fa9c7e/MarkupSafe-2.0.1-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: toolz>=0.8.0 in /usr/local/lib/python3.6/dist-packages (from cytoolz<1.0.0,>=0.10.1; implementation_name == "cpython"->eth-utils==1.9.0->mythril)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from cycler>=0.10->matplotlib->mythril)
Collecting pydantic==1.7.3 (from mythx-models==2.0.1->pythx->mythril)
  Using cached https://files.pythonhosted.org/packages/35/47/7ce1c5dbcdc9dfa51cfc61db7bcccfc118c3cebe302971a5e34dda666c9d/pydantic-1.7.3-py3-none-any.whl
Collecting jsonschema==3.2.0 (from mythx-models==2.0.1->pythx->mythril)
  Using cached https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl
Requirement already satisfied: asn1crypto in /usr/lib/python3/dist-packages (from coincurve>=7.0.0->ethereum>=2.3.2->mythril)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi; platform_python_implementation == "CPython"->persistent>=4.2.0->mythril)
Collecting dataclasses>=0.6; python_version < "3.7" (from pydantic==1.7.3->mythx-models==2.0.1->pythx->mythril)
  Using cached https://files.pythonhosted.org/packages/fe/ca/75fac5856ab5cfa51bbbcefa250182e50441074fdc3f803f6e76451fab43/dataclasses-0.8-py3-none-any.whl
Collecting pyrsistent>=0.14.0 (from jsonschema==3.2.0->mythx-models==2.0.1->pythx->mythril)
  Using cached https://files.pythonhosted.org/packages/6c/19/1af501f6f388a40ede6d0185ba481bdb18ffc99deab0dd0d092b173bc0f4/pyrsistent-0.18.0-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from jsonschema==3.2.0->mythx-models==2.0.1->pythx->mythril)
Collecting importlib-metadata; python_version < "3.8" (from jsonschema==3.2.0->mythx-models==2.0.1->pythx->mythril)
  Using cached https://files.pythonhosted.org/packages/3f/e1/e5bba549a033adf77448699a34ecafc7a32adaeeb4369396b35f56d5cc3e/importlib_metadata-4.6.1-py3-none-any.whl
Collecting attrs>=17.4.0 (from jsonschema==3.2.0->mythx-models==2.0.1->pythx->mythril)
  Using cached https://files.pythonhosted.org/packages/20/a9/ba6f1cd1a1517ff022b35acd6a7e4246371dfab08b8e42b829b6d07913cc/attrs-21.2.0-py2.py3-none-any.whl
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata; python_version < "3.8"->jsonschema==3.2.0->mythx-models==2.0.1->pythx->mythril)
  Using cached https://files.pythonhosted.org/packages/2e/35/6c4fff5ab443b57116cb1aad46421fb719bed2825664e8fe77d66d99bcbc/typing_extensions-3.10.0.0-py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->jsonschema==3.2.0->mythx-models==2.0.1->pythx->mythril)
  Using cached https://files.pythonhosted.org/packages/92/d9/89f433969fb8dc5b9cbdd4b4deb587720ec1aeb59a020cf15002b9593eef/zipp-3.5.0-py3-none-any.whl
Building wheels for collected packages: plyvel, coincurve
  Running setup.py bdist_wheel for plyvel ... done
  Stored in directory: /root/.cache/pip/wheels/9c/71/df/be5c69c134635ba5b789389a3143bd1d5f7279731b3967d25f
  Running setup.py bdist_wheel for coincurve ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-b6ydh3jf/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpjlu414cppip-wheel- --python-tag cp36:
  /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/keys.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/_windows_libsecp256k1.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/context.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/types.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/ecdsa.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/utils.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/__init__.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/flags.py -> build/lib.linux-x86_64-3.6/coincurve
  copying coincurve/py.typed -> build/lib.linux-x86_64-3.6/coincurve
  running build_clib
  /tmp/pip-build-b6ydh3jf/coincurve/libsecp256k1/autogen.sh: 3: /tmp/pip-build-b6ydh3jf/coincurve/libsecp256k1/autogen.sh: autoreconf: not found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-b6ydh3jf/coincurve/setup.py", line 309, in <module>
      **setup_kwargs
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-b6ydh3jf/coincurve/setup.py", line 95, in run
      _bdist_wheel.run(self)
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-b6ydh3jf/coincurve/setup.py", line 152, in run
      subprocess.check_call([autogen], cwd=absolute('libsecp256k1'))
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/tmp/pip-build-b6ydh3jf/coincurve/libsecp256k1/autogen.sh']' returned non-zero exit status 127.
  
  ----------------------------------------
  Failed building wheel for coincurve
  Running setup.py clean for coincurve
Successfully built plyvel
Failed to build coincurve
Installing collected packages: py-solc-x, kiwisolver, cycler, pillow, pyparsing, numpy, matplotlib, dictionaries, py-flags, py-solc, PyJWT, inflection, dataclasses, pydantic, pyrsistent, typing-extensions, zipp, importlib-metadata, attrs, jsonschema, mythx-models, pythx, transaction, future, scrypt, pyethash, coincurve, pysha3, mypy-extensions, py-ecc, pbkdf2, repoze.lru, ethereum, plyvel, persistent, mock, z3-solver, cached-property, lru-dict, eth-bloom, trie, blake2b-py, py-evm, MarkupSafe, jinja2, mythril
  Found existing installation: Pillow 5.1.0
    Not uninstalling pillow at /usr/lib/python3/dist-packages, outside environment /usr
  Running setup.py install for coincurve ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-b6ydh3jf/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-2bnd94wq-record/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/keys.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/_windows_libsecp256k1.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/context.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/types.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/ecdsa.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/utils.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/__init__.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/flags.py -> build/lib.linux-x86_64-3.6/coincurve
    copying coincurve/py.typed -> build/lib.linux-x86_64-3.6/coincurve
    running build_clib
    /tmp/pip-build-b6ydh3jf/coincurve/libsecp256k1/autogen.sh: 3: /tmp/pip-build-b6ydh3jf/coincurve/libsecp256k1/autogen.sh: autoreconf: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-b6ydh3jf/coincurve/setup.py", line 309, in <module>
        **setup_kwargs
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-b6ydh3jf/coincurve/setup.py", line 152, in run
        subprocess.check_call([autogen], cwd=absolute('libsecp256k1'))
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-b6ydh3jf/coincurve/libsecp256k1/autogen.sh']' returned non-zero exit status 127.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-b6ydh3jf/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-2bnd94wq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-b6ydh3jf/coincurve/

My running environment is: Ubuntu 18.04, python 3.6，How can we solve this problem？

**Comment by Lsw-98** [comment]
I took a look at it. It might be this mistake:Running setup.py bdist_wheel for coincurve ... error

**Comment by Lsw-98** [comment]
resolvent: pip install coincurve
