### ISSUE TITLE
JSONDecodeError when using --solc-json

### ISSUE THREAD

**Issue by littlezigy** [ConsenSys/mythril#1502]
## Description
I get this error message when I run mythril with --solc-json. I have a solc.json to handle my file imports. If I run without the `--solc-json` argument, it works fine. I've been able to run the analyzer on .sol files with no imports.

```
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.23-py3.8.egg/mythril/interfaces/cli.py", line 844, in parse_args_and_execute
    address = load_code(disassembler, args)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.23-py3.8.egg/mythril/interfaces/cli.py", line 633, in load_code
    address, _ = disassembler.load_from_solidity(
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.23-py3.8.egg/mythril/mythril/mythril_disassembler.py", line 180, in load_from_solidity
    self.sigs.import_solidity_file(
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.23-py3.8.egg/mythril/support/signatures.py", line 245, in import_solidity_file
    solc_json = get_solc_json(file_path, solc_binary, solc_settings_json)
  File "/usr/local/lib/python3.8/dist-packages/mythril-0.22.23-py3.8.egg/mythril/ethereum/util.py", line 48, in get_solc_json
    settings = json.loads(solc_settings_json) if solc_settings_json else {}
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## How to Reproduce
```console
$ docker run -v $(pwd):/tmp mythril/myth analyze <contract-name>.sol --solc-json /tmp/solc.json`
```

## Environment

NOTE: I am using the docker image (mythril/myth)

- Mythril version: Mythril version v0.22.23
- Solidity compiler and version: 0.8.4+commit.c7e474f2.Linux.g++
- Python version: Python 2.7.17
- OS and Version: Elementary OS Juno (Base: Ubuntu 18.04.2 bionic)

**Comment by norhh** [comment]
This should be fixed now
