### ISSUE TITLE
Error simply running `myth` after installing in MacOS

### ISSUE THREAD

**Issue by julianmrodri** [ConsenSys/mythril#1509]
## Description

After installing with the required instructions and prerequisties (leveldb, etc). I get the following error when running `myth` in MacOS Big Sur version 11.4

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/myth", line 11, in <module>
    load_entry_point('mythril==0.22.25', 'console_scripts', 'myth')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mythril/interfaces/cli.py", line 26, in <module>
    from mythril.mythril import (
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mythril/mythril/__init__.py", line 3, in <module>
    from .mythril_config import MythrilConfig
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mythril/mythril/mythril_config.py", line 14, in <module>
    from mythril.ethereum.interface.leveldb.client import EthLevelDB
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mythril/ethereum/interface/leveldb/client.py", line 13, in <module>
    from mythril.ethereum.interface.leveldb.eth_db import ETH_DB
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mythril/ethereum/interface/leveldb/eth_db.py", line 3, in <module>
    import plyvel
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyvel/__init__.py", line 6, in <module>
    from ._plyvel import (  # noqa
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyvel/_plyvel.cpython-37m-darwin.so, 2): Symbol not found: __ZTIN7leveldb10ComparatorE
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyvel/_plyvel.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyvel/_plyvel.cpython-37m-darwin.so

```
## How to Reproduce

I installed in a MacOS following these steps:

```
brew update
brew upgrade
brew tap ethereum/ethereum
brew install leveldb
brew install solidity
pip3 install mythril
```

Then run a simple command:

```
$ myth
```

## Expected behavior

Run `myth` properly as myth seems to be properly installed.

## Screenshot

![image](https://user-images.githubusercontent.com/56316686/132585548-b446b6f2-dd4c-4b93-986d-bc2a7022171f.png)

## Environment

- Mythril version:  Results in same error
- Solidity compiler and version: Version: 0.8.7+commit.e28d00a7.Darwin.appleclang
- Python version:  `python -V` returns `Python 2.7.161.   `python3 -V returns `Python 3.7.7`
- OS and Version: MacOS Big Sur

**Comment by norhh** [comment]
It should be an issue with plyvel. Try running `import plyvel` in python interpreter. If the problem persists then plyvel is likely not properly installed/linked to leveldb. Meanwhile you can directly use mythril docker container. For more info look up here https://mythril-classic.readthedocs.io/en/master/installation.html#docker

**Comment by julianmrodri** [comment]
I get this:

```
Python 3.7.7 (v3.7.7:d7c567b08f, Mar 10 2020, 02:56:16) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import plyvel 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyvel/__init__.py", line 6, in <module>
    from ._plyvel import (  # noqa
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyvel/_plyvel.cpython-37m-darwin.so, 2): Symbol not found: __ZTIN7leveldb10ComparatorE
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyvel/_plyvel.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyvel/_plyvel.cpython-37m-darwin.so
>>> 
```

**Comment by norhh** [comment]
It is likely the leveldb packages aren't linked to plyvel, but I am not sure, it's better if you post this issue in https://github.com/wbolster/plyvel . Meanwhile, try using the docker container, it should be easy to run in it.

**Comment by nonduino** [comment]
M1?
