### ISSUE TITLE
$ myth analyze <solidity-file> Not working

### ISSUE THREAD

**Issue by patelvishal1401** [ConsenSys/mythril#1523]
After installing mythril 

when i use command myth, its not working

Traceback (most recent call last):
  File "/usr/local/bin/myth", line 5, in <module>
    from mythril.interfaces.cli import main
  File "/usr/local/lib/python3.9/site-packages/mythril/interfaces/cli.py", line 26, in <module>
    from mythril.mythril import (
  File "/usr/local/lib/python3.9/site-packages/mythril/mythril/__init__.py", line 3, in <module>
    from .mythril_config import MythrilConfig
  File "/usr/local/lib/python3.9/site-packages/mythril/mythril/mythril_config.py", line 14, in <module>
    from mythril.ethereum.interface.leveldb.client import EthLevelDB
  File "/usr/local/lib/python3.9/site-packages/mythril/ethereum/interface/leveldb/client.py", line 13, in <module>
    from mythril.ethereum.interface.leveldb.eth_db import ETH_DB
  File "/usr/local/lib/python3.9/site-packages/mythril/ethereum/interface/leveldb/eth_db.py", line 3, in <module>
    import plyvel
  File "/usr/local/lib/python3.9/site-packages/plyvel/__init__.py", line 6, in <module>
    from ._plyvel import (  # noqa
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/plyvel/_plyvel.cpython-39-darwin.so, 2): Symbol not found: __ZTIN7leveldb10ComparatorE
  Referenced from: /usr/local/lib/python3.9/site-packages/plyvel/_plyvel.cpython-39-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.9/site-packages/plyvel/_plyvel.cpython-39-darwin.so

**Comment by patelvishal1401** [comment]
@norhh Sure thanks!!
