### ISSUE TITLE
TypeError: 'BitVec' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by gsalzer** [ConsenSys/mythril#1568]
## Description

Crash when analyzing bytecode

## How to Reproduce

```console
$ cat demo.hex
6060604052361561006c5760e060020a60003504630274ea8181146100795780631bfa5d8a146100985780633741b92b1461010257806358da3ca914610152578063aa804a8014610219578063bba65ed11461022f578063d6b8ae261461025e578063d876fb2114610274575b34610002576102c4610002565b34610002576102c660043560243560443560643560843560a4356102ee565b346100025761030a6004356024356040805183815260208101839052815190819003909101902060009081908180805b6401000003d019846401000003d0198687090992506104366401000003d0196007850863400000f460fe60020a036401000003d01961017c565b346100025761032360043560243560006000600060006401000003d019866401000003d0198889090992506104916401000003d0196007850863400000f460fe60020a036401000003d01961017c565b346100025761030a60043560243560443560008080806401000003d0196104bb866401000003d319835b6000600160ff60020a825b60008211156105385760009050600082871611156101a3575060015b8481880a86858609099250600090508060028304871611156101c3575060015b8481880a86858609099250600090508060048304871611156101e3575060015b8481880a8685860909925060009050806008830487161115610203575060015b8481880a86858609099250601082049150610187565b34610002576102c660043560243560443561033c565b3461000257610323600435602435600060026008830660020a8481156100025704811561000257069392505050565b346100025761032360043560243560443561017c565b34610002576102c660043560243560443570014551231950b75fc4402da1732fc9bebe196064350660008080808080808915806102af575087155b1561055b57600096508695506001945061054d565b005b60408051938452602084019290925282820152519081900360600190f35b6105a58484848e8e8e5b600080808080808a151561037757888888955095509550610368565b6040805192835260208301919091528051918290030190f35b60408051918252519081900360200190f35b6103618c8c8c5b600080808080808715156104e757600095508594508493505b50505093509350939050565b9550955095505b50505096509650969350505050565b87151561038c578b8b8b955095509550610368565b6401000003d0198c880288020692506401000003d019898b028b020691506401000003d0198b8802880288020698506401000003d019888b028b028b02069750828214156103eb57888814610335576000955085945060019350610368565b506401000003d01982820380840281026002810282800283028c8c03808002919091039190910384900698508b83028302830291899003020382900695508a02870206925084610368565b91506002826401000003d019849003919006600103026002830683020190506401000003d0198182096401000003d01960078508141561047e57929792965091945050505050565b6401000003d019600185010693506100c8565b9150600282068518600118905080600103826401000003d019030281830201935050505092915050565b880991506401000003d0196104d7866401000003d4198361017c565b8709919791965090945050505050565b50506401000003d01986800288810260088181028b80028080026009029190910385900698509280020260036004909202889003909202020381900693506002868802020691508390508282610355565b509095945050505050565b8383839650965096505b505050509450945094915050565b50600092508291506001905060ff60020a5b60008111156105435761058184848461033c565b91955093509150878116156105ad578215156102e4578a93508992508891506105ad565b919550935091505b6002900461056d56
$ python myth -v4 analyze -f demo.hex
mythril.mythril.mythril_config [INFO]: Infura key not provided, so onchain access is disabled. Use --infura-id <INFURA_ID> or set it in the environment variable INFURA_ID or in the ~/.mythril/config.ini file
mythril.support.signatures [INFO]: Using signature database at /home/ethereum/.mythril/signatures.db
mythril.laser.ethereum.svm [INFO]: LASER EVM initialized with dynamic loader: <mythril.support.loader.DynLoader object at 0x7fc5198c1d90>
mythril.laser.ethereum.strategy.extensions.bounded_loops [INFO]: Loaded search strategy extension: Loop bounds (limit = 3)
mythril.laser.plugin.loader [INFO]: Loading laser plugin: coverage
mythril.laser.plugin.loader [INFO]: Loading laser plugin: mutation-pruner
mythril.laser.plugin.loader [INFO]: Loading laser plugin: call-depth-limit
mythril.laser.plugin.loader [INFO]: Loading laser plugin: instruction-profiler
mythril.laser.plugin.loader [INFO]: Loading laser plugin: dependency-pruner
mythril.laser.plugin.loader [INFO]: Instrumenting symbolic vm with plugin: coverage
mythril.laser.plugin.loader [INFO]: Instrumenting symbolic vm with plugin: mutation-pruner
mythril.laser.plugin.loader [INFO]: Instrumenting symbolic vm with plugin: call-depth-limit
mythril.laser.plugin.loader [INFO]: Instrumenting symbolic vm with plugin: instruction-profiler
mythril.laser.plugin.loader [INFO]: Instrumenting symbolic vm with plugin: dependency-pruner
mythril.laser.ethereum.svm [INFO]: Starting contract creation transaction
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/home/ethereum/tools/mythril/mythril/mythril/mythril_analyzer.py", line 149, in fire_lasers
    sym = SymExecWrapper(
  File "/home/ethereum/tools/mythril/mythril/analysis/symbolic.py", line 169, in __init__
    self.laser.sym_exec(
  File "/home/ethereum/tools/mythril/mythril/laser/ethereum/svm.py", line 160, in sym_exec
    created_account = execute_contract_creation(
  File "/home/ethereum/tools/mythril/mythril/laser/ethereum/transaction/symbolic.py", line 150, in execute_contract_creation
    laser_evm.exec(True)
  File "/home/ethereum/tools/mythril/mythril/laser/ethereum/svm.py", line 254, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/home/ethereum/tools/mythril/mythril/laser/ethereum/svm.py", line 343, in execute_state
    new_global_states = Instruction(
  File "/home/ethereum/tools/mythril/mythril/laser/ethereum/instructions.py", line 263, in evaluate
    result = instruction_mutator(global_state)
  File "/home/ethereum/tools/mythril/mythril/laser/ethereum/instructions.py", line 195, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/home/ethereum/tools/mythril/mythril/laser/ethereum/instructions.py", line 130, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/home/ethereum/tools/mythril/mythril/laser/ethereum/instructions.py", line 1864, in return_
    global_state.current_transaction.end(global_state, return_data)
  File "/home/ethereum/tools/mythril/mythril/laser/ethereum/transaction/transaction_models.py", line 263, in end
    global_state.environment.active_account.code.assign_bytecode(tuple(return_data))
  File "/home/ethereum/tools/mythril/mythril/disassembler/disassembly.py", line 39, in assign_bytecode
    self.instruction_list = asm.disassemble(bytecode)
  File "/home/ethereum/tools/mythril/mythril/disassembler/asm.py", line 109, in disassemble
    part_code = bytes(bytecode[-43:])
TypeError: 'BitVec' object cannot be interpreted as an integer

mythril.mythril.mythril_analyzer [INFO]: Solver statistics: 
Query count: 60 
Solver time: 2.268463373184204
The analysis was completed successfully. No issues were detected.
```
## Environment

- Mythril version: v0.22.32
- Python version: 3.8.10
- OS and Version: Ubuntu 20.04.3 LTS

**Comment by norhh** [comment]
@gsalzer , For some reason I can't reproduce this issue. can you run `python myth -v4 analyze -f 0xb4e348c10b8f1dcf2b5bc524f1f2ab912fde4048.hex `. And how long did it take for the execution to finish with an error?

**Comment by gsalzer** [comment]
@norhh Sorry, my bad. The code on Etherscan is the deployment code, the error occurs when analyzing the deployed code. I have updated my original report.

**Comment by norhh** [comment]
Oh! Mythril first triggers contract creation transaction, which is not possible with deployment bytecode. try using `--bin-runtime` flag.

**Comment by gsalzer** [comment]
@norhh You are right, this changes the behavior of Mythril, no crash so far (analysis still running). Thanks for pointing this out.

But the crash in my original setting shouldn't happen anyway, should it? If the runtime code is taken as deployment code, then whatever is returned by the RETURN statement, should be deployed and run. This may garbage, but it still shouldn't lead to a crash ...

Anyway, my original problem doesn't exist anymore, so I'll close the issue.

**Comment by norhh** [comment]
@gsalzer, yes that's due to the recent changes. Now that I think about it, it's better if such circumstances lead to a crash. Since it isn't good for people to run deployment bytecodes. I'll add some relevant error messages in such cases.

**Comment by gsalzer** [comment]
@norhh I'm a bit confused. Deployment bytecode = creation bytecode, deployed bytecode = runtime bytecode, right?

If it is not good for people to run deployment (creation) bytecode, why is it the default for `analyze -f`?

Besides, it makes perfectly sense to analyze deployment (creation) bytecode, as there are millions of deployments where all the action happens during deployment, and in the end a zombie contract is deployed (or none at all).

**Comment by norhh** [comment]
Yes, I mean it's not possible to run deployed code as creation code. My previous statement has a typo.  Mythril is actually a bytecode analyzer, so it defaults to accepting creation code,  Other MythX tools preprocess the input and feed the resultant bytecode to Mythril. Mythril has a wrapper that uses external libraries to convert source code to bytecode (It can only convert from versions 0.4.0+) and has issues with bytecode to source code mapping in a few cases due to internal solc issues.

**Comment by gsalzer** [comment]
@norhh  Thanks for the clarification.
