### ISSUE TITLE
Exception occurred but analysis completed while using mythril

### ISSUE THREAD

**Issue by aga7hokakological** [ConsenSys/mythril#1575]
I tried running myth analyze but I got an critical exception but also completed successful.

I am using arch on wsl.

```
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please repo
rt this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mythril/mythril/mythril_analyzer.py", line 145, in fir
e_lasers
    sym = SymExecWrapper(
  File "/usr/lib/python3.9/site-packages/mythril/analysis/symbolic.py", line 162, in __init__
    self.laser.sym_exec(
  File "/usr/lib/python3.9/site-packages/mythril/laser/ethereum/svm.py", line 165, in sym_exec
    created_account = execute_contract_creation(
  File "/usr/lib/python3.9/site-packages/mythril/laser/ethereum/transaction/symbolic.py", line
150, in execute_contract_creation
    laser_evm.exec(True)
  File "/usr/lib/python3.9/site-packages/mythril/laser/ethereum/svm.py", line 247, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/lib/python3.9/site-packages/mythril/laser/ethereum/svm.py", line 335, in execute_s
tate
    new_global_states = Instruction(
  File "/usr/lib/python3.9/site-packages/mythril/laser/ethereum/instructions.py", line 240, in
evaluate
    result = instruction_mutator(global_state)
  File "/usr/lib/python3.9/site-packages/mythril/laser/ethereum/instructions.py", line 187, in
wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/usr/lib/python3.9/site-packages/mythril/laser/ethereum/instructions.py", line 122, in
call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/usr/lib/python3.9/site-packages/mythril/laser/ethereum/instructions.py", line 1811, in
 return_
    global_state.current_transaction.end(global_state, return_data)
  File "/usr/lib/python3.9/site-packages/mythril/laser/ethereum/transaction/transaction_models.
py", line 254, in end
    contract_code = bytes.hex(array.array("B", return_data).tostring())
AttributeError: 'array.array' object has no attribute 'tostring'
```

And the last line was

```
The analysis was completed successfully. No issues were detected.
```

**Comment by norhh** [comment]
Thanks for reporting @aga7hokakological, are you running on python 3.9?

**Comment by norhh** [comment]
@aga7hokakological thanks for reporting this issue, can you try with the latest version, this issue should be resolved in it.

**Comment by norhh** [comment]
This should be fixed now. @aga7hokakological , feel free to reopen this issue if it still persists.
