### ISSUE TITLE
myth analyze command not working on Ubuntu

### ISSUE THREAD

**Issue by BuggerBag** [ConsenSys/mythril#1598]
Hi, I install myth via
```
# Update
sudo apt update

# Install solc
sudo apt install software-properties-common
sudo add-apt-repository ppa:ethereum/ethereum
sudo apt install solc

# Install libssl-dev, python3-dev, and python3-pip
sudo apt install libssl-dev python3-dev python3-pip

# Install mythril
pip3 install mythril
myth version
```
after running ```myth analyze contract.sol```
it let me an error:
```
mythril.ethereum.util [ERROR]: Encountered a decode error, stdout:, stderr: b'""."" is not a valid file. Skipping\n'
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mythril/interfaces/cli.py", line 960, in parse_args_and_execute
    address = load_code(disassembler, args)
  File "/usr/local/lib/python3.8/dist-packages/mythril/interfaces/cli.py", line 703, in load_code
    address, _ = disassembler.load_from_solidity(
  File "/usr/local/lib/python3.8/dist-packages/mythril/mythril/mythril_disassembler.py", line 182, in load_from_solidity
    self.sigs.import_solidity_file(
  File "/usr/local/lib/python3.8/dist-packages/mythril/support/signatures.py", line 245, in import_solidity_file
    solc_json = get_solc_json(file_path, solc_binary, solc_settings_json)
  File "/usr/local/lib/python3.8/dist-packages/mythril/ethereum/util.py", line 90, in get_solc_json
    raise e
  File "/usr/local/lib/python3.8/dist-packages/mythril/ethereum/util.py", line 87, in get_solc_json
    result = json.loads(out)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I upgrade all the things but the issue never disappears.

my contract is
```solidity
pragma solidity 0.4.24;

contract SimpleDAO {
  mapping (address => uint) public credit;
    
  function donate(address to) payable public{
    credit[to] += msg.value;
  }
    
  function withdraw(uint amount) public{
    if (credit[msg.sender]>= amount) {
      require(msg.sender.call.value(amount)());
      credit[msg.sender]-=amount;
    }
  }  

  function queryCredit(address to) view public returns(uint){
    return credit[to];
  }
}
```
I already run ```solc-select``` ```install``` and ```use``` command for pragma 0.4.24 too.
In previous version of mythril, all the things goes right but in version 0.22.32, it's showing an error.

**Comment by BuggerBag** [comment]
Bug is solved
I uninstall ```solc-select``` and install it again
then run ```solc-select install 0.4.24```
then run ```solc-select use 0.4.24```
then run ```myth analyze contract.sol```
after all, it works for me!
