### ISSUE TITLE
Mythril has a problem at EtherCoin contract

### ISSUE THREAD

**Issue by BuggerBag** [ConsenSys/mythril#1599]
hi, I test the EtherCoin contract with Mythril, but it takes me an error.
```solidity
//SPDX-License-Identifier: MIT

pragma solidity ^0.7.0;
contract EtherCoin{
    EtherPool public etherpool;
    mapping (address=>uint) Balances;
    function hasFunds(address user) public view returns(bool){
        if(Balances[user]>0){return true;}else{return false;}
    }
    function creator(address payable user) internal{
        etherpool=(new EtherPool){value:Balances[user]}({_ethercoinAddress:address(this),user:user});
        Balances[user] = 0; //set balance to zero
    }
    function deposit() external payable{
        Balances[msg.sender]+=msg.value;
    }
    function withdrawAll() external {
        creator(payable(msg.sender));
    }

}
contract EtherPool{
    EtherCoin public ethercoin;
    constructor(address _ethercoinAddress,address payable user) payable{
        if(user!=address(0)){
            ethercoin=EtherCoin(_ethercoinAddress);
            if(ethercoin.hasFunds(user)){
                (bool success,)=user.call{value:msg.value}("");
                require(success,"revert");
            }
        }
    }
}
```
Error:
```
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mythril/interfaces/cli.py", line 961, in parse_args_and_execute
    execute_command(
  File "/usr/local/lib/python3.8/dist-packages/mythril/interfaces/cli.py", line 871, in execute_command
    report = analyzer.fire_lasers(
  File "/usr/local/lib/python3.8/dist-packages/mythril/mythril/mythril_analyzer.py", line 180, in fire_lasers
    issue.add_code_info(contract)
  File "/usr/local/lib/python3.8/dist-packages/mythril/analysis/report.py", line 151, in add_code_info
    codeinfo = contract.get_source_info(
  File "/usr/local/lib/python3.8/dist-packages/mythril/solidity/soliditycontract.py", line 202, in get_source_info
    file_index = mappings[index].solidity_file_idx
IndexError: list index out of range
```
I use ```solc-select use 0.7.3```
thanks.

**Comment by BuggerBag** [comment]
another problem is Mythril is not working on Rubixi and Parity wallet contract.
I test other smart contracts from the SWC repo and it works well.

**Comment by norhh** [comment]
@BuggerBag what version of mythril are you using?

**Comment by BuggerBag** [comment]
hi, here is:
Mythril version v0.22.32
