### ISSUE TITLE
Got ValueError when try to analyze a piece of bytecode

### ISSUE THREAD

**Issue by echohermion** [ConsenSys/mythril#1624]
## Description

Hi there, I used `myth analyze -c .bin` to analyze a bin file and got the following error information:

```
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mythril/interfaces/cli.py", line 924, in parse_args_and_execute
    address = load_code(disassembler, args)
  File "/usr/local/lib/python3.9/site-packages/mythril/interfaces/cli.py", line 670, in load_code
    address, _ = disassembler.load_from_bytecode(code, args.bin_runtime)
  File "/usr/local/lib/python3.9/site-packages/mythril/mythril/mythril_disassembler.py", line 107, in load_from_bytecode
    EVMContract(
  File "/usr/local/lib/python3.9/site-packages/mythril/ethereum/evmcontract.py", line 39, in __init__
    self.creation_disassembly = Disassembly(
  File "/usr/local/lib/python3.9/site-packages/mythril/disassembler/disassembly.py", line 27, in __init__
    self.instruction_list = asm.disassemble(util.safe_decode(code))
  File "/usr/local/lib/python3.9/site-packages/mythril/ethereum/util.py", line 35, in safe_decode
    return bytes.fromhex(hex_encoded_string)
ValueError: non-hexadecimal number found in fromhex() arg at position 0
```

Here is the content of the bin file.

```
60566023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220e76ba56361471e437554b7c19133a35879ce40c8f884c09f7fb80c6e738f337b64736f6c63430006050033
```

I use pip to install mythril and the python version is 3.9.12 on Mac OS X. How could I fix the issue?

**Comment by norhh** [comment]
Hi @echohermion, 
you need to use the `-f` flag to run bytecode from a file. ex:- `myth analyze -f file.bin `

**Comment by echohermion** [comment]
It works well now. Thank you so much!

**Comment by echohermion** [comment]
> Hi @echohermion, you need to use the `-f` flag to run bytecode from a file. ex:- `myth analyze -f file.bin `

It works well now. Thank you so much!
