### ISSUE TITLE
mythril.laser.ethereum.evm_exceptions.OutOfGasException

### ISSUE THREAD

**Issue by gsalzer** [ConsenSys/mythril#1672]
## Description

Mythril raises the exception `mythril.laser.ethereum.evm_exceptions.OutOfGasException`.

## How to Reproduce

```console
$ cat > 0x2e5750b4d2f6945c456fdd23686652619f537c38.hex <<END
608060405260043610610057576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806301f59d161461005c57806312adddd41461008757806325245b26146100de575b600080fd5b34801561006857600080fd5b50610071610192565b6040518082815260200191505060405180910390f35b34801561009357600080fd5b5061009c610198565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b61017860048036038101908080359060200190820180359060200190808060200260200160405190810160405280939291908181526020018383602002808284378201915050505050509192919290803590602001908201803590602001908080602002602001604051908101604052809392919081815260200183836020028082843782019150505050505091929192905050506101bd565b604051808215151515815260200191505060405180910390f35b60015481565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6000806000806000855187511415156101d257fe5b60ff8751111515156101e057fe5b34935060009250600091505b86518260ff16101561029557858260ff1681518110151561020957fe5b9060200190602002015183019250868260ff1681518110151561022857fe5b9060200190602002015173ffffffffffffffffffffffffffffffffffffffff166108fc878460ff1681518110151561025c57fe5b906020019060200201519081150290604051600060405180830381858888f19350505050151561028857fe5b81806001019250506101ec565b600154830192506000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166108fc6001549081150290604051600060405180830381858888f1935050505015156102fc57fe5b82840390506000811115610348573373ffffffffffffffffffffffffffffffffffffffff166108fc829081150290604051600060405180830381858888f19350505050151561034757fe5b5b6001945050505050929150505600a165627a7a723058206fb14b90861a435a4bc5adf691cd1555bbbd6899d0323d591a5232e38c46fea90029
END
$ myth a -o json --bin-runtime -f 0x2e5750b4d2f6945c456fdd23686652619f537c38.hex
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/mythril/mythril/laser/ethereum/svm.py", line 378, in execute_state
    new_global_states = Instruction(
  File "/mythril/mythril/laser/ethereum/instructions.py", line 264, in evaluate
    result = instruction_mutator(global_state)
  File "/mythril/mythril/laser/ethereum/instructions.py", line 196, in wrapper
    new_global_states = [
  File "/mythril/mythril/laser/ethereum/instructions.py", line 197, in <listcomp>
    self.accumulate_gas(state) for state in new_global_states
  File "/mythril/mythril/laser/ethereum/instructions.py", line 174, in accumulate_gas
    self.check_gas_usage_limit(global_state)
  File "/mythril/mythril/laser/ethereum/instructions.py", line 160, in check_gas_usage_limit
    raise OutOfGasException()
mythril.laser.ethereum.evm_exceptions.OutOfGasException
```

## Environment

- Mythril version: `0.23.8`
- Python version: `3.9.13`
- OS: `Ubuntu 18.04.6 LTS`

**Comment by gsalzer** [comment]
Same exception as #1657, but the old issue was marked as resolved (and seems indeed resolved).
