### ISSUE TITLE
Could not install Mythrill on ubuntu

### ISSUE THREAD

**Issue by GraphicalDot** [ConsenSys/mythril#1676]
## How to Reproduce
```
ubuntu@ip-10-0-1-162:~$ pip3 install mythril
Defaulting to user installation because normal site-packages is not writeable
Collecting mythril
  Using cached mythril-0.23.8.tar.gz (4.5 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: MarkupSafe<2.1.0 in /usr/lib/python3/dist-packages (from mythril) (2.0.1)
Collecting asn1crypto>=0.22.0
  Using cached asn1crypto-1.5.1-py2.py3-none-any.whl (105 kB)
Collecting blake2b-py
  Using cached blake2b_py-0.1.3.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-g69c06p1 --interpreter /usr/bin/python3`
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-kqrtpesb/overlay/local/lib/python3.10/dist-packages/maturin/__init__.py", line 174, in prepare_metadata_for_build_wheel
          output = subprocess.check_output(command)
        File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.10/subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'maturin'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

-->

**Comment by norhh** [comment]
Try switching to python 3.9. It should work

**Comment by B353S** [comment]
Just install maturin
sudo pip3 install maturin

**Comment by lelerukjaymoh** [comment]
Sure It works well on 3.9. :confetti_ball:  
You may also need to install PIL

**Comment by gerald62** [comment]
u need to install maturin and the nightly build of rust .. worked for me

**Comment by gerald62** [comment]
there is also wheel something..

**Comment by emretepedev** [comment]
Same issue here.

**Comment by gerald62** [comment]
Try installing rust and the missing python modules
