### ISSUE TITLE
Assertion Error: Bytecode is different when querying mainnet vs locally

### ISSUE THREAD

**Issue by joewww** [ConsenSys/mythril#185]
# Sympton

Hello, I'm noticing some strange behavior when quering a contract via -i, versus querying a contracts bytecode locally.

# Version
v0.17.5

# Steps to recreate

If I add some debugging info:

```
joe@dev1:~/mythril$ git diff .
diff --git a/mythril/mythril.py b/mythril/mythril.py
index 1686048..4deb7a5 100644
--- a/mythril/mythril.py
+++ b/mythril/mythril.py
@@ -250,6 +250,9 @@ class Mythril(object):

         try:
             code = self.eth.eth_getCode(address)
+            print("mythril.py: START DEBUG")
+            print(code)
+            print("mythril.py: END DEBUG")
         except FileNotFoundError as e:
              raise CriticalError("IPC error: " + str(e))
         except ConnectionError as e:
```

And query the contract using Infuras API, I see the following:

```
joe@dev1:~/mythril$ myth -xia 0x1bb28e79f2482df6bf60efc7a33365703bcf1536
mythril.py: START DEBUG
0x6060604052361561004a576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063354284f2146100e75780634a3f17e7146100f9575b6100e55b34600060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008282540192505081905550343373ffffffffffffffffffffffffffffffffffffffff167f115522125a340a348d82c36b243d9dcbb357931a24824ddbe1d13179155e309160405180905060405180910390a35b565b005b34156100ef57fe5b6100f7610143565b005b341561010157fe5b61012d600480803573ffffffffffffffffffffffffffffffffffffffff169060200190919050506102b5565b6040518082815260200191505060405180910390f35b6000635f220d804211801561019757506000600060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054115b15156101a35760006000fd5b600060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205490506000600060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055503373ffffffffffffffffffffffffffffffffffffffff166108fc829081150290604051809050600060405180830381858888f19350505050151561026a57fe5b803373ffffffffffffffffffffffffffffffffffffffff167f0dc8f43545dbeec87c6f54e44dac2d8889f2a4b3bf0f62683cd7e1c6346128e760405180905060405180910390a35b50565b600060205280600052604060002060009150905054815600a165627a7a72305820ff37ab4aec94c93a993cc8874bf94a6d3d706d3eeb6b5b5df89d7c23a75227310029
mythril.py: END DEBUG
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 4, in <module>
    __import__('pkg_resources').run_script('mythril==0.17.5', 'myth')
...
  File "/usr/local/lib/python3.6/dist-packages/laser/ethereum/taint_analysis.py", line 131, in execute_state
    assert len(state.mstate.stack) == len(record.stack)
AssertionError
```

which triggers an assertion error. But if I view the contract from Etherscan: https://etherscan.io/address/0x1bb28e79f2482df6bf60efc7a33365703bcf1536#code

and paste the bytecode in directly to mythril, it executes successfully.

```
joe@dev1:~/mythril$ cat etherscan.bytecode
6060604052341561000c57fe5b5b6102f98061001c6000396000f3006060604052361561004a576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063354284f2146100e75780634a3f17e7146100f9575b6100e55b34600060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008282540192505081905550343373ffffffffffffffffffffffffffffffffffffffff167f115522125a340a348d82c36b243d9dcbb357931a24824ddbe1d13179155e309160405180905060405180910390a35b565b005b34156100ef57fe5b6100f7610143565b005b341561010157fe5b61012d600480803573ffffffffffffffffffffffffffffffffffffffff169060200190919050506102b5565b6040518082815260200191505060405180910390f35b6000635f220d804211801561019757506000600060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054115b15156101a35760006000fd5b600060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205490506000600060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055503373ffffffffffffffffffffffffffffffffffffffff166108fc829081150290604051809050600060405180830381858888f19350505050151561026a57fe5b803373ffffffffffffffffffffffffffffffffffffffff167f0dc8f43545dbeec87c6f54e44dac2d8889f2a4b3bf0f62683cd7e1c6346128e760405180905060405180910390a35b50565b600060205280600052604060002060009150905054815600a165627a7a72305820ff37ab4aec94c93a993cc8874bf94a6d3d706d3eeb6b5b5df89d7c23a75227310029
joe@dev1:~/mythril$ myth -xc $(cat etherscan.bytecode)
The analysis was completed successfully. No issues were detected.
```

You will notice that the bytecode returned from -i is different from the bytecode as listed on Etherscan. Should it be parsing the same exact bytecode in both use cases, or is it trying to reconstruct it in some odd way?

**Comment by b-mueller** [comment]
Thanks @joewww.

The assertion error appears to be similar to the TaintRunner issue described in the discussion of #166.

Regarding the bytecode, Etherscan shows the *contract creation* code, while Mythril retrieves the *runtime* bytecode. It's natural for those two to be different!

**Comment by JoranHonig** [comment]
@b-mueller Yes, this is a duplicate issue. So this one can be closed. 
@joewww  I already created a pr https://github.com/b-mueller/laser-ethereum/pull/22#partial-pull-merging for this. Once that gets merged and released, your problem should be fixed
