### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by suhabe** [ConsenSys/mythril#187]
Mythril crashes on the following benchmark:

```
contract Benchmark {
    function () public {
        if ( sha256 (10 ) < 10 ){
            msg.sender.transfer(10);
        }
    }
}
```

```
vagrant@vagrant:~$ pip3 search mythril
mythril (0.17.5)  - Security analysis tool for Ethereum smart contracts
  INSTALLED: 0.17.5 (latest)
vagrant@vagrant:~$ myth -x host/benchmarks/test2.sol 
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/usr/local/lib/python3.5/dist-packages/mythril/interfaces/cli.py", line 202, in main
    max_depth=args.max_depth)
  File "/usr/local/lib/python3.5/dist-packages/mythril/mythril.py", line 322, in fire_lasers
    max_depth=max_depth)
  File "/usr/local/lib/python3.5/dist-packages/mythril/analysis/symbolic.py", line 22, in __init__
    self.laser.sym_exec(address)
  File "/usr/local/lib/python3.5/dist-packages/laser/ethereum/svm.py", line 263, in sym_exec
    node = self._sym_exec(gblState)
  File "/usr/local/lib/python3.5/dist-packages/laser/ethereum/svm.py", line 892, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth + 1, constraints=new_constraints)
  File "/usr/local/lib/python3.5/dist-packages/laser/ethereum/svm.py", line 892, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth + 1, constraints=new_constraints)
  File "/usr/local/lib/python3.5/dist-packages/laser/ethereum/svm.py", line 892, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth + 1, constraints=new_constraints)
  File "/usr/local/lib/python3.5/dist-packages/laser/ethereum/svm.py", line 471, in _sym_exec
    exp = ULT(helper.pop_bitvec(state), helper.pop_bitvec(state))
  File "/usr/local/lib/python3.5/dist-packages/laser/ethereum/helper.py", line 49, in pop_bitvec
    item = state.stack.pop()
IndexError: pop from empty list
```

**Comment by b-mueller** [comment]
Fixed in 0.17.6:

```
$ myth -x bench.sol 
The analysis was completed successfully. No issues were detected.
```
