### ISSUE TITLE
AssertionError thrown

### ISSUE THREAD

**Issue by suhabe** [ConsenSys/mythril#195]
Mythril 0.17.8 throws an AssertionError on this benchmark:
```
pragma solidity ^0.4.16;

contract Benchmark {

    function () public payable { 
        if ( sha256 (msg.data ) < bytes32 (11111) ) {
            msg.sender.transfer(10); 
        }
    }
}
```

```
vagrant@vagrant:~/host/benchmarks$ myth -x bug_2.sol 
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/usr/local/lib/python3.5/dist-packages/mythril/interfaces/cli.py", line 202, in main
    max_depth=args.max_depth)
  File "/usr/local/lib/python3.5/dist-packages/mythril/mythril.py", line 324, in fire_lasers
    issues = fire_lasers(sym, modules)
  File "/usr/local/lib/python3.5/dist-packages/mythril/analysis/security.py", line 20, in fire_lasers
    issues += module.execute(statespace)
  File "/usr/local/lib/python3.5/dist-packages/mythril/analysis/modules/integer.py", line 34, in execute
    issues += _check_integer_overflow(statespace, state, node)
  File "/usr/local/lib/python3.5/dist-packages/mythril/analysis/modules/integer.py", line 84, in _check_integer_overflow
    if not _verify_integer_overflow(statespace, node, expr, state, model, constraint, op0, op1):
  File "/usr/local/lib/python3.5/dist-packages/mythril/analysis/modules/integer.py", line 103, in _verify_integer_overflow
    interesting_usages = _search_children(statespace, node, expr, constraint=[constraint], index=node.states.index(state))
  File "/usr/local/lib/python3.5/dist-packages/mythril/analysis/modules/integer.py", line 234, in _search_children
    taint_result = TaintRunner.execute(statespace, node, state, initial_stack=taint_stack)
  File "/usr/local/lib/python3.5/dist-packages/laser/ethereum/taint_analysis.py", line 106, in execute
    records = TaintRunner.execute_node(node, record, index)
  File "/usr/local/lib/python3.5/dist-packages/laser/ethereum/taint_analysis.py", line 126, in execute_node
    records.append(TaintRunner.execute_state(records[-1], current_state))
  File "/usr/local/lib/python3.5/dist-packages/laser/ethereum/taint_analysis.py", line 131, in execute_state
    assert len(state.mstate.stack) == len(record.stack)
AssertionError

``

**Comment by JoranHonig** [comment]
This is an issue with laser:
https://github.com/b-mueller/laser-ethereum/issues/27
fixed with:
https://github.com/b-mueller/laser-ethereum/pull/28
