### ISSUE TITLE
Exception on Centos. Working fine on macOS

### ISSUE THREAD

**Issue by chapati23** [ConsenSys/mythril#199]
Hey,
ran into another issue with mythril today. Running `truffle compile && myth --truffle` throws the following exception in our CI (based on `centos:7`):

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/laser/ethereum/svm.py", line 968, in _sym_exec
    callee_address = hex(helper.get_concrete_int(to))
  File "/usr/lib/python3.6/site-packages/laser/ethereum/helper.py", line 72, in get_concrete_int
    return simplify(item).as_long()
AttributeError: 'BitVecRef' object has no attribute 'as_long'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/usr/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 134, in main
    mythril.analyze_truffle_project(args)
  File "/usr/lib/python3.6/site-packages/mythril/mythril.py", line 139, in analyze_truffle_project
    return analyze_truffle_project(*args, **kwargs)  # just passthru for now
  File "/usr/lib/python3.6/site-packages/mythril/support/truffle.py", line 44, in analyze_truffle_project
    sym = SymExecWrapper(ethcontract, address, max_depth=10)
  File "/usr/lib/python3.6/site-packages/mythril/analysis/symbolic.py", line 22, in __init__
    self.laser.sym_exec(address)
  File "/usr/lib/python3.6/site-packages/laser/ethereum/svm.py", line 265, in sym_exec
    node = self._sym_exec(gblState)
  File "/usr/lib/python3.6/site-packages/laser/ethereum/svm.py", line 927, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/lib/python3.6/site-packages/laser/ethereum/svm.py", line 927, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/lib/python3.6/site-packages/laser/ethereum/svm.py", line 927, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  [Previous line repeated 20 more times]
  File "/usr/lib/python3.6/site-packages/laser/ethereum/svm.py", line 904, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/lib/python3.6/site-packages/laser/ethereum/svm.py", line 854, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/lib/python3.6/site-packages/laser/ethereum/svm.py", line 854, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/lib/python3.6/site-packages/laser/ethereum/svm.py", line 854, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/lib/python3.6/site-packages/laser/ethereum/svm.py", line 904, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/lib/python3.6/site-packages/laser/ethereum/svm.py", line 904, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/lib/python3.6/site-packages/laser/ethereum/svm.py", line 1001, in _sym_exec
    state.mem_extend(memoutstart, 1)
  File "/usr/lib/python3.6/site-packages/laser/ethereum/svm.py", line 115, in mem_extend
    if (start < 4096 and sz < 4096):
  File "/usr/lib/python3.6/site-packages/z3/z3.py", line 318, in __bool__
    raise Z3Exception("Symbolic expressions cannot be cast to concrete Boolean values.")
z3.z3types.Z3Exception: Symbolic expressions cannot be cast to concrete Boolean values.
```

### How to reproduce
1. `docker pull centos:7`
1. `docker run -it centos /bin/sh`
1. `yum -y update`
1. `yum -y install yum-utils`
1. `yum -y groupinstall development`
1. `yum -y install https://centos7.iuscommunity.org/ius-release.rpm`
1. `yum -y install python36u`
1. `yum -y install python36u-pip`
1. `yum -y install python36u-devel`
1. `pip3.6 install --upgrade pip`
1. `yum install openssl-devel wget bzip2`
1. `pip3.6 install mythril`
1. `git clone https://github.com/brickblock-io/smart-contracts`
1. `cd smart-contracts`
1. `truffle compile`
1. `myth --truffle`

It works fine on macOS for me, and it used to work fine in centos for us until recently.

Were any new system-level dependencies added for mythril? Unfortunately there's no install instructions for `rpm`-based distros like debian or centos so I'm tapping in the dark here a little bit.

**Comment by p0n1** [comment]
It does not work on macOS too.

```
memoutstart:
160 +
32*
Concat(0,
       Extract(255,
               5,
               31 +
               calldata_ExchangeRates_4 + calldata_ExchangeRates_4)) +
160
```

I'll try to handle this symbolic memory access.

**Comment by hefgi** [comment]
same here on mac os 10.13.4, python 3.6.5

```Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 581, in _sym_exec
    dstart = helper.get_concrete_int(op1)
  File "/usr/local/lib/python3.6/site-packages/laser/ethereum/helper.py", line 72, in get_concrete_int
    return simplify(item).as_long()
AttributeError: 'BitVecRef' object has no attribute 'as_long'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/usr/local/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 202, in main
    max_depth=args.max_depth)
  File "/usr/local/lib/python3.6/site-packages/mythril/mythril.py", line 322, in fire_lasers
    max_depth=max_depth)
  File "/usr/local/lib/python3.6/site-packages/mythril/analysis/symbolic.py", line 22, in __init__
    self.laser.sym_exec(address)
  File "/usr/local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 265, in sym_exec
    node = self._sym_exec(gblState)
  File "/usr/local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 927, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 904, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 904, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 854, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 904, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 904, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 854, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 854, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 584, in _sym_exec
    state.mem_extend(mstart, 1)
  File "/usr/local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 128, in mem_extend
    raise Exception
Exception```

**Comment by p0n1** [comment]
@JoranHonig Try to fix in https://github.com/b-mueller/laser-ethereum/pull/35.

Help review please.
