### ISSUE TITLE
No issues report index error

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril#215]

**Comment by JoranHonig** [comment]
Recently @birdofpreyru  found the following bug:
```
root@4b8e9a2487db:/home# myth -xc abcc
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 4, in <module>
    __import__('pkg_resources').run_script('mythril==0.17.12', 'myth')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.17.12-py3.6.egg/EGG-INFO/scripts/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.17.12-py3.6.egg/mythril/interfaces/cli.py", line 205, in main
    'text': report.as_text(),
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.17.12-py3.6.egg/mythril/analysis/report.py", line 54, in as_text
    filename = list(self.issues.values())[0].filename
IndexError: list index out of range
```

**Comment by JoranHonig** [comment]
This is caused by a problem in report.py
