### ISSUE TITLE
Initialization stops at block 1898

### ISSUE THREAD

**Issue by jaylagorio** [ConsenSys/mythril#257]
To initialize my database I use ``myth -i --init-db``. It's been slow and riddled with 502 errors along the way, but restarting each time has gotten things going. Now it's stuck on ``Resuming synchronization from block 1898`` and doesn't seem to move forward no matter how long I wait. I ran a ``git pull`` to make sure I was using the latest version of the project and I'm running it in a Docker instance.

Any suggestions to make it finish up so I can get to the point where I sync the difference between the head block at the time I started this and now? Alternatively, I'm willing to forego the first 1898 ETH blocks in existence and just sync the latest into the database. Is there a way to do that?

Edit: It appears there's an intermittent error involved in processing this block:

```
Resuming synchronization from block 1898
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.15.8-py3.6.egg/mythril/ether/contractstorage.py"                                                                                               , line 60, in sync_blocks
    for tx in block['transactions']:
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/myth", line 4, in <module>
    __import__('pkg_resources').run_script('mythril==0.15.8', 'myth')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.15.8-py3.6.egg/EGG-INFO/scripts/myth", line 255,                                                                                                in <module>
    contract_storage.initialize(eth)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.15.8-py3.6.egg/mythril/ether/contractstorage.py"                                                                                               , line 110, in initialize
    results = pool.map(self.sync_blocks, numbers)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: 'NoneType' object is not subscriptable
```

**Comment by b-mueller** [comment]
PS, yeah syncing from INFURA is crazy slow. I'm surprised you actually got to block 1898!

**Comment by chronaeon** [comment]
@b-mueller I'll add this to the FAQ

**Comment by b-mueller** [comment]
The workaround has been added to the FAQ. I'm closing this issues, but we'll address this more comprehensively with a reworking of the database sync.

**Comment by jaylagorio** [comment]
This worked to reset back to syncing from the top, thanks again guys!

**Comment by b-mueller** [comment]
FYI, here is my [proposal for refactoring the search feature](https://github.com/ConsenSys/mythril/issues/263). This would require users to run a local node to use the search, but I think it's the best way to make sure the feature is useful and returns accurate results. Feedback is appreciated!
