### ISSUE TITLE
$myth -i --init-db syncs intermittently then errors out

### ISSUE THREAD

**Issue by chronaeon** [ConsenSys/mythril#259]
**Describe the bug**
`myth -i --init-db` syncs intermittently then errors out.

```
$ ./myth -i --init-db
WARNING:ZODB.FileStorage:Ignoring index for /home/micah/.mythril/contractstorage.fs
Starting synchronization from latest block: 5750418
2048 blocks processed (in 80 seconds), 2 unique contracts in database, next block: 5748370
4096 blocks processed (in 162 seconds), 11 unique contracts in database, next block: 5746322
6144 blocks processed (in 249 seconds), 15 unique contracts in database, next block: 5744274
...
126976 blocks processed (in 6094 seconds), 600 unique contracts in database, next block: 5623442
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/micah/.local/lib/python3.6/site-packages/mythril/ether/contractstorage.py", line 57, in __call__
    block = self.eth.eth_getBlockByNumber(blockNum)
  File "/home/micah/.local/lib/python3.6/site-packages/mythril/rpc/base_client.py", line 75, in eth_getBlockByNumber
    return self._call('eth_getBlockByNumber', [block, tx_objects])
  File "/home/micah/.local/lib/python3.6/site-packages/mythril/rpc/client.py", line 51, in _call
    raise BadStatusCodeError(r.status_code)
mythril.rpc.exceptions.BadStatusCodeError: 502
"""
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./myth", line 255, in <module>
    contract_storage.initialize(eth)
  File "/home/micah/.local/lib/python3.6/site-packages/mythril/ether/contractstorage.py", line 120, in initialize
    results = pool.map(SyncBlocks(self.eth), numbers)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
mythril.rpc.exceptions.BadStatusCodeError: 502
```
Tried again right after the error and it synced one line (2048 blocks) before throwing the same error:

```
./myth -i --init-db
Resuming synchronization from block 5623442
2048 blocks processed (in 86 seconds), 606 unique contracts in database, next block: 5621394

```
Tried again ~12 hours later. After waiting a bit, it synced six lines (12288 blocks), then before erroring out.

**Desktop (please complete the following information):**
 - Ubuntu 18.04

**Comment by chronaeon** [comment]
Agree the `--init-db` over INFURA can probably go.
Do you think a similar replacement functionality could be offered through an Alethio API?
