### ISSUE TITLE
Refactor the search feature

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#263]
## Description: 

Currently, we sync via RPC to a local "contractdb" for performing search operations. This method is inefficient and has a lot of other problems, including inaccurate reflection of account states (balances), and more.

There is already [support for searching there state trie of a local geth node](https://github.com/ConsenSys/mythril/tree/master/mythril/leveldb). However, the way it is currently implemented, it only works for small testnets. The [EthLevelDB class](https://github.com/ConsenSys/mythril/blob/master/mythril/leveldb/client.py) first parses the complete state to create a list of all 'active' contracts in memory before search operations can be invoked. Obviously this is infeasible if the state trie is large.

To make this usable, it needs to be implemented in a way that allows users to iterate through contracts in the state trie either one-by-one, or by providing a search expression that invokes a callback. 

## Implementation details:Initial implementation ideas/instruction

1. Refactor the LevelDB client class to allow one to iterate over contracts in the geth leveldb instead of reading all contracts into memory in advance.

2. Refactor the search feature to invoke the new leveldb client class. Remove all references to contract storage.

3. Remove the old persistence layer ([contractstorage.py](https://github.com/ConsenSys/mythril/blob/master/mythril/ether/contractstorage.py)), the ZODB requirement and the `--init-db` feature. 

Once the implementation is done, search only works if a validlocal geth leveldb exists. Otherwise, the user is shown an error message.

**Comment by JoranHonig** [comment]
Using a python generator function should be a good fit for this

**Comment by b-mueller** [comment]
@birdofpreyru new challenge for the TopCoder crew :)

**Comment by birdofpreyru** [comment]
Here we go: https://www.topcoder.com/challenges/30066270

**Comment by b-mueller** [comment]
Thanks @birdofpreyru!

**Comment by delaanthonio** [comment]
Does the search feature currently work?

Whenever I try to search I get the following output:

```
~/Projects/mythril feature/search*
❯ ./myth --search "func#changeMultisig(address)#" --leveldb ~/.ethereum/geth/chaindata
Traceback (most recent call last):
  File "./myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/ext/b2/mythril/mythril/interfaces/cli.py", line 142, in main
    mythril.search_db(args.search)
  File "/ext/b2/mythril/mythril/mythril.py", line 224, in search_db
    self.ethDb.search(search, search_callback)
  File "/ext/b2/mythril/mythril/leveldb/client.py", line 80, in search
    for contract, m in self.get_active_contracts():
  File "/ext/b2/mythril/mythril/leveldb/client.py", line 72, in get_active_contracts
    for contract, md5 in self.get_all_contracts():
  File "/ext/b2/mythril/mythril/leveldb/client.py", line 53, in get_all_contracts
    for a in state.get_all_accounts():
  File "/ext/b2/mythril/mythril/leveldb/state.py", line 127, in get_all_accounts
    for address_hash, rlpdata in self.secureTrie.trie.to_dict().items():
  File "/home/dela/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ethereum/trie.py", line 884, in to_dict
    d = self._to_dict(self.root_node)
  File "/home/dela/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ethereum/trie.py", line 869, in _to_dict
    sub_dict = self._to_dict(self._decode_to_node(node[i]))
  File "/home/dela/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ethereum/trie.py", line 229, in _decode_to_node
    o = rlp.decode(self.db.get(encoded))
  File "/home/dela/.pyenv/versions/3.6.4/lib/python3.6/site-packages/rlp/codec.py", line 217, in decode
    rlp = str_to_bytes(rlp)
  File "/home/dela/.pyenv/versions/3.6.4/lib/python3.6/site-packages/rlp/utils_py3.py", line 20, in str_to_bytes
    return bytes(value, 'utf-8')
TypeError: encoding without a string argument
```
Do you know how I can fix this issue?

**Comment by b-mueller** [comment]
Tbh I never tested this feature properly myself. I'm not getting this error, but the search also doesn't terminate because I'm running in on a fully synced node.

What's your environment:

- OS
- Python version
- pip freeze

**Comment by delaanthonio** [comment]
OS: Arch Linux
Python: 3.6.4
Pip Freeze:
```
aniso8601==3.0.0
asn1crypto==0.24.0
astroid==1.6.1
atomicwrites==1.1.5
attrdict==2.0.0
attrs==17.4.0
autobahn==18.6.1
Automat==0.6.0
BTrees==4.5.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
coincurve==7.1.0
constantly==15.1.0
coverage==4.5.1
cryptography==2.2.2
cycler==0.10.0
cytoolz==0.9.0.1
dictionaries==0.0.1
eth-abi==1.1.1
eth-account==0.2.3
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-tester==0.1.0b27
eth-utils==1.0.3
ethereum==2.3.1
Flask==1.0.2
Flask-RESTful==0.3.6
future==0.16.0
hexbytes==0.1.0
hyperlink==18.0.0
idna==2.6
incremental==17.5.0
isort==4.3.4
itsdangerous==0.24
jedi==0.11.1
Jinja2==2.10
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
MarkupSafe==1.0
matplotlib==2.2.2
mccabe==0.6.1
mock==2.0.0
more-itertools==4.1.0
numpy==1.14.2
pandas==0.22.0
parsimonious==0.8.0
parso==0.1.1
pbkdf2==1.3
pbr==4.0.4
persistent==4.2.4.2
pluggy==0.6.0
plyvel==1.0.4
py==1.5.3
py-ecc==1.4.2
py-flags==1.1.2
py-solc==3.1.0
pyasn1==0.4.3
pyasn1-modules==0.2.1
pycparser==2.18
pycryptodome==3.6.1
pyethash==0.1.27
pylint==1.8.2
pyOpenSSL==18.0.0
pyparsing==2.2.0
pysha3==1.0.2
pytest==3.6.1
pytest-cov==2.5.1
pytest-mock==1.10.0
python-dateutil==2.7.2
pytz==2018.4
PyYAML==3.12
repoze.lru==0.7
requests==2.18.4
rlp==0.6.0
scrypt==0.8.6
semantic-version==2.6.0
service-identity==17.0.0
six==1.11.0
toolz==0.9.0
transaction==2.2.1
Twisted==18.4.0
txaio==2.10.0
urllib3==1.22
watson-developer-cloud==1.3.5
Werkzeug==0.14.1
wrapt==1.10.11
yapf==0.20.2
z3-solver==4.5.1.0.post2
zc.lockfile==1.3.0
ZConfig==3.2.0
ZODB==5.4.0
zodbpickle==1.0.1
zope.interface==4.5.0
```

**Comment by delaanthonio** [comment]
@b-mueller does searching still work for you when you specify the `leveldb` path?

**Comment by b-mueller** [comment]
Yes, at least I don't get any errors. Although the search never finished.

**Comment by b-mueller** [comment]
FYI, my Pypi packages:

```
asn1crypto==0.24.0
atomicwrites==1.1.5
attrdict==2.0.0
attrs==18.1.0
BTrees==4.5.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
coincurve==7.1.0
coverage==4.5.1
cytoolz==0.9.0.1
dictionaries==0.0.1
docopt==0.6.2
eth-abi==1.1.1
eth-account==0.2.3
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-tester==0.1.0b27
eth-utils==1.0.3
ethereum==2.3.1
flake8==3.5.0
Flask==1.0.2
future==0.16.0
grip==4.5.2
hexbytes==0.1.0
idna==2.7
itsdangerous==0.24
Jinja2==2.10
laser-ethereum==0.17.12
Markdown==2.6.11
MarkupSafe==1.0
mccabe==0.6.1
mock==2.0.0
mockprocess==0.2
more-itertools==4.2.0
mythril==0.18.4
parsimonious==0.8.0
path-and-address==2.0.1
pbkdf2==1.3
pbr==4.0.4
persistent==4.2.4.2
pluggy==0.6.0
plyvel==1.0.4
py==1.5.3
py-ecc==1.4.2
py-flags==1.1.2
py-solc==3.1.0
pycodestyle==2.3.1
pycparser==2.18
pycryptodome==3.6.1
pyethash==0.1.27
pyflakes==1.6.0
Pygments==2.2.0
pysha3==1.0.2
pytest==3.6.0
pytest-cov==2.5.1
pytest-mock==1.10.0
PyYAML==3.12
repoze.lru==0.7
requests==2.19.0
rlp==0.6.0
scrypt==0.8.6
semantic-version==2.6.0
six==1.11.0
toolz==0.9.0
transaction==2.2.1
urllib3==1.23
Werkzeug==0.14.1
z3-solver==4.5.1.0.post2
zc.lockfile==1.3.0
ZConfig==3.2.0
ZODB==5.4.0
zodbpickle==1.0.1
zope.interface==4.5.0
```

**Comment by delaanthonio** [comment]
I removed the files in my `chaindata` and ran `geth`. Searching works now.
