### ISSUE TITLE
AttributeError on 'myth --truffle'

### ISSUE THREAD

**Issue by kyriediculous** [ConsenSys/mythril#271]
**Describe the bug**
Hi again,

I have a truffle project which contains many contracts. I try to run` myth --truffle` as described on the wiki. 
It seems to go right for my ERC20 token contract, which is probably the only 'normal' contract of the bunch. 

My other contracts consist out of proxies, libraries, storage and a controller. My proxies use a lower version of delegatecall() using assembly, just like in zeppelinOS. 

My truffle tests all run fine, migration file runs fine, etc .. 

This is the error I'm getting: 
```

osboxes@osboxes:~/blockchain-programmable-incentives$ myth --truffle# Analysis result for Token:

==== Integer Overflow  ====
Type: Warning
Contract: Unknown
Function name: _function_0x06fdde03
PC address: 1125
A possible integer overflow exists in the function `_function_0x06fdde03`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: Token.json:152

string public name

--------------------


Traceback (most recent call last):
  File "/home/osboxes/.local/bin/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/home/osboxes/.local/lib/python3.5/site-packages/mythril/interfaces/cli.py", line 134, in main
    mythril.analyze_truffle_project(args)
  File "/home/osboxes/.local/lib/python3.5/site-packages/mythril/mythril.py", line 139, in analyze_truffle_project
    return analyze_truffle_project(*args, **kwargs)  # just passthru for now
  File "/home/osboxes/.local/lib/python3.5/site-packages/mythril/support/truffle.py", line 45, in analyze_truffle_project
    issues = fire_lasers(sym)
  File "/home/osboxes/.local/lib/python3.5/site-packages/mythril/analysis/security.py", line 20, in fire_lasers
    issues += module.execute(statespace)
  File "/home/osboxes/.local/lib/python3.5/site-packages/mythril/analysis/modules/transaction_order_independence.py", line 25, in execute
    interesting_storages = list(_get_influencing_storages(call))
  File "/home/osboxes/.local/lib/python3.5/site-packages/mythril/analysis/modules/transaction_order_independence.py", line 103, in _get_influencing_storages
    variable = _get_storage_variable(storage, state)
  File "/home/osboxes/.local/lib/python3.5/site-packages/mythril/analysis/modules/transaction_order_independence.py", line 68, in _get_storage_variable
    index = int(re.search('[0-9]+', storage).group())
AttributeError: 'NoneType' object has no attribute 'group'
```
**To Reproduce**
truffle project: https://github.com/kyriediculous/blockchain-programmable-incentives

**Comment by JoranHonig** [comment]
Hi @kyriediculous, thanks for the report. 
This seems to be caused by the "loose" regex in the _dependent_on_storage function.

**Comment by JoranHonig** [comment]
Hey @kyriediculous, I implemented a fix for your problem. It works for me locally, could you check that it works for you?

The fork is here:
https://github.com/JoranHonig/mythril/tree/bugfix/271

**Comment by kyriediculous** [comment]
Hey @JoranHonig . It seems to be working now indeed. Thanks so much for the quick fix!

Now it's time to take a deep dive into mythril and it's possibilities ! 

Cheers!

**Comment by JoranHonig** [comment]
Happy to be of help!
