### ISSUE TITLE
z3.z3types.Z3Exception: Third argument must be a Z3 Bitvector expression

### ISSUE THREAD

**Issue by suhabe** [ConsenSys/mythril#272]
Mythril 0.18.4 is throwing the exception below:

```
vagrant@vagrant:~/host/packages/sale-contracts$ PATH=/home/vagrant/.py-solc/solc-v0.4.23/bin/:$PATH myth -x --solv 0.4.23 --solc-args="$ZEPPELIN $TFSTATE $TFTOKEN" contracts/Whitelistable.sol 
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/usr/local/lib/python3.5/dist-packages/mythril/interfaces/cli.py", line 202, in main
    max_depth=args.max_depth)
  File "/usr/local/lib/python3.5/dist-packages/mythril/mythril.py", line 323, in fire_lasers
    max_depth=max_depth)
  File "/usr/local/lib/python3.5/dist-packages/mythril/analysis/symbolic.py", line 22, in __init__
    self.laser.sym_exec(address)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 265, in sym_exec
    node = self._sym_exec(gblState)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 910, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 910, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 910, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 910, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 910, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 910, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 896, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 896, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 851, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 851, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 851, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 910, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 851, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 896, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.5/dist-packages/mythril/laser/ethereum/svm.py", line 395, in _sym_exec
    result = Concat(BitVecVal(0, 248), Extract(oft + 7, oft, s1))
  File "/usr/local/lib/python3.5/dist-packages/z3/z3.py", line 3715, in Extract
    _z3_assert(is_bv(a), "Third argument must be a Z3 Bitvector expression")
  File "/usr/local/lib/python3.5/dist-packages/z3/z3.py", line 91, in _z3_assert
    raise Z3Exception(msg)
z3.z3types.Z3Exception: Third argument must be a Z3 Bitvector expression
```

**Comment by JoranHonig** [comment]
Hi @suhabe, I have a branch which should fix your problem. https://github.com/JoranHonig/mythril/tree/bugfix/272
Does that work for you?

**Comment by b-mueller** [comment]
Same here:

```
$ myth -xia 0xff8f2519ff90c844f41a79c50577d2f528849421
(...)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 395, in _sym_exec
    result = Concat(BitVecVal(0, 248), Extract(oft + 7, oft, s1))
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/z3/z3.py", line 3715, in Extract
    _z3_assert(is_bv(a), "Third argument must be a Z3 Bitvector expression")
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/z3/z3.py", line 91, in _z3_assert
    raise Z3Exception(msg)
z3.z3types.Z3Exception: Third argument must be a Z3 Bitvector expression
```

**Comment by b-mueller** [comment]
With #283 applied I get a different error:

```
$ $MYTH -xia 0xff8f2519ff90c844f41a79c50577d2f528849421 
Traceback (most recent call last):
  File "/Users/bernhardmueller/Projects/mythril/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/Users/bernhardmueller/Projects/mythril/mythril/interfaces/cli.py", line 202, in main
    max_depth=args.max_depth)
  File "/Users/bernhardmueller/Projects/mythril/mythril/mythril.py", line 323, in fire_lasers
    max_depth=max_depth)
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/symbolic.py", line 22, in __init__
    self.laser.sym_exec(address)
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/svm.py", line 265, in sym_exec
    node = self._sym_exec(gblState)
(...)
    new_node = self._sym_exec(new_gblState)
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/svm.py", line 392, in _sym_exec
    s1 = BitVecVal(s1, 256)
  File "/Users/bernhardmueller/.pyenv/versions/mythril/lib/python3.6/site-packages/z3/z3.py", line 3605, in BitVecVal
    return BitVecNumRef(Z3_mk_numeral(ctx.ref(), _to_int_str(val), BitVecSort(bv, ctx).ast), ctx)
  File "/Users/bernhardmueller/.pyenv/versions/mythril/lib/python3.6/site-packages/z3/z3.py", line 2797, in _to_int_str
    _z3_assert(False, "Python value cannot be used as a Z3 integer")
  File "/Users/bernhardmueller/.pyenv/versions/mythril/lib/python3.6/site-packages/z3/z3.py", line 91, in _z3_assert
    raise Z3Exception(msg)
z3.z3types.Z3Exception: Python value cannot be used as a Z3 integer
```

**Comment by JoranHonig** [comment]
Oh, my bad I made a mistake should be fixed now

**Comment by b-mueller** [comment]
#284 fixed the issue for me.

**Comment by JoranHonig** [comment]
@suhabe, can you confirm that the pr fixed the issue for your contract?

**Comment by JoranHonig** [comment]
Closing this for now, we can reopen if necessary
