### ISSUE TITLE
Assertion error in integer overflow check

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#285]
**Describe the bug**
Integer overflow analysis terminates with an `AssertionError` in some cases.

**To Reproduce**

```
$ $MYTH -xia 0xff8f2519ff90c844f41a79c50577d2f528849421 
Traceback (most recent call last):
  File "/Users/bernhardmueller/Projects/mythril/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/Users/bernhardmueller/Projects/mythril/mythril/interfaces/cli.py", line 202, in main
    max_depth=args.max_depth)
  File "/Users/bernhardmueller/Projects/mythril/mythril/mythril.py", line 325, in fire_lasers
    issues = fire_lasers(sym, modules)
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/security.py", line 20, in fire_lasers
    issues += module.execute(statespace)
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/modules/integer.py", line 34, in execute
    issues += _check_integer_overflow(statespace, state, node)
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/modules/integer.py", line 84, in _check_integer_overflow
    if not _verify_integer_overflow(statespace, node, expr, state, model, constraint, op0, op1):
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/modules/integer.py", line 103, in _verify_integer_overflow
    interesting_usages = _search_children(statespace, node, expr, constraint=[constraint], index=node.states.index(state))
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/modules/integer.py", line 234, in _search_children
    taint_result = TaintRunner.execute(statespace, node, state, initial_stack=taint_stack)
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/taint_analysis.py", line 106, in execute
    records = TaintRunner.execute_node(node, record, index)
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/taint_analysis.py", line 126, in execute_node
    records.append(TaintRunner.execute_state(records[-1], current_state))
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/taint_analysis.py", line 131, in execute_state
    assert len(state.mstate.stack) == len(record.stack)
AssertionError
```

**Comment by norhh** [comment]
It is related to #286 . By using the latest version after the commit this was working fine.
