### ISSUE TITLE
Stack assertion error when running on -l flag

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril#309]
**Describe the bug**
Integer overflow analysis terminates with assertion error when run on dynamic link.Problem may be in some 'CALL' related areas as not using -l won't result in this problem

**To Reproduce**
steps to reproduce the behavior.
```
>python3 ./myth -xila 0x869ed845F8D4B436fFE778ADC0E9ab253E53f0F2
Traceback (most recent call last):
  File "./myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/home/nikhil/MYTHRIL/mythril/mythril/interfaces/cli.py", line 198, in main
    max_depth=args.max_depth)
  File "/home/nikhil/MYTHRIL/mythril/mythril/mythril.py", line 345, in fire_lasers
    issues = fire_lasers(sym, modules)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/security.py", line 20, in fire_lasers
    issues += module.execute(statespace)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/modules/integer.py", line 34, in execute
    issues += _check_integer_overflow(statespace, state, node)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/modules/integer.py", line 84, in _check_integer_overflow
    if not _verify_integer_overflow(statespace, node, expr, state, model, constraint, op0, op1):
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/modules/integer.py", line 103, in _verify_integer_overflow
    interesting_usages = _search_children(statespace, node, expr, constraint=[constraint], index=node.states.index(state))
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/modules/integer.py", line 234, in _search_children
    taint_result = TaintRunner.execute(statespace, node, state, initial_stack=taint_stack)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/taint_analysis.py", line 106, in execute
    records = TaintRunner.execute_node(node, record, index)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/taint_analysis.py", line 126, in execute_node
    records.append(TaintRunner.execute_state(records[-1], current_state))
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/taint_analysis.py", line 131, in execute_state
    assert len(state.mstate.stack) == len(record.stack)
AssertionError
```

**Expected behavior**
There should not be an assertion error

**Desktop (please complete the following information):**
Ubuntu-17.10

**Comment by norhh** [comment]
thanks to the worklist we have a simpler error to deal with.

```
Traceback (most recent call last):
  File "./myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/Users/nparasaram/mythril/mythril/mythril/interfaces/cli.py", line 198, in main
    max_depth=args.max_depth)
  File "/Users/nparasaram/mythril/mythril/mythril/mythril.py", line 343, in fire_lasers
    max_depth=max_depth)
  File "/Users/nparasaram/mythril/mythril/mythril/analysis/symbolic.py", line 22, in __init__
    self.laser.sym_exec(address)
  File "/Users/nparasaram/mythril/mythril/mythril/laser/ethereum/svm.py", line 61, in sym_exec
    self._sym_exec()
  File "/Users/nparasaram/mythril/mythril/mythril/laser/ethereum/svm.py", line 75, in _sym_exec
    new_states, op_code = self.execute_state(global_state)
  File "/Users/nparasaram/mythril/mythril/mythril/laser/ethereum/svm.py", line 88, in execute_state
    return Instruction(op_code, self.dynamic_loader).evaluate(global_state), op_code
  File "/Users/nparasaram/mythril/mythril/mythril/laser/ethereum/instructions.py", line 69, in evaluate
    return instruction_mutator(global_state)
  File "/Users/nparasaram/mythril/mythril/mythril/laser/ethereum/instructions.py", line 34, in wrapper
    new_global_states = func(self, global_state_copy)
  File "/Users/nparasaram/mythril/mythril/mythril/laser/ethereum/instructions.py", line 915, in call_
    calldata_type=call_data_type)
  File "/Users/nparasaram/mythril/mythril/mythril/laser/ethereum/state.py", line 61, in __init__
    self.address = BitVecVal(int(active_account.address, 16), 256)
AttributeError: 'NoneType' object has no attribute 'address'

```

**Comment by b-mueller** [comment]
Same for this contracts:

```
$ myth -xila 0x902d03103A59d9E855d2508Bc7dc51bbe1FA5053
Traceback (most recent call last):
  File "/Users/bernhardmueller/.pyenv/versions/mythril/bin/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 198, in main
    max_depth=args.max_depth)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/mythril.py", line 344, in fire_lasers
    issues = fire_lasers(sym, modules)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/analysis/security.py", line 20, in fire_lasers
    issues += module.execute(statespace)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/analysis/modules/integer.py", line 34, in execute
    issues += _check_integer_overflow(statespace, state, node)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/analysis/modules/integer.py", line 84, in _check_integer_overflow
    if not _verify_integer_overflow(statespace, node, expr, state, model, constraint, op0, op1):
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/analysis/modules/integer.py", line 103, in _verify_integer_overflow
    interesting_usages = _search_children(statespace, node, expr, constraint=[constraint], index=node.states.index(state))
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/analysis/modules/integer.py", line 234, in _search_children
    taint_result = TaintRunner.execute(statespace, node, state, initial_stack=taint_stack)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/laser/ethereum/taint_analysis.py", line 106, in execute
    records = TaintRunner.execute_node(node, record, index)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/laser/ethereum/taint_analysis.py", line 126, in execute_node
    records.append(TaintRunner.execute_state(records[-1], current_state))
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/laser/ethereum/taint_analysis.py", line 131, in execute_state
    assert len(state.mstate.stack) == len(record.stack)
AssertionError
```
