### ISSUE TITLE
Stack Underflow Exception is thrown for some contracts.

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril#314]
**Describe the bug**
Stack Underflow Exception is thrown for some contracts.

**To Reproduce**
```
>python3 myth -xila 0x47d4cc3d331525976553baff7c9e4d410087804a

Traceback (most recent call last):
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/instructions.py", line 100, in pop_
    global_state.mstate.stack.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/home/nikhil/MYTHRIL/mythril/mythril/interfaces/cli.py", line 198, in main
    max_depth=args.max_depth)
  File "/home/nikhil/MYTHRIL/mythril/mythril/mythril.py", line 343, in fire_lasers
    max_depth=max_depth)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/symbolic.py", line 22, in __init__
    self.laser.sym_exec(address)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/svm.py", line 63, in sym_exec
    self._sym_exec()
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/svm.py", line 71, in _sym_exec
    new_states, op_code = self.execute_state(global_state)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/svm.py", line 84, in execute_state
    return Instruction(op_code, self.dynamic_loader).evaluate(global_state), op_code
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/instructions.py", line 69, in evaluate
    return instruction_mutator(global_state)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/instructions.py", line 34, in wrapper
    new_global_states = func(self, global_state_copy)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/instructions.py", line 102, in pop_
    raise StackUnderflowException()
mythril.laser.ethereum.instructions.StackUnderflowException

```

**Expected behavior**
It should execute properly

**Desktop (please complete the following information):**
 - Ubuntu
 - 17.10

**Comment by norhh** [comment]
This can also be a duplicate of #309

**Comment by JoranHonig** [comment]
The stack underflow exception is new, I added this because we don't want to fail silently in case this happens (previous behaviour). This is probably caused by a bug in one of the instruction implementations

**Comment by norhh** [comment]
Oops! i meant this exception should not be reached
