### ISSUE TITLE
ImportError: cannot import name 'ALL_BYTES'

### ISSUE THREAD

**Issue by suhabe** [ConsenSys/mythril#319]
My mythril installation is crashing due to this import error on Ubuntu 16.04, Python 3.5.2:

```
vagrant@vagrant:~/host$ pip3 search mythril
mythril (0.18.6)  - Security analysis tool for Ethereum smart contracts
  INSTALLED: 0.18.6 (latest)

vagrant@vagrant:~/host$ myth -x contracts/Blacklistable.sol 
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 6, in <module>
    import mythril.interfaces.cli
  File "/usr/local/lib/python3.5/dist-packages/mythril/interfaces/cli.py", line 16, in <module>
    from mythril.mythril import Mythril
  File "/usr/local/lib/python3.5/dist-packages/mythril/mythril.py", line 13, in <module>
    from ethereum import utils
  File "/usr/local/lib/python3.5/dist-packages/ethereum/__init__.py", line 11, in <module>
    from . import slogging  # noqa
  File "/usr/local/lib/python3.5/dist-packages/ethereum/slogging.py", line 6, in <module>
    from ethereum.utils import bcolors, is_numeric
  File "/usr/local/lib/python3.5/dist-packages/ethereum/utils.py", line 15, in <module>
    from rlp.utils import ALL_BYTES
ImportError: cannot import name 'ALL_BYTES'
```

**Comment by norhh** [comment]
hi @suhabe , can you try doing pip install ethereum==2.3.1 and then retrying it again

**Comment by suhabe** [comment]
Looks like that fixed it.
