### ISSUE TITLE
Z3 parser error exception is thrown

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril#320]
**Describe the bug**

**To Reproduce**
```
>python3 ./myth -xila 0x2b7932875085330b421b0af9f6b237bfe02f5e5f

Traceback (most recent call last):
  File "./myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/home/nikhil/MYTHRIL/mythril/mythril/interfaces/cli.py", line 198, in main
    max_depth=args.max_depth)
  File "/home/nikhil/MYTHRIL/mythril/mythril/mythril.py", line 343, in fire_lasers
    max_depth=max_depth)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/symbolic.py", line 22, in __init__
    self.laser.sym_exec(address)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/svm.py", line 63, in sym_exec
    self._sym_exec()
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/svm.py", line 71, in _sym_exec
    new_states, op_code = self.execute_state(global_state)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/svm.py", line 84, in execute_state
    return Instruction(op_code, self.dynamic_loader).evaluate(global_state), op_code
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/instructions.py", line 69, in evaluate
    return instruction_mutator(global_state)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/instructions.py", line 34, in wrapper
    new_global_states = func(self, global_state_copy)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/instructions.py", line 115, in and_
    stack.append(op1 & op2)
  File "/home/nikhil/.local/lib/python3.6/site-packages/z3/z3.py", line 3204, in __and__
    a, b = _coerce_exprs(self, other)
  File "/home/nikhil/.local/lib/python3.6/site-packages/z3/z3.py", line 1018, in _coerce_exprs
    b = s.cast(b)
  File "/home/nikhil/.local/lib/python3.6/site-packages/z3/z3.py", line 3065, in cast
    return BitVecVal(val, self)
  File "/home/nikhil/.local/lib/python3.6/site-packages/z3/z3.py", line 3602, in BitVecVal
    return BitVecNumRef(Z3_mk_numeral(ctx.ref(), _to_int_str(val), bv.ast), ctx)
  File "/home/nikhil/.local/lib/python3.6/site-packages/z3/z3core.py", line 2227, in Z3_mk_numeral
    raise Z3Exception(lib().Z3_get_error_msg(a0, err))
z3.z3types.Z3Exception: b'parser error'
```

**Expected behavior**
The code should be executed properly

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 17.10

**Comment by JoranHonig** [comment]
@norhh This is caused by the way we currently do native contracts. If the sha256 function encounters a TypeError, it will return sha256_data. Which will get put on the stack as ['s', 'h' ....].
Instead of putting concrete values in memory just add unconstrained symbols. I think that is a good approach in this case
