### ISSUE TITLE
Attribute Error is being raised for some contracts

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril#321]
**Describe the bug**
Attribute error is being thrown for some some contracts.

**To Reproduce**
```
>python3 ./myth -xila 0xcba65975b1c66586bfe7910f32377e0ee55f783e
Traceback (most recent call last):
  File "./myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/home/nikhil/MYTHRIL/mythril/mythril/interfaces/cli.py", line 198, in main
    max_depth=args.max_depth)
  File "/home/nikhil/MYTHRIL/mythril/mythril/mythril.py", line 343, in fire_lasers
    max_depth=max_depth)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/symbolic.py", line 22, in __init__
    self.laser.sym_exec(address)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/svm.py", line 63, in sym_exec
    self._sym_exec()
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/svm.py", line 76, in _sym_exec
    self.manage_cfg(op_code, new_states)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/svm.py", line 97, in manage_cfg
    self._new_node_state(state, JumpType.CALL)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/svm.py", line 111, in _new_node_state
    self.edges.append(Edge(old_node.uid, new_node.uid, edge_type=edge_type, condition=condition))
AttributeError: 'MachineState' object has no attribute 'uid'
```
**Expected behavior**
The contract should execute properly. Looks like my luck is bad(in a way good as bugs are being found) as only i am encountering a lot of issues.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 17.10

**Comment by norhh** [comment]
Probably because this line(and few others) is sending MachineState as node as the third argument as node for GlobalState where node should have uid but machineState doesn't have one.
```
new_global_state = GlobalState(global_state.accounts, callee_environment, MachineState(gas))
```

**Comment by JoranHonig** [comment]
This problem has been fixed in the pr. However there are still some problems, but those should maybe be moved to a new issue
