### ISSUE TITLE
ImportError: cannot import name 'ALL_BYTES'

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#327]
**Describe the bug**
After updating packages with `pip install -U`, the myth command line tool exits with an error.

```
(mythril) cerebral-cortex:~ bernhardmueller$ myth
Traceback (most recent call last):
  File "/Users/bernhardmueller/.pyenv/versions/mythril/bin/myth", line 6, in <module>
    import mythril.interfaces.cli
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 16, in <module>
    from mythril.mythril import Mythril
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/mythril.py", line 13, in <module>
    from ethereum import utils
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/ethereum/__init__.py", line 11, in <module>
    from . import slogging  # noqa
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/ethereum/slogging.py", line 6, in <module>
    from ethereum.utils import bcolors, is_numeric
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/ethereum/utils.py", line 15, in <module>
    from rlp.utils import ALL_BYTES
ImportError: cannot import name 'ALL_BYTES'
```

Most likely there's an incompatibility with the newest Ethereum package.

**To Reproduce**

Update to Mythril 0.18.6 and Ethereum 2.3.2.

**Desktop (please complete the following information):**
 - OS: Mac OS High Sierra

**Additional context**

Installed packages:

```
$ pip freeze
asn1crypto==0.24.0
atomicwrites==1.1.5
attrdict==2.0.0
attrs==18.1.0
BTrees==4.5.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
coincurve==8.0.0
configparser==3.5.0
coverage==4.5.1
cytoolz==0.9.0.1
dictionaries==0.0.1
docopt==0.6.2
eth-abi==1.1.1
eth-account==0.2.3
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-tester==0.1.0b28
eth-utils==1.0.3
ethereum==2.3.2
flake8==3.5.0
Flask==1.0.2
future==0.16.0
grip==4.5.2
hexbytes==0.1.0
idna==2.7
itsdangerous==0.24
Jinja2==2.10
laser-ethereum==0.17.12
Markdown==2.6.11
MarkupSafe==1.0
mccabe==0.6.1
mock==2.0.0
mockprocess==0.2
more-itertools==4.2.0
mythril==0.18.6
parsimonious==0.8.0
path-and-address==2.0.1
pbkdf2==1.3
pbr==4.1.0
persistent==4.2.4.2
pluggy==0.6.0
plyvel==1.0.4
py==1.5.3
py-ecc==1.4.3
py-flags==1.1.2
py-solc==3.1.0
pycodestyle==2.3.1
pycparser==2.18
pycryptodome==3.6.3
pyethash==0.1.27
pyflakes==1.6.0
Pygments==2.2.0
pysha3==1.0.2
pytest==3.6.0
pytest-cov==2.5.1
pytest-mock==1.10.0
PyYAML==3.13
repoze.lru==0.7
requests==2.19.1
rlp==0.6.0
scrypt==0.8.6
semantic-version==2.6.0
six==1.11.0
toolz==0.9.0
transaction==2.2.1
urllib3==1.23
Werkzeug==0.14.1
z3-solver==4.5.1.0.post2
zc.lockfile==1.3.0
ZConfig==3.2.0
ZODB==5.4.0
zodbpickle==1.0.1
zope.interface==4.5.0
```

**Comment by XertroV** [comment]
Yup; note that you've got ethereum==2.3.2 installed to, but current requirements.txt specifies 2.3.1. I've manually `pip3 install ethereum==2.3.1` on my machine (was getting same error as you above before), and now getting 

```
    from ethereum.utils import bcolors, is_numeric
  File "/usr/local/lib/python3.6/site-packages/ethereum/utils.py", line 13, in <module>
    from rlp.utils import decode_hex, encode_hex, ascii_chr, str_to_bytes
ImportError: cannot import name 'decode_hex'
```

So yeah definitely seems to be an issue with `rlp` version.
