### ISSUE TITLE
Pip installation error on Ubuntu

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#371]
**Describe the bug**
The upgrade to mythril 0.18.10 fails on Ubuntu with the following error:

```
$ pip3 install mythril -U
Collecting mythril
  Using cached https://files.pythonhosted.org/packages/ac/c4/a258e1472f29e0866d6a82f320df17b69e1b45e552e7c7cf46194a566e70/mythril-0.18.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qa5hgytb/mythril/setup.py", line 15, in <module>
        exec(open(version_path, 'r').read())
    TypeError: invalid file: PosixPath('/tmp/pip-install-qa5hgytb/mythril/mythril/version.py')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qa5hgytb/mythril/
```

Same error when running `setup.py` manually:

```
ubuntu:~/myth/mythril-0.18.10$ python setup.py 
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    exec(open(version_path, 'r').read())
TypeError: invalid file: PosixPath('/home/ubuntu/myth/mythril-0.18.10/mythril/version.py')
```

The file mentioned in the error message exists & is readable though:

```
$ cat /home/ubuntu/myth/mythril-0.18.10/mythril/version.py
# This file is suitable for sourcing inside POSIX shell, e.g. bash as
# well as for importing into Python
VERSION="v0.18.10"  # NOQA
```

On my Mac, it worked without issues.

@rocky, this might have something to do with the latest changes in #351?

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Comment by rocky** [comment]
A quick workaround until I have time fully understand and fix is 
```
  diff --git a/setup.py b/setup.py
index 68bd8e9..18dc9ce 100755
--- a/setup.py
+++ b/setup.py
@@ -6,13 +6,13 @@ import os
 
 # To make lint checkers happy we set VERSION here, but
 # it is redefined by the exec below
-VERSION = None
+VERSION = "v0.18.9"
 
 # Package version (vX.Y.Z). It must match git tag being used for CircleCI
 # deployment; otherwise the build will failed.

```diff 
 version_path = (Path(__file__).parent / 'mythril' / 'version.py').absolute()
-exec(open(version_path, 'r').read())
+#exec(open(version_path, 'r').read())
 
 class VerifyVersionCommand(install):
     """Custom command to verify that the git tag matches our version"""
```

And also curious is that I use Ubuntu and recently pullled mythril from master and that worked. Whatever. Will track this down and add a test which I guess I should have done initially.

**Comment by rocky** [comment]
This worked when I just tried it on Ubuntu bionic:

```
$ pip3 install mythril -U 
Collecting mythril
  Downloading https://files.pythonhosted.org/packages/ac/c4/a258e1472f29e0866d6a82f320df17b69e1b45e552e7c7cf46194a566e70/mythril-0.18.10.tar.gz (64kB)
    100% |████████████████████████████████| 71kB 2.3MB/s 
Requirement not upgraded as not directly required: ethereum>=2.3.2 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (2.3.2)
Requirement not upgraded as not directly required: z3-solver>=4.5 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (4.5.1.0.post2)
Requirement not upgraded as not directly required: requests in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (2.19.1)
Requirement not upgraded as not directly required: py-solc in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (3.1.0)
Requirement not upgraded as not directly required: plyvel in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (1.0.5)
Requirement not upgraded as not directly required: eth_abi>=1.0.0 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (1.1.1)
Requirement not upgraded as not directly required: eth-utils>=1.0.1 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (1.0.3)
Requirement not upgraded as not directly required: eth-account>=0.1.0a2 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (0.2.3)
Requirement not upgraded as not directly required: eth-hash>=0.1.0 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (0.1.4)
Requirement not upgraded as not directly required: eth-keyfile>=0.5.1 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (0.5.1)
Requirement not upgraded as not directly required: eth-keys>=0.2.0b3 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (0.2.0b3)
Requirement not upgraded as not directly required: eth-rlp>=0.1.0 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (0.1.2)
Requirement not upgraded as not directly required: eth-tester>=0.1.0b21 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (0.1.0b28)
Requirement not upgraded as not directly required: coverage in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (4.5.1)
Requirement not upgraded as not directly required: jinja2>=2.9 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (2.10)
Requirement not upgraded as not directly required: rlp>=1.0.1 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (1.0.1)
Requirement not upgraded as not directly required: transaction>=2.2.1 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (2.2.1)
Requirement not upgraded as not directly required: py-flags in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (1.1.2)
Requirement not upgraded as not directly required: mock in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (2.0.0)
Requirement not upgraded as not directly required: configparser>=3.5.0 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (3.5.0)
Requirement not upgraded as not directly required: persistent>=4.2.0 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mythril) (4.2.4.2)
Requirement not upgraded as not directly required: PyYAML in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from ethereum>=2.3.2->mythril) (3.13)
Requirement not upgraded as not directly required: future in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from ethereum>=2.3.2->mythril) (0.16.0)
Requirement not upgraded as not directly required: scrypt in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from ethereum>=2.3.2->mythril) (0.8.6)
Requirement not upgraded as not directly required: pysha3>=1.0.1 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from ethereum>=2.3.2->mythril) (1.0.2)
Requirement not upgraded as not directly required: pycryptodome>=3.4.7 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from ethereum>=2.3.2->mythril) (3.6.4)
Requirement not upgraded as not directly required: py-ecc in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from ethereum>=2.3.2->mythril) (1.4.3)
Requirement not upgraded as not directly required: pyethash<1.0.0,>=0.1.27 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from ethereum>=2.3.2->mythril) (0.1.27)
Requirement not upgraded as not directly required: coincurve>=7.0.0 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from ethereum>=2.3.2->mythril) (8.0.0)
Requirement not upgraded as not directly required: repoze.lru in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from ethereum>=2.3.2->mythril) (0.7)
Requirement not upgraded as not directly required: pbkdf2 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from ethereum>=2.3.2->mythril) (1.3)
Requirement not upgraded as not directly required: chardet<3.1.0,>=3.0.2 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from requests->mythril) (3.0.4)
Requirement not upgraded as not directly required: urllib3<1.24,>=1.21.1 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from requests->mythril) (1.23)
Requirement not upgraded as not directly required: certifi>=2017.4.17 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from requests->mythril) (2018.4.16)
Requirement not upgraded as not directly required: idna<2.8,>=2.5 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from requests->mythril) (2.7)
Requirement not upgraded as not directly required: semantic-version>=2.6.0 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from py-solc->mythril) (2.6.0)
Requirement not upgraded as not directly required: parsimonious==0.8.0 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from eth_abi>=1.0.0->mythril) (0.8.0)
Requirement not upgraded as not directly required: cytoolz<1.0.0,>=0.8.2 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from eth-utils>=1.0.1->mythril) (0.9.0.1)
Requirement not upgraded as not directly required: attrdict<3,>=2.0.0 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from eth-account>=0.1.0a2->mythril) (2.0.0)
Requirement not upgraded as not directly required: hexbytes<1,>=0.1.0 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from eth-account>=0.1.0a2->mythril) (0.1.0)
Requirement not upgraded as not directly required: MarkupSafe>=0.23 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from jinja2>=2.9->mythril) (1.0)
Requirement not upgraded as not directly required: zope.interface in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from transaction>=2.2.1->mythril) (4.5.0)
Requirement not upgraded as not directly required: dictionaries==0.0.1 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from py-flags->mythril) (0.0.1)
Requirement not upgraded as not directly required: pbr>=0.11 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mock->mythril) (4.1.1)
Requirement not upgraded as not directly required: six>=1.9 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from mock->mythril) (1.11.0)
Requirement not upgraded as not directly required: asn1crypto in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from coincurve>=7.0.0->ethereum>=2.3.2->mythril) (0.24.0)
Requirement not upgraded as not directly required: cffi>=1.3.0 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from coincurve>=7.0.0->ethereum>=2.3.2->mythril) (1.11.5)
Requirement not upgraded as not directly required: toolz>=0.8.0 in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from cytoolz<1.0.0,>=0.8.2->eth-utils>=1.0.1->mythril) (0.9.0)
Requirement not upgraded as not directly required: setuptools in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from zope.interface->transaction>=2.2.1->mythril) (39.0.1)
Requirement not upgraded as not directly required: pycparser in /home/rocky/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from cffi>=1.3.0->coincurve>=7.0.0->ethereum>=2.3.2->mythril) (2.18)
Building wheels for collected packages: mythril
  Running setup.py bdist_wheel for mythril ... done
  Stored in directory: /home/rocky/.cache/pip/wheels/23/c8/46/1a694efdffa5a626eae1d7a6454af3b3ac2d9a03c648a6f85a
Successfully built mythril
Installing collected packages: mythril
  Found existing installation: mythril 0.18.9
    Uninstalling mythril-0.18.9:
      Successfully uninstalled mythril-0.18.9
Successfully installed mythril-0.18.10
```
Will investigate further though...

**Comment by rocky** [comment]
Ok. I see what's up. I bet you ran this on Python version 3.5.x (or more precisely < Python 3.6) where `open()` doesn't accept a Path type.

One simple fix is to change: 

```
exec(open(version_path, 'r').read())
```
to: 
```
exec(open(str(version_path), 'r').read())
```

but perhaps this error has some blessings in disguise. (Or at least I hope you take it that way :-) )

Previously when I was checking to see if this worked for Pypy, I recall reading that Mythril needs 3.6 or later. Is 3.5 acceptable? 

Our setup.py suggest yes [here](https://github.com/ConsenSys/mythril/blob/master/setup.py#L51).

However it also says [here](https://github.com/ConsenSys/mythril/blob/master/setup.py#L297-L302) that Python 2x, 2.7, 3x, .3, and 3.4 are allowed in addition. And no mention of 3.6 or 3.7. 

So which versions do we support? 

After understanding that, I would be happy to correct all of the parts of setup.py to make them consistent. 

Thanks.

**Comment by johnbender** [comment]
@rocky 

Your post is correct from what I can tell. 0.18.9 installs fine with the default ubuntu install of 3.5.2. I installed without a version specification two days ago and ran into this issue while installing today today.

Thanks for posting @b-mueller.

**Comment by b-mueller** [comment]
We never clearly defined this, but I think it makes sense to support both 3.5 and 3.6 to make things easy for Ubuntu users? If we only need the `str` fix to do it.

**Comment by johnbender** [comment]
@rocky 

No worries! I ran the following without issue:

```
pip3 install git+https://github.com/ConsenSys/mythril.git@332653d7c1800cf8af9cb1fdd2cbb14ee17c9fd5
```

**Comment by stuardo3191** [comment]
this is what i got on my mac when i tried to install it 



-I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c scrypt-1.2.1/libcperciva/crypto/crypto_aes.c -o build/temp.macosx-10.9-x86_64-3.7/scrypt-1.2.1/libcperciva/crypto/crypto_aes.o
    scrypt-1.2.1/libcperciva/crypto/crypto_aes.c:6:10: fatal error: 'openssl/aes.h' file not found
    #include <openssl/aes.h>
             ^~~~~~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/w7/y8bs9vj17fj26py3ylyrz7s40000gn/T/pip-install-yaw0bz9l/scrypt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/w7/y8bs9vj17fj26py3ylyrz7s40000gn/T/pip-record-koxecbym/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/w7/y8bs9vj17fj26py3ylyrz7s40000gn/T/pip-install-yaw0bz9l/scrypt/

**Comment by norhh** [comment]
hi @stuardo3191 , is the problem with this(v 0.18.10) version ?(did you successfully install mythril before?)

**Comment by stuardo3191** [comment]
not yet but I'm going to right now

**Comment by stuardo3191** [comment]
okay so i tried it  om my mac   including the older versions and non of them were successfully installed

**Comment by norhh** [comment]
can you try doing ```brew install openssl``` or something like that which installs openssl and then retry installing it?

**Comment by JoranHonig** [comment]
Closing this as the original issue seems to be fixed. Thanks @johnbender for confirming. 
Not sure if the mac os thing has been solved, if not feel free to open another issue :smile: 

@JonHaas Thanks for the info! :+1: Hope that helped with @stuardo3191's issue. We're planning on supporting 3.7 as well in the future
