### ISSUE TITLE
Assertion error when run on some contracts with -l

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril#397]
## Description

Specifically happens when -l is used.

## How to Reproduce
```console
$ myth -xila 0x8f46325b00536da3714eb8646b10ed653d5b17f2
Traceback (most recent call last):
  File "./myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/home/nikhil/MYTHRIL/mythril/mythril/interfaces/cli.py", line 209, in main
    max_depth=args.max_depth, execution_timeout=args.execution_timeout)
  File "/home/nikhil/MYTHRIL/mythril/mythril/mythril.py", line 382, in fire_lasers
    issues = fire_lasers(sym, modules)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/security.py", line 20, in fire_lasers
    issues += module.execute(statespace)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/modules/integer.py", line 34, in execute
    issues += _check_integer_overflow(statespace, state, node)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/modules/integer.py", line 84, in _check_integer_overflow
    if not _verify_integer_overflow(statespace, node, expr, state, model, constraint, op0, op1):
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/modules/integer.py", line 103, in _verify_integer_overflow
    interesting_usages = _search_children(statespace, node, expr, constraint=[constraint], index=node.states.index(state))
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/modules/integer.py", line 233, in _search_children
    taint_result = TaintRunner.execute(statespace, node, state, initial_stack=taint_stack)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/taint_analysis.py", line 107, in execute
    records = TaintRunner.execute_node(node, record, index)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/taint_analysis.py", line 139, in execute_node
    records.append(TaintRunner.execute_state(records[-1], current_state))
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/taint_analysis.py", line 144, in execute_state
    assert len(state.mstate.stack) == len(record.stack)
AssertionError

...
$
```
## Expected behavior

Should execute properly

## Environment

- Mythril version: latest master
- Solidity compiler and version: 0.4.25-develop.2018.6.21+commit.32f2db78.Linux.g++
- Python version: 3.6
- OS: Ubuntu
- OS Version: 17.10

## Additional Info
the error seems to occur when we started copying global state's accounts in jumpi.

**Comment by JoranHonig** [comment]
fixed with #404
