### ISSUE TITLE
Issue running --init-db, NoneType Object is not scriptable

### ISSUE THREAD

**Issue by postables** [ConsenSys/mythril#42]
When trying to initialize the contract database I receive the following error.
Note this was installed by cloning the master branch of this repo, and running `sudo python3.6 setup.py install`

```
 myth --init-db --infura-rinkeby
Starting synchronization from latest block: 1560817
Traceback (most recent call last):
  File "/usr/bin/myth", line 4, in <module>
    __import__('pkg_resources').run_script('mythril==0.8.27', 'myth')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.6/site-packages/mythril-0.8.27-py3.6.egg/EGG-INFO/scripts/myth", line 168, in <module>
    contract_storage.initialize(eth, args.sync_all)
  File "/usr/lib/python3.6/site-packages/mythril-0.8.27-py3.6.egg/mythril/ether/contractstorage.py", line 67, in initialize
    for tx in block['transactions']:
TypeError: 'NoneType' object is not subscriptable

```

**Comment by b-mueller** [comment]
Hi @postables! Seems like the `eth_getBlockByNumber` RPC call is currently returning empty blocks. Maybe there's an issue with INFURA. I'll look into it.

**Comment by b-mueller** [comment]
It appears that there is some delay before the latest block is made available by INFURA. I added a workaround in master and it should work now:

```
$ ./myth --init-db --infura-rinkeby --sync-all
Starting synchronization from latest block: 1572500
```

Not however that this is very, very slow, I'd recommend doing this with a local node.
