### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#427]
## Description

Mythril crashes with an IndexError for the following contract:

```
$ $ myth -xia 0xade468790ec609db3403bd728b2bfc751f4ac7dc
Traceback (most recent call last):
  File "/Users/bernhardmueller/.pyenv/versions/mythril/bin/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 206, in main
    max_depth=args.max_depth, execution_timeout=args.execution_timeout)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/mythril.py", line 380, in fire_lasers
    max_depth=max_depth, execution_timeout=execution_timeout)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/analysis/symbolic.py", line 30, in __init__
    self.laser.sym_exec(address)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 61, in sym_exec
    transaction.run(self.open_states, self)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/laser/ethereum/transaction.py", line 58, in run
    evm.exec()
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 83, in exec
    self.manage_cfg(op_code, new_states)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 109, in manage_cfg
    self._new_node_state(state, JumpType.CONDITIONAL, state.mstate.constraints[-1])
IndexError: list index out of range
```
## Environment

- Mythril version: v0.18.11
- Solidity compiler and version: 0.4.24+commit.e67f0147.Darwin.appleclang
- Python version: Python 3.6.3
- OS: High Sierra

**Comment by rocky** [comment]
Is this the same thing? 

```console
$ ./myth -x -dc 6060
0 PUSH1 0x60
$ ./myth -x -c 6060
Traceback (most recent call last):
  File "./myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/src/external-vcs/github/consensys/mythril/mythril/interfaces/cli.py", line 209, in main
    max_depth=args.max_depth, execution_timeout=args.execution_timeout)
  File "/src/external-vcs/github/consensys/mythril/mythril/mythril.py", line 379, in fire_lasers
    max_depth=max_depth, execution_timeout=execution_timeout)
  File "/src/external-vcs/github/consensys/mythril/mythril/analysis/symbolic.py", line 30, in __init__
    self.laser.sym_exec(address)
  File "/src/external-vcs/github/consensys/mythril/mythril/laser/ethereum/svm.py", line 65, in sym_exec
    self.execute_message_call(main_address)
  File "/src/external-vcs/github/consensys/mythril/mythril/laser/ethereum/svm.py", line 266, in execute_message_call
    self.exec()
  File "/src/external-vcs/github/consensys/mythril/mythril/laser/ethereum/svm.py", line 75, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/src/external-vcs/github/consensys/mythril/mythril/laser/ethereum/svm.py", line 87, in execute_state
    op_code = instructions[global_state.mstate.pc]['opcode']
IndexError: list index out of range
```

**Comment by JoranHonig** [comment]
@rocky No, in your case its actually your fault ;) (however we should fix the error that is generated in this case).
What happens in your case is the following:
push1 0x60 is executed, which means 0x60 is put on the stack and the pc is incremented.
Laser now tries to execute the next instruction (which isn't there) and has the index out of range error. I think in this case we should have something like an EvmRuntimeException with a message "Severe error: encountered an invalid program counter value"
