### ISSUE TITLE
Stack assertion error for Delegate call based contracts

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril#435]
## How to Reproduce
```console
$ ./myth --rpc infura-rinkeby -xla 0x002c39bf9e2144e8a96af3105d19ea127de08604
Traceback (most recent call last):
  File "./myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/home/nikhil/MYTHRIL/norhh/mythril/mythril/interfaces/cli.py", line 209, in main
    max_depth=args.max_depth, execution_timeout=args.execution_timeout)
  File "/home/nikhil/MYTHRIL/norhh/mythril/mythril/mythril.py", line 381, in fire_lasers
    issues = fire_lasers(sym, modules)
  File "/home/nikhil/MYTHRIL/norhh/mythril/mythril/analysis/security.py", line 20, in fire_lasers
    issues += module.execute(statespace)
  File "/home/nikhil/MYTHRIL/norhh/mythril/mythril/analysis/modules/integer.py", line 33, in execute
    issues += _check_integer_underflow(statespace, state, node)
  File "/home/nikhil/MYTHRIL/norhh/mythril/mythril/analysis/modules/integer.py", line 170, in _check_integer_underflow
    interesting_usages = _search_children(statespace, node, (op0 - op1), index=node.states.index(state))
  File "/home/nikhil/MYTHRIL/norhh/mythril/mythril/analysis/modules/integer.py", line 233, in _search_children
    taint_result = TaintRunner.execute(statespace, node, state, initial_stack=taint_stack)
  File "/home/nikhil/MYTHRIL/norhh/mythril/mythril/laser/ethereum/taint_analysis.py", line 107, in execute
    records = TaintRunner.execute_node(node, record, index)
  File "/home/nikhil/MYTHRIL/norhh/mythril/mythril/laser/ethereum/taint_analysis.py", line 139, in execute_node
    records.append(TaintRunner.execute_state(records[-1], current_state))
  File "/home/nikhil/MYTHRIL/norhh/mythril/mythril/laser/ethereum/taint_analysis.py", line 144, in execute_state
    assert len(state.mstate.stack) == len(record.stack)
AssertionError
...
$
```
## Environment
- Mythril version: latest master
- Python version: 3.6
- OS: Ubuntu
- OS Version 17.10

## Additional Environment or Context
It seems to be a problem with some Delegatecall contracts where delegatecall clears out the state stack whereas the taint record doesn't clear it's stack.

**Comment by shashank-srikant** [comment]
i see the same errors on some of the contracts when i run mythril in parallel. Although strangely, i'm unable to reproduce it when i run mythril on the contracts serially.

**Comment by norhh** [comment]
do the contracts have `DELEGATECALL` instruction in them? it can be checked with
 `myth -d <contract_name> |grep DELEGATE`

**Comment by shashank-srikant** [comment]
no, doesn't exist.
i'm running mythril on all the contracts that appear in this script - 
https://etherscan.io/address/0xf6da07a8ffb5683314715d8c7a1a5c952b4e74ca#code

here's a screenshot (which doesn't really help in debugging anything)
![untitled](https://user-images.githubusercontent.com/14936946/44196493-180c3c00-a10a-11e8-97a4-434f0ad661a8.png)

**Comment by norhh** [comment]
In that case can you mention the mythril commit(or version if it's directly taken from pip) which resulted in this error?

**Comment by shashank-srikant** [comment]
i'm working on the latest commit from github, which i pulled an hour ago.
```
>> myth --version
Mythril version v0.18.11
```

**Comment by norhh** [comment]
oops, that has some bug which we realized recently.Till then it might be a good idea to try the commit 657458bda31a868c54c8966a98b4b6a1ba841abd .

**Comment by shashank-srikant** [comment]
btw, i was incorrect in pointing out the file.
i am able to reproduce this issue (and the dump shown in the screenshot) with `myth -xo json filename` where `filename`  has the source https://etherscan.io/address/0xfffce2dc587badbd10b4fe17f0f5f293458f6793#code
