### ISSUE TITLE
Mythril crashes with Unicode error on docker

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril#479]
## Description

Mythrl docker image crashes with unicode error for [this](https://etherscan.io/address/0x39e8082b00c9f19ebf553e40feb7cf8459acc693#code) contract. may be related to #448 but in this case for docker it is crashing at a different location.

## How to Reproduce
```console
$ sudo docker run -v $(pwd):/tmp mythril/myth -x /tmp/crash.sol
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 4, in <module>
    __import__('pkg_resources').run_script('mythril==0.18.11', 'myth')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.11-py3.6.egg/EGG-INFO/scripts/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.11-py3.6.egg/mythril/interfaces/cli.py", line 212, in main
    print(outputs[args.outform])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 439-447: ordinal not in range(128)
...
$
```

## Expected behavior

It should not crash.

## Environment
Please modify for your setup

- Mythril version: 0.18.11
- Solidity compiler and version: `0.4.24`

**Comment by dmuhs** [comment]
Looking into this, the most recent Mythril container gives me a different `solc` version. Apart from that, I can reproduce the error with the container.
![screenshot from 2018-09-09 16-32-44](https://user-images.githubusercontent.com/5565837/45265624-1b1af380-b44e-11e8-9cb5-3cf94bc332d8.png)
Interestingly, I do not get the error running Mythril locally, even though I have the same dependencies installed. Execution just yields a warning and errors out shortly after.
```
WARNING:root:No contract was created during the execution of contract creation Increase the resources for creation execution (--max-depth or --create_timeout)
Traceback (most recent call last):
  File "./myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/home/spoons/diligence/mythril/mythril/interfaces/cli.py", line 218, in main
    create_timeout=args.create_timeout)
  File "/home/spoons/diligence/mythril/mythril/mythril.py", line 374, in fire_lasers
    issue.add_code_info(contract)
  File "/home/spoons/diligence/mythril/mythril/analysis/report.py", line 38, in add_code_info
    codeinfo = contract.get_source_info(self.address)
  File "/home/spoons/diligence/mythril/mythril/ether/soliditycontract.py", line 105, in get_source_info
    solidity_file = self.solidity_files[self.mappings[index].solidity_file_idx]
TypeError: list indices must be integers or slices, not NoneType
```

**Comment by norhh** [comment]
oops that wasn't the container's solc version, will update it

**Comment by norhh** [comment]
Also i think that TypeError was another error #446 .

**Comment by dmuhs** [comment]
PR is out. For reference, [this SO thread](https://stackoverflow.com/questions/25127673/how-to-print-utf-8-to-console-with-python-3-4-windows-8) explains everything in a little more detail.
