### ISSUE TITLE
Can't initialize contract class

### ISSUE THREAD

**Issue by infiBoy** [ConsenSys/mythril#496]
I'm doing my first steps in mythril. Here is the code I'm trying to run:

from mythril.ether.soliditycontract import SolidityContract
from mythril.laser.ethereum import svm
contract = SolidityContract("./examples/rubixi.sol", "Rubixi")

But I get the following error:
``
 Traceback (most recent call last):
  File "/home/username/PycharmProjects/untitled/p.py", line 4, in 
    contract = SolidityContract("./examples/rubixi.sol", "Rubixi")
  File "/home/username/.local/lib/python3.6/site-packages/mythril/ether/soliditycontract.py", line 99, in init
    super().init(code, creation_code, name=name)
  File "/home/username/.local/lib/python3.6/site-packages/mythril/ether/ethcontract.py", line 20, in init
    self.disassembly = Disassembly(self.code, enable_online_lookup=enable_online_lookup)
  File "/home/username/.local/lib/python3.6/site-packages/mythril/disassembler/disassembly.py", line 50, in init
    signatures.write()  # store resolved signatures (potentially resolved online)
  File "/home/username/.local/lib/python3.6/site-packages/mythril/support/signatures.py", line 129, in write
    self.signatures_file_lock.aquire()  # try to aquire it within the next 10s
  File "/home/username/.local/lib/python3.6/site-packages/mythril/support/signatures.py", line 40, in aquire
    self.lockfile.touch(mode=0o0000, exist_ok=False)  # touch the lockfile
  File "/usr/lib/python3.6/pathlib.py", line 1236, in touch
    fd = self._raw_open(flags, mode)
  File "/usr/lib/python3.6/pathlib.py", line 1044, in _raw_open
    return self._accessor.open(self, flags, mode)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/.mythril/signatures.json.lck'

``
I'm using fresh Ubuntu 18.04

**Comment by norhh** [comment]
Hi @infiBoy, thanks for the report, unfortunately there is a bug in mythril in the last release regarding the signatures file, so can you try using the master branch for this, that might do the work.

**Comment by infiBoy** [comment]
I tried to download the master branch and import it directly.
However, it still throw the same error.
Can you guide me more specifically?

**Comment by norhh** [comment]
hey @infiBoy, you don't have any problems currently with master right?, in that case i am closing this issue, If the problem persists then feel free to mention it here, we will reopen this issue and fix it :smile:
