### ISSUE TITLE
taint_analysis.py, line 144, assert len(state.mstate.stack) == len(record.stack)

### ISSUE THREAD

**Issue by iljah** [ConsenSys/mythril#508]
## Description
```
Traceback (most recent call last):
  File ".../.local/bin/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File ".../.local/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 206, in main
    max_depth=args.max_depth, execution_timeout=args.execution_timeout)
  File ".../.local/lib/python3.6/site-packages/mythril/mythril.py", line 382, in fire_lasers
    issues = fire_lasers(sym, modules)
  File ".../.local/lib/python3.6/site-packages/mythril/analysis/security.py", line 20, in fire_lasers
    issues += module.execute(statespace)
  File ".../.local/lib/python3.6/site-packages/mythril/analysis/modules/integer.py", line 33, in execute
    issues += _check_integer_underflow(statespace, state, node)
  File ".../.local/lib/python3.6/site-packages/mythril/analysis/modules/integer.py", line 170, in _check_integer_underflow
    interesting_usages = _search_children(statespace, node, (op0 - op1), index=node.states.index(state))
  File ".../.local/lib/python3.6/site-packages/mythril/analysis/modules/integer.py", line 233, in _search_children
    taint_result = TaintRunner.execute(statespace, node, state, initial_stack=taint_stack)
  File ".../.local/lib/python3.6/site-packages/mythril/laser/ethereum/taint_analysis.py", line 107, in execute
    records = TaintRunner.execute_node(node, record, index)
  File ".../.local/lib/python3.6/site-packages/mythril/laser/ethereum/taint_analysis.py", line 139, in execute_node
    records.append(TaintRunner.execute_state(records[-1], current_state))
  File ".../.local/lib/python3.6/site-packages/mythril/laser/ethereum/taint_analysis.py", line 144, in execute_state
    assert len(state.mstate.stack) == len(record.stack)
AssertionError
```

## How to Reproduce
```bash
$ ~/.local/bin/myth -xla 0xac3211a5025414af2866ff09c23fc18bc97e79b1
```
## Expected behavior
Analysis of above contract

## Environment
Myth installed with pip3 install --user ...
```bash
$ /usr/bin/python3 --version
Python 3.6.6
$ ~/.local/bin/myth --version
Mythril version v0.18.11
$ cat /etc/fedora-release 
Fedora release 28 (Twenty Eight)
$ pip3 --version
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
```

**Comment by norhh** [comment]
hey @iljah, can you try it on master, this should work there as this bug was already fixed.

**Comment by iljah** [comment]
That worked, thanks
