### ISSUE TITLE
Z3 sort mismatch error

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/mythril#56]
From within this directory: https://github.com/Modular-Network/ethereum-libraries/tree/audits/CrowdsaleLib/IICOLib/truffle/contracts

I tried with and without the `-l` flag: 

```
$ myth -x -l InteractiveCrowdsaleTestContract.sol
Traceback (most recent call last):
  File "/Users/primary/.pyenv/versions/3.6.1/bin/myth", line 284, in <module>
    states = StateSpace(contracts, dynloader=DynLoader(eth), max_depth=args.max_depth)
  File "/Users/primary/.pyenv/versions/3.6.1/lib/python3.6/site-packages/mythril/analysis/symbolic.py", line 30, in __init__
    self.svm.sym_exec(contracts[0].address)
  File "/Users/primary/.pyenv/versions/3.6.1/lib/python3.6/site-packages/laser/ethereum/svm.py", line 185, in sym_exec
    node = self._sym_exec(context, State())
  File "/Users/primary/.pyenv/versions/3.6.1/lib/python3.6/site-packages/laser/ethereum/svm.py", line 853, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth, constraints=new_constraints)
  File "/Users/primary/.pyenv/versions/3.6.1/lib/python3.6/site-packages/laser/ethereum/svm.py", line 853, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth, constraints=new_constraints)
  File "/Users/primary/.pyenv/versions/3.6.1/lib/python3.6/site-packages/laser/ethereum/svm.py", line 830, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth+1, constraints=new_constraints)
  File "/Users/primary/.pyenv/versions/3.6.1/lib/python3.6/site-packages/laser/ethereum/svm.py", line 772, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth+1, constraints=constraints)
  File "/Users/primary/.pyenv/versions/3.6.1/lib/python3.6/site-packages/laser/ethereum/svm.py", line 286, in _sym_exec
    state.stack.append(state.stack.pop() & state.stack.pop())
  File "/Users/primary/.pyenv/versions/3.6.1/lib/python3.6/site-packages/z3/z3.py", line 3214, in __rand__
    a, b = _coerce_exprs(self, other)
  File "/Users/primary/.pyenv/versions/3.6.1/lib/python3.6/site-packages/z3/z3.py", line 1016, in _coerce_exprs
    s = _coerce_expr_merge(s, b)
  File "/Users/primary/.pyenv/versions/3.6.1/lib/python3.6/site-packages/z3/z3.py", line 1006, in _coerce_expr_merge
    _z3_assert(False, "sort mismatch")
  File "/Users/primary/.pyenv/versions/3.6.1/lib/python3.6/site-packages/z3/z3.py", line 91, in _z3_assert
    raise Z3Exception(msg)
z3.z3types.Z3Exception: sort mismatch
```

I get a similar result for all files in that dir, except for LinkedListLib.sol and Array256Lib.sol.

**Comment by b-mueller** [comment]
Looking into it now!
On a side note you can use the truffle feature here which also outputs the affected line of code:

```
(mythril) Cerebral-Cortex:IICOLib bernhardmueller$ cd truffle/
(mythril) Cerebral-Cortex:truffle bernhardmueller$ myth --truffle
Analysis result for CrowdsaleLib:
==== CALL with gas to dynamic address ====
Type: Warning
Contract: CrowdsaleLib
Function name: _function_0x3617dbba
PC address: 1237
The function _function_0x3617dbba contains a function call to an address provided as a function argument. The available gas is forwarded to the called contract. Make sure that the logic of the calling contract is not adversely affected if the called contract misbehaves (e.g. reentrancy).
--------------------
Affected code:

self.token.balanceOf(this)
--------------------
```

**Comment by b-mueller** [comment]
[Fixed in laser-ethereum](https://github.com/b-mueller/laser-ethereum/commit/073916913c739f73b73b12ccf91d6d54d6e76f7b).

```
$  pip install mythril==0.10.11
```
