### ISSUE TITLE
SpankChain LedgerChannel contract: No contract created

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#566]
## Description

Contract creation fails when analyzing the SpankChain smart contract.

## How to Reproduce

Run myth on code taken from [EtherScan](https://etherscan.io/address/0xf91546835f756da0c10cfa0cda95b15577b84aa7#code).

```
$ $MYTH -x spank.sol:LedgerChannel --create-timeout 1000 --max-depth 1000
WARNING:root:No contract was created during the execution of contract creation Increase the resources for creation execution (--max-depth or --create_timeout)
The analysis was completed successfully. No issues were detected.
```
## Expected behavior

Analysis should run successfully.

**Comment by norhh** [comment]
I think this was fixed on the latest commit from master by @p0n1 .but for some reason the contract doesn't get created, that should probably be checked.

**Comment by b-mueller** [comment]
@norhh you're right, my local repo wasn't synced up. I updated issue name & description.

**Comment by b-mueller** [comment]
Coloredlogs are awesome 👍 

Looks like the creation byte code hits a revert

```
$ $MYTH -x spank.sol:LedgerChannel --create-timeout 1000 --max-depth 1000 -v2
root[14406] DEBUG Signatures: found 36 signatures after parsing
root[14406] INFO LASER EVM initialized with dynamic loader: None
root[14406] DEBUG Starting LASER execution
root[14406] INFO Starting contract creation transaction
root[14406] DEBUG Evaluating PUSH1
root[14406] DEBUG Evaluating PUSH1
root[14406] DEBUG Evaluating MSTORE
root[14406] DEBUG MSTORE to mem[64]: 128
root[14406] DEBUG Evaluating PUSH1
root[14406] DEBUG Evaluating DUP1
root[14406] DEBUG Evaluating SSTORE
root[14406] DEBUG Write to storage[0]
root[14406] DEBUG Evaluating CALLVALUE
root[14406] DEBUG Evaluating DUP1
root[14406] DEBUG Evaluating ISZERO
root[14406] DEBUG Evaluating PUSH2
root[14406] DEBUG Evaluating JUMPI
root[14406] DEBUG Evaluating JUMPDEST
root[14406] DEBUG Evaluating POP
root[14406] DEBUG Evaluating PUSH2
root[14406] DEBUG Evaluating DUP1
root[14406] DEBUG Evaluating PUSH3
root[14406] DEBUG Evaluating PUSH1
root[14406] DEBUG Evaluating CODECOPY
root[14406] DEBUG Evaluating PUSH1
root[14406] DEBUG Evaluating RETURN
root[14406] DEBUG Evaluating PUSH1
root[14406] DEBUG Evaluating DUP1
root[14406] DEBUG Evaluating REVERT
root[14406] INFO Finished contract creation, found 0 open states
```

**Comment by dmuhs** [comment]
The point where the `REVERT` happens has `node.function_name` set to `constructor`. It `LedgerChannel` doesn't have an explicit constructor, but maybe it's triggered by something like this
```
struct Channel {
        //TODO: figure out if it's better just to split arrays by balances/deposits instead of eth/erc20
        address[2] partyAddresses; // 0: partyA 1: partyI
        uint256[4] ethBalances; // 0: balanceA 1:balanceI 2:depositedA 3:depositedI
        uint256[4] erc20Balances; // 0: balanceA 1:balanceI 2:depositedA 3:depositedI
        uint256[2] initialDeposit; // 0: eth 1: tokens
        uint256 sequence;
        uint256 confirmTime;
        bytes32 VCrootHash;
        uint256 LCopenTimeout;
        uint256 updateLCtimeout; // when update LC times out
        bool isOpen; // true when both parties have joined
        bool isUpdateLCSettling;
        uint256 numOpenVC;
        HumanStandardToken token;
    }
```
which initializes the `HumanStandardToken` contract. The output of `./myth -x spank.sol:HumanStandardToken` is
```
WARNING:root:No contract was created during the execution of contract creation Increase the resources for creation execution (--max-depth or --create_timeout)
<valid report stuff>
```
and looking at it with `-v2` shows the same opcode order:
```
root[29303] DEBUG Evaluating PUSH1
root[29303] DEBUG Evaluating DUP1
root[29303] DEBUG Evaluating REVERT
```

When I try to further drill down to the `StandardToken` contract, Mythril keeps on running at as soon as it hits about 9GB of RAM I'm forced to kill it. :laughing: Seemingly the issue is somewhere around the token contracts, though.

**Comment by JoranHonig** [comment]
https://github.com/ConsenSys/mythril/pull/568 Fixes the problem, with contract creation.
I'm now looking at the reentrancy itself

**Comment by b-mueller** [comment]
With #568 applied I get the same `IndexError` mentioned in #574:

```console
$ $MYTH -x spank.sol:LedgerChannel
Traceback (most recent call last):
  File "/Users/bernhardmueller/Projects/mythril/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/Users/bernhardmueller/Projects/mythril/mythril/interfaces/cli.py", line 221, in main
    create_timeout=args.create_timeout)
  File "/Users/bernhardmueller/Projects/mythril/mythril/mythril.py", line 370, in fire_lasers
    create_timeout=create_timeout)
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/symbolic.py", line 54, in __init__
    instruction = state.get_current_instruction()
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/state.py", line 266, in get_current_instruction
    return instructions[self.mstate.pc]
IndexError: list index out of range
```

**Comment by b-mueller** [comment]
This now works for me with Mythril master (however the problem described in #574 still persists).
