### ISSUE TITLE
IndexError on token.sol

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#574]
## Description

Mythril terminates with and `IndexError` on the following input code:

```
contract Token{

    mapping(address => uint) public balances;
    function airdrop() public{
        balances[msg.sender] = 1000;
    }

    function consume() public{ 
        require(balances[msg.sender]>0);
        balances[msg.sender] -= 1;
    }

    function backdoor() public{
        balances[msg.sender] += 1;
    }
 
   function test_invariants() {
      assert(balances[msg.sender] <= 1000);
  }
}
```

## How to Reproduce

```console
$ $MYTH -x token-invariant.sol 
Traceback (most recent call last):
  File "/Users/bernhardmueller/Projects/mythril/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/Users/bernhardmueller/Projects/mythril/mythril/interfaces/cli.py", line 221, in main
    create_timeout=args.create_timeout)
  File "/Users/bernhardmueller/Projects/mythril/mythril/mythril.py", line 370, in fire_lasers
    create_timeout=create_timeout)
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/symbolic.py", line 54, in __init__
    instruction = state.get_current_instruction()
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/state.py", line 266, in get_current_instruction
    return instructions[self.mstate.pc]
IndexError: list index out of range
```

## Environment

- Mythril version: Master
- Solidity compiler and version: 0.4.24+commit.e67f0147.Darwin.appleclang
- Python version: 3.6.3
- OS and Version: Mac OS Mojave

**Comment by b-mueller** [comment]
Probably related to #566, #568:

```console
(mythril) cerebral-cortex:Desktop bernhardmueller$ $MYTH -x token-invariant.sol -v2
root[26306] DEBUG Signatures: found 5 signatures after parsing
root[26306] INFO LASER EVM initialized with dynamic loader: None
root[26306] DEBUG Starting LASER execution
root[26306] INFO Starting contract creation transaction
root[26306] DEBUG Evaluating PUSH1
root[26306] DEBUG Evaluating PUSH1
root[26306] DEBUG Evaluating MSTORE
root[26306] DEBUG MSTORE to mem[64]: 128
root[26306] DEBUG Evaluating CALLVALUE
root[26306] DEBUG Evaluating DUP1
root[26306] DEBUG Evaluating ISZERO
root[26306] DEBUG Evaluating PUSH2
root[26306] DEBUG Evaluating JUMPI
root[26306] DEBUG Evaluating JUMPDEST
root[26306] DEBUG Evaluating POP
root[26306] DEBUG Evaluating PUSH2
root[26306] DEBUG Evaluating DUP1
root[26306] DEBUG Evaluating PUSH2
root[26306] DEBUG Evaluating PUSH1
root[26306] DEBUG Evaluating CODECOPY
root[26306] DEBUG Evaluating PUSH1
root[26306] DEBUG Evaluating RETURN
root[26306] DEBUG Evaluating PUSH1
root[26306] DEBUG Evaluating DUP1
root[26306] DEBUG Evaluating REVERT
root[26306] INFO Finished contract creation, found 1 open states
root[26306] INFO Starting message call transaction, iteration: 0
root[26306] INFO Finished symbolic execution
root[26306] INFO 4 nodes, 3 edges, 19 total states
Traceback (most recent call last):
  File "/Users/bernhardmueller/Projects/mythril/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/Users/bernhardmueller/Projects/mythril/mythril/interfaces/cli.py", line 221, in main
    create_timeout=args.create_timeout)
  File "/Users/bernhardmueller/Projects/mythril/mythril/mythril.py", line 370, in fire_lasers
    create_timeout=create_timeout)
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/symbolic.py", line 54, in __init__
    instruction = state.get_current_instruction()
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/state.py", line 266, in get_current_instruction
    return instructions[self.mstate.pc]
IndexError: list index out of range
```

**Comment by b-mueller** [comment]
This is what I get with patch #568 applied:

```console
(mythril) cerebral-cortex:Desktop bernhardmueller$ $MYTH -x token-invariant.sol -v2
root[29248] DEBUG Signatures: found 5 signatures after parsing
root[29248] INFO LASER EVM initialized with dynamic loader: None
root[29248] DEBUG Starting LASER execution
root[29248] INFO Starting contract creation transaction
root[29248] DEBUG Evaluating PUSH1
root[29248] DEBUG Evaluating PUSH1
root[29248] DEBUG Evaluating MSTORE
root[29248] DEBUG MSTORE to mem[64]: 128
root[29248] DEBUG Evaluating CALLVALUE
root[29248] DEBUG Evaluating DUP1
root[29248] DEBUG Evaluating ISZERO
root[29248] DEBUG Evaluating PUSH2
root[29248] DEBUG Evaluating JUMPI
root[29248] DEBUG Evaluating JUMPDEST
root[29248] DEBUG Evaluating POP
root[29248] DEBUG Evaluating PUSH2
root[29248] DEBUG Evaluating DUP1
root[29248] DEBUG Evaluating PUSH2
root[29248] DEBUG Evaluating PUSH1
root[29248] DEBUG Evaluating CODECOPY
root[29248] DEBUG Evaluating PUSH1
root[29248] DEBUG Evaluating RETURN
root[29248] DEBUG Evaluating PUSH1
root[29248] DEBUG Evaluating DUP1
root[29248] DEBUG Evaluating REVERT
root[29248] INFO Finished contract creation, found 1 open states
root[29248] INFO Starting message call transaction, iteration: 0
root[29248] INFO Finished symbolic execution
root[29248] INFO 4 nodes, 3 edges, 19 total states
Traceback (most recent call last):
  File "/Users/bernhardmueller/Projects/mythril/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/Users/bernhardmueller/Projects/mythril/mythril/interfaces/cli.py", line 221, in main
    create_timeout=args.create_timeout)
  File "/Users/bernhardmueller/Projects/mythril/mythril/mythril.py", line 370, in fire_lasers
    create_timeout=create_timeout)
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/symbolic.py", line 54, in __init__
    instruction = state.get_current_instruction()
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/state.py", line 266, in get_current_instruction
    return instructions[self.mstate.pc]
IndexError: list index out of range
```

**Comment by b-mueller** [comment]
Interesting observation: Running `myth` on `soldity_examples/suicide.sol` returns the exact same debugging output and I end up with `4 nodes, 3 edges, 19 total states`:

```
$ $MYTH -x solidity_examples/suicide.sol -v2
root[54215] DEBUG Signatures: found 1 signatures after parsing
root[54215] INFO LASER EVM initialized with dynamic loader: None
root[54215] DEBUG Starting LASER execution
root[54215] INFO Starting contract creation transaction
(...)
root[54215] INFO Finished contract creation, found 1 open states
root[54215] INFO Starting message call transaction, iteration: 0
root[54215] INFO Finished symbolic execution
root[54215] INFO 4 nodes, 3 edges, 19 total states
Traceback (most recent call last):
  File "/Users/bernhardmueller/Projects/mythril/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/Users/bernhardmueller/Projects/mythril/mythril/interfaces/cli.py", line 223, in main
    max_transaction_count=args.max_transaction_count)
  File "/Users/bernhardmueller/Projects/mythril/mythril/mythril.py", line 372, in fire_lasers
    max_transaction_count=max_transaction_count)
  File "/Users/bernhardmueller/Projects/mythril/mythril/analysis/symbolic.py", line 55, in __init__
    instruction = state.get_current_instruction()
  File "/Users/bernhardmueller/Projects/mythril/mythril/laser/ethereum/state.py", line 266, in get_current_instruction
    return instructions[self.mstate.pc]
IndexError: list index out of range
```
