### ISSUE TITLE
Unhandled exception in analyze_truffle_project 

### ISSUE THREAD

**Issue by thec00n** [ConsenSys/mythril#60]
Reproduce:
myth -v2 --truffle
Let me know if the project is required to reproduce the issue.

Output:

`INFO:root:Executing <module 'weak_random' from '/Users/lol/.pyenv/versions/3.6.4/lib/python3.6/site-packages/mythril-0.10.13-py3.6.egg/mythril/analysis/modules/weak_random.py'>
DEBUG:root:Executing module: WEAK_RANDOM
Traceback (most recent call last):
  File "/Users/lol/.pyenv/versions/3.6.4/bin/myth", line 4, in <module>
    __import__('pkg_resources').run_script('mythril==0.10.13', 'myth')
  File "/Users/lol/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/lol/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "/Users/lol/.pyenv/versions/3.6.4/lib/python3.6/site-packages/mythril-0.10.13-py3.6.egg/EGG-INFO/scripts/myth", line 146, in <module>
    analyze_truffle_project()
  File "/Users/lol/.pyenv/versions/3.6.4/lib/python3.6/site-packages/mythril-0.10.13-py3.6.egg/mythril/support/truffle.py", line 72, in analyze_truffle_project
    for key, issue in report.issues.items():
AttributeError: 'list' object has no attribute 'issues'`

**Comment by b-mueller** [comment]
Fixed [cfad73e](https://github.com/ConsenSys/mythril/commit/cfad73e2b63649050759c4538c727af4bc9f536a)
