### ISSUE TITLE
Another `IndexError: list index out of range`

### ISSUE THREAD

**Issue by thoppe** [ConsenSys/mythril#76]
**Version** `mythril==0.13.9`

Perhaps related to #25, contract [`0xE0F7e56e61b4267062172494D7506087205A4229`](https://etherscan.io/address/0xe0f7e56e61b4267062172494d7506087205a4229) fails to parse. Etherscan shows there are 89,000 [other contracts](https://etherscan.io/find-similiar-contracts?a=0xe0f7e56e61b4267062172494d7506087205a4229&lvl=5) with this matching bytecode, a large fraction of which were created at the same time?

``` bash
>> myth --rpc localhost:8545 -x -a 0xE0F7e56e61b4267062172494D7506087205A4229

Traceback (most recent call last):
  File "/usr/local/bin/myth", line 406, in <module>
    issues = fire_lasers(sym)
  File "/usr/local/lib/python3.5/dist-packages/mythril/analysis/security.py", line 19, in fire_lasers
    issues += module.execute(statespace)
  File "/usr/local/lib/python3.5/dist-packages/mythril/analysis/modules/unchecked_retval.py", line 53, in execute
    _state = call.node.states[call.state_index + i]
IndexError: list index out of range
```

**Comment by b-mueller** [comment]
Working for me now so I'm closing this :)

```
$ myth --infura-mainnet -x -a 0xE0F7e56e61b4267062172494D7506087205A4229
==== Message call to external contract ====
Type: Warning
Contract: 0xE0F7e56e61b4267062172494D7506087205A4229
Function name: fallback
PC address: 377
The function fallback contains a function call to an address provided as a function argument.The available gas is forwarded to the called contract. Make sure that the logic of the calling contract is not adversely affected if the called contract misbehaves (e.g. reentrancy).
--------------------

==== Exception state ====
Type: Informational
Contract: 0xE0F7e56e61b4267062172494D7506087205A4229
Function name: fallback
PC address: 384
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that assert() should only be used to check invariants. Use require() for regular input checking. The exception is triggered under the following conditions:

extcodesize: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
caller: 0x0
storage_0: 0x0
calldata_0xE0F7e56e61b4267062172494D7506087205A4229_0: 0x29b5b30c00000000000000000000000000000000000000000000000000000000
calldatasize_0xE0F7e56e61b4267062172494D7506087205A4229: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
retval_378: 0x0
callvalue: 0x0

--------------------

(...)

==== Unchecked CALL return value ====
Type: Informational
Contract: 0xE0F7e56e61b4267062172494D7506087205A4229
Function name: _function_0xe5225381
PC address: 500
The return value of an external call is not checked. Note that execution continue even if the called contract throws.
--------------------
```
