### ISSUE TITLE
Z3 integer exception

### ISSUE THREAD

**Issue by mahjiang** [ConsenSys/mythril#988]
## Description

Getting this error using Mythril 0.20.2 for vulnerability detection:

```
$ myth -x Contract.sol 
mythril.mythril [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mythril/mythril.py", line 592, in fire_lasers
    enable_iprof=enable_iprof,
  File "/usr/local/lib/python3.7/site-packages/mythril/analysis/symbolic.py", line 102, in __init__
    creation_code=contract.creation_code, contract_name=contract.name
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/svm.py", line 151, in sym_exec
    self._execute_transactions(created_account.address)
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/svm.py", line 190, in _execute_transactions
    execute_message_call(self, address)
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/transaction/symbolic.py", line 58, in execute_message_call
    laser_evm.exec()
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/svm.py", line 236, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/svm.py", line 285, in execute_state
    self._execute_pre_hook(op_code, global_state)
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/ethereum/svm.py", line 562, in _execute_pre_hook
    hook(global_state)
  File "/usr/local/lib/python3.7/site-packages/mythril/analysis/modules/integer.py", line 108, in execute
    func(state)
  File "/usr/local/lib/python3.7/site-packages/mythril/analysis/modules/integer.py", line 119, in _handle_add
    op0, op1 = self._get_args(state)
  File "/usr/local/lib/python3.7/site-packages/mythril/analysis/modules/integer.py", line 113, in _get_args
    self._make_bitvec_if_not(stack, -1),
  File "/usr/local/lib/python3.7/site-packages/mythril/analysis/modules/integer.py", line 186, in _make_bitvec_if_not
    stack[index] = symbol_factory.BitVecVal(value, 256)
  File "/usr/local/lib/python3.7/site-packages/mythril/laser/smt/__init__.py", line 128, in BitVecVal
    raw = z3.BitVecVal(value, size)
  File "/usr/local/lib/python3.7/site-packages/z3/z3.py", line 3741, in BitVecVal
    return BitVecNumRef(Z3_mk_numeral(ctx.ref(), _to_int_str(val), BitVecSort(bv, ctx).ast), ctx)
  File "/usr/local/lib/python3.7/site-packages/z3/z3.py", line 2925, in _to_int_str
    _z3_assert(False, "Python value cannot be used as a Z3 integer")
  File "/usr/local/lib/python3.7/site-packages/z3/z3.py", line 92, in _z3_assert
    raise Z3Exception(msg)
z3.z3types.Z3Exception: Python value cannot be used as a Z3 integer
```

## Environment

- Mac OS Mojave 10.14.3
- Mythril 0.20.2
- Solidity 0.4.25
- Python 3.7.3

**Comment by norhh** [comment]
Hi @mahjiang , thanks for reporting the issue.By any chance can you post the contract code, or at least the minimal version of the code which might result in the error. That would be quite helpful

**Comment by JoranHonig** [comment]
@norhh Can you try to reproduce this locally? Otherwise we'll have to close this issue

**Comment by norhh** [comment]
@mahjiang I can't unfortunately reproduce it locally, tried it with a lot of contracts, try running the contract with `v0.20.4`, If the problem still persists please feel free to reopen this issue.

**Comment by Danc2050** [comment]
@norhh I discovered multiple contracts that produce this error. Let me know if you would like other addresses for solving this issue. 
# To reproduce
Run `myth -v4 analyze -1 --execution-timeout 3600 -a 0x126c473bf26360075e084555687dB4FF4B7C917e`
